danskernesdigitalebibliotek/dpl-react

- .github/workflows/code_coverage.yml
- .github/workflows/pages.yml
- .github/workflows/release.yml
Because dpl-react is using "main" and it's standard to do so.
> Changing "master" branch definitions in gh actions

- .github/workflows/code_coverage.yml
- .github/workflows/pages.yml
- .github/workflows/release.yml
Because dpl-react is using "main" and it's standard to do so.
> Change "master" branch definitions in gh actions

- .github/workflows/code_coverage.yml
- .github/workflows/pages.yml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- .yarnrc
- package.json
- yarn.lock
Github has a policy that only allows read access to their npm registry by using a token.
Either PAT or GITHUB_TOKEN.
This PR uses `secrets.GITHUB_TOKEN` in order to get access.
Look at the commits.
And verify that GH actions pass.
https://reload.atlassian.net/browse/DDFSOEG-113
> Add GH token to setup-node tasks

- README.md
- package.json
- src/components/availability-label/availability-label.dev.tsx
- yarn.lock
There was an error in indentation of argument types for the Availability label story, which prevented the default values to be read.
> Fix availability label stories and eslint settings

- .eslintrc
- architecture/adr-002-ui-text-handling.md
- docs/ui_text_handling.md
- src/apps/hello-world/hello-world.dev.tsx
- src/apps/hello-world/hello-world.entry.tsx
- src/apps/hello-world/hello-world.tsx
- src/components/hello/hello.dev.tsx
- src/components/hello/hello.tsx
- src/core/store.ts
- src/core/text.slice.ts
- src/core/utils/text.tsx
With this initiative we can access strings in nested components inside 
the apps without passing props.
https://reload.atlassian.net/browse/DDFSOEG-122
A high order component wraps the entry component and puts all props that ends with `*Text` in the redux store.
When the strings are needed you implement the `useText()` hook that returns a function that you can use to fetch them
> Add functionality for handling app string props

- .browserslistrc
- package.json
- webpack.config.js
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-176
Performance checks at https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/118 shows that we are running into performance problems due to the amount of JavaScript we deliver to clients.
One way to reduce this is to not cross compile our code to legacy browsers as this will require a lot of polyfills. [This is also a suggestion mentioned by Lighthouse](https://storage.googleapis.com/lighthouse-infrastructure.appspot.com/reports/1659519745506-91116.report.html#legacy-javascript). According to our coding guidelines we do not have to support legacy browsers.
This PR updates our `.browserslists` configuration to match our coding guidelines.
In general we should be aware of our bundle size. The current tool included in the project is not in …
> Only cross-compile code to modern browsers

- src/apps/search-header/search-header.tsx
- src/components/search-bar/search-bar.tsx
https://reload.atlassian.net/browse/DDFSOEG-176
Accessibility checks at danskernesdigitalebibliotek/dpl-cms#118 shows a problem where an ARIA property is added to the form element where it is not valid.
The ARIA role comes from Downshift `getInputProps()`. This PR moves it from the `<form>` to a `<div/>`  which wraps the `<input/>` element. This is in accordance with [Downshift documentation and examples](https://www.downshift-js.com/use-combobox).
As far as I remember we have experienced problems with using a form as the outer element. My initial testing shows that this is not the case.
The PR also includes a bit of boyscouting in relation to the search header.
https://user-images.githubusercontent.com/73966/182362468-53bf3374-5757-46a9-9575-63b738ce57c4.mp4
> Improve accessibility for search header

- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/components/material/MaterialDescription.tsx
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.tsx
https://reload.atlassian.net/browse/DDFSOEG-153
This PR introduces "Emnetal" / fictionNonfiction.
It is displayed in the HorizontalTermLine in the same way as the rest of the data.
> Add fictionNonfiction / emnetal to Material description  

- src/components/material/MaterialHeader.tsx
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.tsx
https://reload.atlassian.net/browse/DDFSOEG-148
This change checks if the language contains "dansk" and if not it will be displayed together with the title.
c. Title-full - og såfremt værket er en bog, som ikke er på dansk - sprog i parentes efter Title-full
**This is a reverse example because there are only languages that contain "dansk"**
> Add logic to display language in title

- src/components/autosuggest-material/autosuggest-material.tsx
https://reload.atlassian.net/browse/DDFSOEG-191
Using autosuggest material item workId as key for mapped suggestion items makes sure that mapped element's keys stay the same between specific items across reloads. Thus the items won't be re-rendered when they the items stay the same - thus the cover pictures won't flash.
https://user-images.githubusercontent.com/28546954/183887537-343c6ca4-791f-4830-a65e-125ab3e3d9d5.mov
n/a
> Fix reloading covers for autosuggest - material suggestions

- src/components/button-favourite/button-favourite.dev.tsx
- src/components/button-favourite/button-favourite.tsx
- src/components/material/MaterialHeader.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
https://reload.atlassian.net/browse/DDFSOEG-34
This PR is a review of button favorite compared to MK. 
The button has been changed so that it now uses a specific type of id instead of just a string
- Variation 3a has not been made
> Fix button favourite

- README.md
- docs/code_guidelines.md
This should clarify the primary language of the project.
> Reference TypeScript instead of JavaScript in documentation

- cypress/fixtures/material/availability.json
- cypress/fixtures/material/cover.json
- cypress/fixtures/material/fbi-api.json
- src/apps/material/material.dev.tsx
- src/apps/material/material.test.ts
- src/core/dbc-gateway/graphql-fetcher.ts
https://reload.atlassian.net/browse/DDFSOEG-188
This PR sets up a cypress test that checks the material app and it also fixes the pathname problem.
- The test uses mockup data to check if data is rendered in the right places
**This commit fixes the pathname bug 9306dfbfab7a8bcb0ac40c718358aaffdd32d7c9**
> Material app e2e + it also fixes the pathname problem

- src/apps/search-header/search-header.dev.tsx
- src/apps/search-header/search-header.entry.tsx
- src/apps/search-header/search-header.tsx
- src/components/autosuggest-material/autosuggest-material.tsx
- src/core/store.ts
- src/core/utils/withSuffix.tsx
https://reload.atlassian.net/browse/DDFSOEG-185
This PR makes sure that linking from the search header app to search result app/material app works when the apps are set into the CMS.  
The biggest challenge here was distinguishing between the different kinds of suggestion items. If it is one of the string suggestions - we redirect to the search result; if it is a material suggestion - we redirect to the material app page. 
n/a
n/a
> Feature/link from search header to search results app + material app

- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/apps/material/material.graphql
- src/apps/material/material.tsx
- src/components/material/MaterialHeader.tsx
- src/core/dbc-gateway/generated/graphql.schema.json
- src/core/dbc-gateway/generated/graphql.tsx
Since we have decided to use full work id when using the material app we need to change the inner workings, query etc.
As it is now we use the newest manifestation pid as the pid for choosing cover etc. That will change when we have implemented using the type parameter
> Use workid in material app

- src/core/mount.js
In 748a9f7567b29fbd33630fd00d5c56c4d6874883 react-error-boundary was updated from v1 to v3. This update requires changes in [how the library is used as a higher order component](https://github.com/bvaughn/react-error-boundary#usage).
This PR adds the required `FallbackComponent` and an `onError` handler which for now logs errors to the console. This should make it easier to understand what happens when an error occurs.
Without this change any errors will result in an error in the error boundary due to the missing fallback component.
> Update error boundary handling

- package.json
- src/components/horizontal-term-line/HorizontalTermLine.tsx
- src/components/material/MaterialDescription.tsx
- src/components/material/MaterialHeaderText.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.schema.json
- src/core/dbc-gateway/generated/graphql.tsx
- src/core/store.ts
- src/core/utils/withSuffix.tsx
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-187
-> refers to image below
This PR adjust the Horizontal Term Line component (that's all those underscored lines of text on image above) to not create links itself, but instead receives them ready made. This "dumb-ifying" of the component lets us decide where to redirect before calling the component. ("I samme serie" items redirect to material page, as opposed to the rest.)
Minor updates to the graphQL schema adding workId as one of the keys for the array of "in the same series as". We need the WorkId to create links to material page.
n/a
n/a
> Linkability from material page to search results & material page

- src/apps/material/helper.ts
- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/apps/material/material.tsx
- src/components/availability-label/availability-label.tsx
- src/components/availability-label/availability-labels.tsx
- src/components/material/MaterialHeader.tsx
- src/components/material/MaterialMainfestationItem.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.schema.json
- src/core/dbc-gateway/generated/graphql.tsx
- src/core/utils/helpers/general.ts
- src/core/utils/helpers/url.ts
https://reload.atlassian.net/browse/DDFSOEG-154
https://reload.atlassian.net/browse/DDFSOEG-190
https://reload.atlassian.net/browse/DDFSOEG-160
This PR adds select work manifestation logic and display the cover image for the selected manifestation and added more logic to details on material details and edition details.
- Material type is now specified in the URL and will be set to first published manifestation if not. 
- A currentManifestation state has been added so that we can choose based on it how the material page should be displayed, for example, cover and buttons.
- Availability labels can be clicked on to change both state and URL
- Availability labels show as selected if the type of material text is the same
- logic that shows details from fallback manifestation if there is no …
> Material select work manifestation + cover change + details v2

- package.json
- src/components/material/disclosures/disclosure.tsx
- yarn.lock
Bi-product of https://reload.atlassian.net/browse/DDFSOEG-150
This PR updates the dpl-design-system package which introduces a new utility class "invert" that we use to get inverted disclosure icons.
> Use invert class in disclosures

- .eslintrc
- cypress/support/index.js
- cypress/support/index.ts
- package.json
- src/apps/material/material.entry.tsx
- src/apps/search-header/search-header.entry.tsx
- src/apps/search-header/search-header.tsx
- src/apps/search-result/search-result.dev.tsx
- src/apps/search-result/search-result.entry.tsx
- src/components/button-favourite/button-favourite.dev.tsx
- src/components/button-favourite/button-favourite.tsx
- src/components/guarded-app.tsx
- src/components/material/MaterialHeader.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/components/store.jsx
- src/core/guardedRequests.slice.ts
- src/core/store.ts
- src/core/utils/helpers/date.ts
- src/core/utils/helpers/url.ts
- src/core/utils/helpers/user.ts
- src/core/utils/types/ids.ts
- src/core/utils/withSuffix.tsx
- yarn.lock
This PR is dealing with the scenario where a user wants to perform an action that is prohibited for anonymous users.
As it is now It has been implemented on the favourite button on search results and on the material page.
The flow that is covers:
* An anonymous user clicks the favourite button
* The request that should be fired for storing the material on the users favourite list is persisted via redux-persist
* The user is being redirected to dpl-cms via the authUrl that has been provided to the app. The authUrl gets a `current-path` url parameter attached so the user is redirected back to place where the favourite button was clicked.
* User logs in.
* User is being rediredted back to where the user came from
* The persisted request is fired and the app is being blocked until the request …
> indloggetudlogget funktionalitet DDFSOEG 178

- package.json
- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/apps/material/material.test.ts
- src/apps/material/material.tsx
- src/components/material/MaterialHeader.tsx
- src/components/material/MaterialPeriodical.tsx
- src/components/material/MaterialPeriodicalSelect.tsx
- src/components/material/MaterialPeriodikum.tsx
- src/components/material/MaterialPeriodikumSelect.tsx
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.schema.json
- src/core/dbc-gateway/generated/graphql.tsx
- src/core/utils/helpers/general.ts
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-182
Is a wrapper component that is only rendered if a manifestation has a source that matches types that needs a PeriodicalSelect. it also fetches data with useGetHoldingsV3 and manipulates it before it renders MaterialPeriodicalSelect
Has a setState function (selectPeriodicalSelect)  that comes from the root in the Material app. This will be used later...
** groupBy  global function needs to be rewritten to typeScript **
> Add MaterialPeriodical

- .nycrc
- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/components/availability-label/availability-label.tsx
- src/components/availability-label/availability-labels.tsx
- src/components/material/MaterialAvailabilityText/MaterialAvailabilityText.tsx
- src/components/material/MaterialAvailabilityText/generic/MaterialAvailabilityTextParagraph.tsx
- src/components/material/MaterialAvailabilityText/online/MaterialAvailabilityTextOnline.tsx
- src/components/material/MaterialAvailabilityText/physical/MaterialAvailabilityTextPhysical.tsx
- src/components/material/MaterialHeader.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/publizon/mutator/fetcher.ts
https://reload.atlassian.net/browse/DDFSOEG-149
That checks whether the manifestation accessTypes is PHYSICAL or ONLINE where after it shows **MaterialAvailabilityTextPhysical**, **MaterialAvailabilityTextOnline** or both
Takes a PID id which it then turns into a FaustId and uses useGetHoldingsV3 to get total materials and total reservations
Takes an ISBN number and uses useGetV1ProductsIdentifier to  check if manifestation is costFree (blue title)
useGetV1UserLoansIdentifier must be used to find user's totalEbookLoans and ebookLoansRemaining
> Info text under buttons in the material header.

- src/components/material/MaterialMainfestationItem.tsx
This bug was created during merge conflicts when merging in my last PR.
Before:
After:
n/a
> Fix/material-buttons - don't show "find on shelf" button twice on work manifestations

- package.json
- src/apps/material/helper.ts
- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/apps/material/material.tsx
- src/components/Buttons/ButtonSmallFilled.tsx
- src/components/availability-label/availability-labels.tsx
- src/components/material/MaterialAvailabilityText/physical/MaterialAvailabilityTextPhysical.tsx
- src/components/material/MaterialHeader.tsx
- src/components/material/MaterialMainfestationItem.tsx
- src/components/material/material-buttons/MaterialButtons.tsx
- src/components/material/material-buttons/physical/MaterialButtonPhysical.tsx
- src/components/material/material-buttons/physical/MaterialButtonsPhysical.tsx
- src/components/reservation/ReservationError.tsx
- src/components/reservation/ReservationFormListItem.tsx
- src/components/reservation/ReservationSucces.tsx
- src/components/reservation/UserListItems.tsx
- src/components/reservation/reservation-modal.tsx
- src/core/utils/helpers/general.ts
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-203
The modal is opened after the reservation button has been pressed. Here shows the material and user information.
if the user confirms, and if it is approved it shows ReservationSucces  else is shows ReservationError
Here is added: 
- markup and CSS classes from design-system
- a reusable ReservationFormListItem
- ReservationSucces + ReservationError components 
- add all the translations that are needed
**2 help functions:**
- **getNoInterestAfter**: 
rewrite days into months
- **getPreferredLocation**: 
find branch name with id
> Reservation modal

- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/components/Buttons/Button.tsx
- src/components/material/material-buttons/online/MaterialButtonOnlineExternal.tsx
- src/components/material/material-buttons/physical/MaterialButtonsPhysical.tsx
- src/components/reservation/ReservationError.tsx
- src/components/reservation/ReservationSucces.tsx
- src/components/reservation/reservation-modal.tsx
This PR use response from mutate (useAddReservationsV2) to determine whether to show success or error component after confirming the reservation.
**ReservationSucces**  shows
- title
- numberInQueue
- preferredPickupBranch
if reservationResult === "already_reserved"  **ReservationError**  shows
> Confirming the reservation

- src/apps/loan-list/modal/due-date-loans-modal.tsx
- src/apps/loan-list/modal/material-details-modal.tsx
- src/apps/loan-list/modal/renew-loans-modal.tsx
- src/components/find-on-shelf/FindOnShelfModal.tsx
- src/components/reservation/reservation-modal.tsx
- src/core/utils/modal.tsx
This PR adds padding to reservation modal + change the  modal prop name from additionalClasses to classNames
> Change prop name from additionalClasses to classNames

- .vscode.example/dpl-react.code-snippets
- src/apps/search-result/search-result.tsx
- src/components/result-pager/use-pager.tsx
This PR does 3 things
- Hide pager component if no results
- Only render SearchResultHeader + SearchResultList if worksAreLoaded
This prevents that there will be a flash of a zero result search page before the result are ready
- Adding debug snippet
> Only render SearchResultHeader + SearchResultList if worksAreLoaded

- src/apps/material/material.test.ts
- cy.visit() is moved to the bottom of beforeEach 
- instead of opening all the details, only the last one is now selected, which is the one for the material
> Fix broken material test

- src/components/find-on-shelf/FindOnShelfModal.tsx
- src/components/material/disclosures/disclosure.tsx
https://reload.atlassian.net/browse/DDFSOEG-223
This PR makes changes to the Find on shelf modal and the disclosure component. 
It is only the last two commits that you need to address (b52d2a3 and e4a7ec9).
The rest is from find-on-shelf-manifestation-info branch that has its own PR.
> Find on shelf - open branch disclosure if it's the only one present

- src/apps/material/helper.ts
- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/components/reservation/ReservationSucces.tsx
- src/components/reservation/UserListItems.tsx
- src/components/reservation/forms/ModalReservationFormSelect.tsx
- src/components/reservation/forms/PickupModal.tsx
- src/components/reservation/forms/helper.ts
- src/components/reservation/helper.ts
- src/components/reservation/reservation-modal.tsx
This PR gives the opportunity to change where you want to collect the material
A useState (selectedBranch) has been added in ReservationModal which sets the user's preferredPickupBranch with a useEffect. 
setState is prop drilling until ModalReservationFormSelect from where it can be changed
> Makes it possible to change the pick-up point for a reservation

- src/apps/loan-list/list/list.tsx
- src/components/find-on-shelf/FindOnShelfModal.tsx
https://reload.atlassian.net/browse/DDFSOEG-226
This PR orders find on shelf modal library branches alphabetically (with the exception of the main branch, which is always first).
n/a
> Sort find on shelf modal library branches alphabetically

- package.json
- src/apps/loan-list/list/list.tsx
- src/components/find-on-shelf/FindOnShelfModal.tsx
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-225
This PR introduces sorting library branches in "find on shelf modal" in **groups** - branches that have at least one available manifestation are shown first and branches without any available specimens are shown last (with the exception of any main branches that are shown on the top regardless).
n/a
> Feature/find on shelf/show unavailable branches last

- .github/workflows/build.yml
- .github/workflows/pull_request.yml
- .github/workflows/relative_ci.yml
- architecture/adr-004-relative-ci.md
This PR adds the configuration of Relative CI to the `release/4` branch. This is needed to make PRs from forks report statistics which can be compared with the base repository.
The actual commits should be the same as in #151 which will make it possible to merge `release/4` into `main` without problems eventually.
> Add Relative CI (release 4)

- cypress/fixtures/material/periodical-fbi-api.json
- cypress/fixtures/material/periodical-holdings.json
- src/apps/material/material.dev.tsx
- src/apps/material/material.test.ts
- src/apps/material/material.tsx
- src/components/material/MaterialHeader.tsx
- src/components/material/MaterialPeriodical.tsx
- src/components/material/MaterialPeriodicalSelect.tsx
- src/components/material/periodical/MaterialPeriodical.tsx
- src/components/material/periodical/MaterialPeriodicalSelect.tsx
- src/components/material/periodical/helper.ts
- src/components/reservation/ReservationFormListItem.tsx
- src/components/reservation/ReservationModal.tsx
- src/components/reservation/ReservationModalBody.tsx
- src/components/reservation/helper.ts
To find out if it is a periodical we need to look for manifestation materialTypes and not source as we previously thought
Other changes:
- adds an extra story to be able to display a periodical
- change periodicalSelect (useState) to type GroupListItem instead of string
> Add reserve a periodical logic

- .vscode.example/launch.json
- README.md
Yes!!! Found my way in configuring vs code for step debugging.
Configuration was taken from this article:
https://blog.bruceleeharrison.com/2022/01/26/debug-storybook-from-vscode-2022/
> Add working example of vscode debugging conf (dockerless)

- src/components/material/material-buttons/MaterialButtons.tsx
- src/components/material/material-buttons/helper.ts
[DDFSOEG-264](https://reload.atlassian.net/browse/DDFSOEG-264)
In case none of the material manifestations have online access, we shouldn't show the "online reservation" button on the material page. 
n/a
n/a
> Don't show "online material reserve button" if no manifestation have online access

- src/components/reservation/ReservationFormListItem.tsx
- src/components/reservation/ReservationModalBody.tsx
- src/components/reservation/helper.ts
https://reload.atlassian.net/browse/DDFSOEG-265
This PR fixes 3 things in the reservation modal:
- removes the "change" button from the "editions beam" as according to the project specs
- shows the correct edition in the "editions beam" for periodicals
- if the given material doesn't have any creators specified, instead of showing "By missing creators", we now don't show the line at all
No creators shown if there are no creators:
n/a
> Fix/remove "change" from editions & show correct periodical edition - in reservation modal

- .github/workflows/pull_request.yml
This updates the runtime from Node 12 to Node 16. Node 12 is being deprecated by GitHub and actions using it cause warnings.
See https://github.com/xt0rted/markdownlint-problem-matcher/issues/527
> Use Markdownlint problem matcher v2

- cypress/fixtures/material/fbi-api.json
- cypress/fixtures/material/infomedia-fbi-api.json
- cypress/fixtures/material/periodical-fbi-api.json
- cypress/fixtures/search-result/facet-browser/searchWithPagination.json
- cypress/fixtures/search-result/facet-browser/searchWithPagination_terms_joanne-k-rowling.json
- cypress/fixtures/search-result/fbi-api.json
- src/apps/search-result/facet-browser.test.ts
- src/components/find-on-shelf/FindOnShelfManifestationList.tsx
- src/components/find-on-shelf/FindOnShelfManifestationListItem.tsx
- src/components/find-on-shelf/mocked-data.ts
- src/components/reservation/helper.ts
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.schema.json
- src/core/dbc-gateway/generated/graphql.tsx
- src/core/utils/helpers/general.ts
it has moved from being a child of manifestation to being in manifestation.edition.publicationYear. this means that I have had to correct the search query, fixtures, and rewrites in all components that touch publicationYear.
It is especially this commit where I made logical corrections that you should pay attention to
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/221/commits/30062e7d7b1ff3f07c4a72c585470e1bfb11540f
> Fix publication year

- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/components/material/material-buttons/online/MaterialButtonOnlineExternal.tsx
- src/components/material/material-buttons/online/MaterialButtonsOnline.tsx
https://reload.atlassian.net/browse/DDFSOEG-301
This PR fixes an issue with the material page action. button. For online materials it should be showing:
- go to filmstriben (when the source is filmstriben)
- go to ereolen (when the source is ereol)
- listen online (when the material type is lydbog (net))
- see online (for the rest)
n/a
> Fix the "view online" button

- cypress/fixtures/material/periodical-fbi-api.json
- src/apps/material/material.test.ts
- src/components/find-on-shelf/FindOnShelfModal.tsx
- src/components/find-on-shelf/mocked-data.ts
- src/components/material/MaterialHeader.tsx
> Change name from periodikum to tidsskrift (new)

- src/components/facet-browser/FacetBrowserModal.tsx
- src/components/facet-browser/FacetBrowserModalBody.tsx
- src/components/facet-browser/helper.ts
- src/components/search-bar/search-result-header/SearchResultHeader.tsx
it is now possible to press the showResults button to close the modal instead of the cross in the corner.
> Add close logic to facet browser showResults button

- src/core/utils/text.tsx
Zero values was not being considered in the first version. This fixes the bug.
Additionally a feature to skip @count placeholder in plural mode has been added.
> Add support for zero count in plural texts

- codecov.yml
We have decided to drop `release/*` branches for continual development and move this to a permanent `develop` branch.
The admin UI is configured to use `release/4` and is filled with many other branches. For some reason develop does not show up. Lets hope defining it in code will work. It is preferable to have it in code anyways.
https://user-images.githubusercontent.com/73966/202441159-8735c0d7-48eb-4ec5-add6-61d2e9abe6ba.mp4
The failing test is unrelated to the change at hand.
> Set develop as the default branch for Codecov code coverage reporting

- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
goToEReolenText is depricated since the introduction of the @source placeholder in the goToText. We no longer use it in any of the apps.
> Remove goToEReolenText as a material app prop.

- cypress/fixtures/search-result/campaign-image-only.json
- cypress/fixtures/search-result/campaign-text-only.json
- cypress/fixtures/search-result/campaign.json
- src/components/campaign/CampaignBody.tsx
- src/components/campaign/campaign.test.ts
/
This PR makes changes to the campaign cypress test in order to prevent it from failing. The problems stemmed from recent 
campaign component semantic changes for how it is displayed when it should be clickable. The test now reflects these changes.
n/a
> Fix campaign test

- src/components/material/periodical/MaterialPeriodical.tsx
An unnecessary check has been introduced by mistake
in the MaterialPeriodical was there a check for if selectedPeriodical has a value
but selectedPeriodical is null to start with and will not be set until later in the flow.
The check in MaterialPeriodical ensures that MaterialPeriodicalSelect will never be rendered. which we do not want. Therefore I have removed it.
This is also why material tests fail.
> Fix falling material test

- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
Please add a link to the issue being addressed by this change.
Because we use onKeyUp we also need to specify which key we are listening to. Therefore we check if e.key === "Enter" otherwise the tab button and all other buttons will also activate the function.
> Fix unwanted redirect to material page on tab

- package.json
- yarn.lock
This is because we have changed the .tag class to use border instead of outline
> Update design-system to use latest css

- src/components/find-on-shelf/FindOnShelfManifestationListItem.tsx
I have used a template literals to create a string with a space in front of the publication year and changed the rendering logic to not render an empty string if there is no publication year
> Add space between title and publication year (FindOnShelf)

- cypress/fixtures/search-result/fbi-api.json
- src/apps/search-result/search-result.test.ts
- src/components/material/MaterialMainfestationItem.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.schema.json
- src/core/dbc-gateway/generated/graphql.tsx
- src/core/utils/helpers/general.ts
DDFSOEG-338
This PR fixes a mistake, where a helper function for retrieving a manifestation's first edition publish year was instead retrieving the publish year for the latest edition. We got it reported as a bug from Tue based on the cards on the search result page showing the latest edition publication year. The helper function isn't used in the end, as just as Tue suggests in the bug report we can use the already existing data prop called workYear - which shows the year of the first publication of a given work. 
I also found out that on the material page under editions - the edition cards show empty brackets for publication year if the data doesn't exist, so I fixed that too. 
Please don't look through the autogenerated files. ("/generated" folder)
> Manifestation edition publication year fixes

- cypress/fixtures/material/order-digital-copy/order-digital-fbi-api.json
- src/apps/material/infomedia.test.ts
- src/apps/material/material.test.ts
- src/apps/material/order-digital-copy.test.ts
- src/apps/material/periodical.test.ts
- src/components/material/digital-modal/DigitalModalBody.tsx
- src/components/material/digital-modal/DigitalModalFeedback.tsx
- src/components/material/material-buttons/MaterialButtons.tsx
- src/components/reservation/forms/ReservationForm.tsx
There is now a test that checks the following things
- render a material that can be ordered as a digital copy
- render modal to order digital copy
- order digital copy with fail
- order digital copy with succes
in addition, I have split up the material test so that Periodical + Infomedia has its own test files
> Add test for order digital copy + Move infomedia & periodical into its own separate files

- .eslintrc
- src/apps/material/material.tsx
> Fix bug: Change <main> to <section>

- src/components/Disclosures/DisclosureControllable.tsx
DDFSOEG-347
This PR fixes a Pa11y accessibility error where our disclosure component aria attributes were not located on the same HTML element. 
n/a
n/a
> Fix aria attributes for the disclosure element

- src/components/material/ReviewInfomedia.tsx
- src/components/material/material-buttons/online/MaterialButtonOnlineDigitalArticle.tsx
- src/components/material/material-buttons/online/MaterialButtonOnlineInfomediaArticle.tsx
- src/core/guardedRequests.slice.ts
- src/core/utils/helpers/url.ts
- src/core/utils/modal.tsx
https://reload.atlassian.net/browse/DDFSOEG-302
This PR introduces a helper function that is used when clicking on the reserve button for digital articles and infomedia articles. This function checks for whether a user is logged in and then either opens the given modal if so, or otherwise redirects the user to the login page with the possibility to come back to where the user left off & the modal open.
n/a
n/a
> Order digital article copy - login redirect

- src/core/utils/modal.tsx
DDFSOEG-352
We are getting an error from the accessibility test in the dpl-cms telling us that an element that has a role of a dialog needs to have a label in order for it to be accessible. 
n/a
n/a
> Fix reservation modal accessibility

- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/components/find-on-shelf/FindOnShelfModal.tsx
- src/components/material/MaterialHeader.tsx
- src/components/material/MaterialHeaderText.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
The situation is due to the fact that we have transitioned from a situation where dummydata always contained authors/origin to a situation where this is no longer the case.
> Creators are missing" should not appear when there is no value (Remove creatorsAreMissingText)

- src/apps/material/material.tsx
Changes made:
- InfomediaModal is now always rendered as long as infomediaId is truthy.
- DigitalModal is now only rendered if the result of hasCorrectAccess("DigitalArticleService") is true 
**Previously, the rendering of DigitalModal was dependent on infomediaId, which was not necessary.**
This commit also removes the unnecessary check for currentManifestation and refactors the code to correctly render the InfomediaModal and DigitalModal components based on their respective prop values.
> Update rendering of InfomediaModal and DigitalModal components

- src/apps/material/helper.ts
- src/apps/material/material.tsx
- src/components/availability-label/availability-labels.tsx
- src/components/reservation/ReservationModalBody.tsx
- src/core/utils/helpers/general.ts
This pull request moves the getManifestationType function from material/helper.ts to core/utils/helpers/general.ts. The purpose of this change is to ensure that the three apps can work independently of each other.
I have updated all relevant imports and references to the function to reflect its new location. 
I believe this change will improve the modularity and maintainability of the codebase.
> Move getManifestationType for app independence

- src/apps/loan-list/materials/stackable-material/material-info.tsx
- src/apps/loan-list/materials/stackable-material/material-status.tsx
- src/apps/loan-list/materials/utils/status-circle.tsx
- src/apps/reservation-list/reservation-material/reservation-info.tsx
- src/apps/reservation-list/reservation-material/reservation-status.tsx
https://platform.dandigbib.org/issues/5555
Set color explicitly, due to ios default colors
Removed some aria hiddens that are not supposed to be there 
Before: 
> 5555: add color-secondary-gray to elements

- src/apps/search-result/facet-browser.test.ts
- src/apps/search-result/search-result.test.ts
Since the campaign endpoint was introduced in search results
we need to have the requests intercepted in all tests that shows search results
> Add missing campaign interception in Cypress tests

- cypress/fixtures/material/fbi-api.json
- cypress/fixtures/material/infomedia-fbi-api.json
- cypress/fixtures/material/order-digital-copy/order-digital-fbi-api.json
- cypress/fixtures/material/periodical-fbi-api.json
- cypress/fixtures/search-result/fbi-api.json
- src/apps/material/helper.ts
- src/apps/material/material.test.ts
- src/apps/search-result/search-result.test.ts
- src/components/material/material-buttons/online/MaterialButtonsOnline.tsx
- src/components/search-bar/search-result-header/SearchResultHeader.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.schema.json
- src/core/dbc-gateway/generated/graphql.tsx
https://reload.atlassian.net/browse/DSC-16
DBC has updated the schema at [fbi-api.dbc.dk/](https://fbi-api.dbc.dk/) for [JED 0.8](https://danbib.dk/broend3_formater). The update contains some breaking changes which forces us to update our client and code accordingly. Key changes for us are related to `workYear`.
The primary purpose of this PR is to update the generated code and updates our code and Cypress fixtures accordingly.
The PR also contains two other changes:
1. We now see empty `access` properties. The code has been updated to handle this case.
2. The search result test has been updated to use `cy` data attributes.
> Update FBI API with latest schema changes for JED 0.8

- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/utils/helpers/lazy-load.ts
https://reload.atlassian.net/browse/DDFSOEG-356
By using the Intersection Observer API
we can distinguish between search result items that the intersecting with the viewport
and thereby change the behaviour depending on the visibility.
> Introduce lazy loading of search results

- src/core/mount.js
https://reload.atlassian.net/browse/DDFSOEG-356
We noticed in the Chrome performance tab that the mounting of the different apps are being run in the same task which exceeds the 50ms limit. This breaks up the app mounts in chunks.
> Settimeout on app mount

- package.json
- src/apps/search-result/search-result.tsx
- src/components/search-bar/search-result-header/SearchResultHeader.tsx
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-371
Remove hitcount from search header when loading and add "text-loading" class for animation.
Depends on:
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/180
There is a loan list test in Cypress that is failing. But as far as I can see it has nothing to do with this PR.
> Remove hitcount from search header when loading

- src/components/reservation/ReservationModalBody.tsx
- src/core/utils/modal.tsx
https://reload.atlassian.net/browse/DDFSOEG-372
This PR fixes a Pa11y accessibility issue for the reservation modal - not all the IDs are unique. Turns out there were two modal components rendered for every single reservation modal - so when the modal opens there would be a modal inside a modal.
Please only review the last 3 commits (with my face on them)
Disregard FBI API changes ( #302 )
> Fix accessibility for reservation modal

- src/apps/material/material.dev.tsx
- src/components/material/MaterialAvailabilityText/physical/MaterialAvailabilityTextPhysical.tsx
- src/components/material/StockAndReservationInfo.tsx
- src/components/reservation/ReservationModalBody.tsx
- src/components/reservation/ReservationSucces.tsx
The StockAndReservationInfo component was added to the ReservationSucces to display more information about the stockCount and reservationCount of a reservation. This information may be useful for the user to know, as it can help them understand the availability and popularity of the item they are interested in.
> Add StockAndReservationInfo to ReservationSucces

- src/apps/material/material.tsx
https://reload.atlassian.net/browse/DSC-25
The manifestations are now sorted by the specific material type, resulting in a more organized and intuitive display for users. This change should improve the user experience when viewing the editions of a work
> Sorted the editions by the specific material type

- package.json
- src/components/cover/cover.tsx
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-389
There was an issue with one of the values for the coverTints css class, which was set to 100. However, there is no css class that fits a tint value of 100. I assume that it should be 60 instead. because it was missing.
> Change incorrect value for coverTints

- src/components/availability-label/availability-labels.tsx
- src/components/material/MaterialHeader.tsx
- src/components/material/material-buttons/physical/MaterialButtonsFindOnShelf.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
https://reload.atlassian.net/browse/DDFSOEG-359
The find on shelf button should always be enabled for physical materials such as books, CDs, etc., even though they are unavailable. 
Please disregard the failing "loan-list" test. Sine is working on fixing it.
> Enable "find on shelf" button if no material specimens available

- src/components/autosuggest-category/autosuggest-category.tsx
- src/components/autosuggest-material/autosuggest-material.tsx
- src/components/autosuggest-text/autosuggest-text-item.tsx
- src/components/autosuggest/autosuggest.tsx
- src/components/search-bar/search-bar.tsx
[DDFSOEG-307](https://reload.atlassian.net/browse/DDFSOEG-307)
This PR adds data-cy property for cypress testing to search header components so that they can be easily targeted in our cypress tests moving forward. (Prompted by [this PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/216) )
n/a
-
> Add data-cy property for cypress testing to search header components

- src/apps/loan-list/list/loan-list.dev.tsx
- src/apps/loan-list/materials/selectable-material/selectable-material.tsx
- src/components/checkbox/Checkbox.tsx
na
Include titel of material in aria label
:)
> add material label to aria string

- src/apps/material/material.dev.tsx
- src/components/material/StockAndReservationInfo.tsx
- src/components/reservation/ReservationModalBody.tsx
- Removal of an unnecessary plural translation in the PromoBar inside ReservationModalBody.
- Addition of space in the StockAndReservationInfo component. The space has been added to the code instead of being written in the CMS for better maintainability.
> Fix text mistakes

- src/apps/material/helper.ts
- src/apps/material/material.tsx
https://reload.atlassian.net/browse/DSC-31
- Added a new function getManifestationsOrderByTypeAndYear that takes an array of Manifestation objects as an argument.
- Used two helper functions, orderManifestationsByYear and groupBy, to sort the array of Manifestation objects.
- Returned a new array with the sorted Manifestation objects.
> Editions grouped by type and then by age

- src/apps/material/helper.ts
- src/apps/material/material.test.ts
- src/components/material/MaterialDescription.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFSOEG-395
'getNumberedSeries' takes in an array of objects (series) and returns a sorted version of the array based on the 'numberInSeries' property. It first filters out any objects that do not have a 'numberInSeries' property, and then sorts the remaining objects based on the numerical value of their 'numberInSeries' property.
**After**:
**Before**:
> use 'getNumberedSeries' to render series on manifestation and search results 

- src/apps/loan-list/list/loan-list.dev.tsx
- src/apps/loan-list/list/loan-list.entry.tsx
- src/apps/loan-list/modal/material-details.tsx
- src/apps/loan-list/modal/renew-button.tsx
- src/apps/reservation-list/modal/delete-reservation/delete-reservation.test.ts
- src/apps/reservation-list/modal/delete-reservation/pause-reservations.test.ts
- src/apps/reservation-list/modal/reservation-details/physical-list-details.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details-buttons.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details-redirect.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
- src/apps/reservation-list/modal/reservation-details/reservation-details.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/list-details-dropdown/list-details-dropdown.tsx
- src/components/list-details/list-details.tsx
https://platform.dandigbib.org/issues/5654
Use returned object from save to update values
fix mobile styling (link)
add missing link to ereolen
> 5654: update styling and save on material details

- src/components/material/material-buttons/material-buttons.test.ts
It isn't rendered before it enters the viewport.
> Scroll down before checking user blocked button in material buttons test

- package.json
- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/apps/material/material.test.ts
- src/components/Disclosures/DisclosureControllable.tsx
- src/components/horizontal-term-line/HorizontalTermLine.tsx
- yarn.lock
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/199
https://reload.atlassian.net/browse/DSC-37
- Limits the number of terms displayed to the value set in numberOfItemsToShow, which is set to 2.
- a toggle button has been added, allowing users to switch between displaying only the limited number of terms and all of them. The button features a toggle icon that changes according to the component's state.
**Other Changes**
- Add css modifier in DisclosureControllable to flip arrow icon
> Add expand icon to horizontal term line

- src/core/utils/helpers/url.ts
https://reload.atlassian.net/browse/DDFSOEG-474
The code changes include:
- Creating a new URL object materialUrl using the original URL object.
These changes ensure that the constructMaterialUrl function behaves as intended and avoids unintended side effects.
> Refactor `constructMaterialUrl` to use 'new URL' object

- src/apps/search-result/helper.ts
- src/components/facet-browser/helper.ts
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
https://reload.atlassian.net/browse/DDFSOEG-463
its retrieves the first materialType from filters that are included in manifestations. it is then used to construct the materialFullUrl in the `SearchResultListItem`
https://user-images.githubusercontent.com/49920322/223070074-346bc298-6bc1-4465-a6f9-53c92eb3aa0f.mov
> Add selected materialType to `constructMaterialUrl`

- src/apps/search-result/search-result.test.ts
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFSOEG-404
This PR fixes an issue with not choosing the correct release year to render on the search result page. 
n/a
n/a
> Fix release year on search result page

- src/apps/loan-list/list/list.tsx
- src/apps/loan-list/modal/renew-loans-modal-content.tsx
- src/apps/reservation-list/list/list.tsx
- src/apps/search-header/search-header.dev.tsx
- src/apps/search-result/search-result.dev.tsx
- src/apps/search-result/search-result.entry.tsx
- src/apps/search-result/search-result.tsx
- src/components/autosuggest/autosuggest.tsx
- src/components/result-pager/result-pager.tsx
- src/components/result-pager/use-pager.tsx
https://reload.atlassian.net/browse/DDFSOEG-459
The isLoading property is used to show a loading indicator while the search results are loading.
**Changes Made:**
- Refactored usePager to accept PagerProps object.
- Added isLoading property in PagerProps.
- Updated search-result, result-pager, and autosuggest components to use the new PagerProps.
https://user-images.githubusercontent.com/49920322/223100785-3a3d2e4c-e2e5-45f2-9210-1101f388b454.mov
It also updates the search-result, result-pager, and autosuggest components to use the new PagerProps object in usePager.
> Refactor `usePager` to accept  'isLoading'

- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/components/reservation/ReservationFormListItem.tsx
- src/components/reservation/UserListItems.tsx
https://reload.atlassian.net/browse/DDFSOEG-434
As screen readers need to know what the change buttons do in the reservation model, this change will improve accessibility and user experience for those who rely on assistive technologies.
> Add `aria-label` to `ReservationFormListItem`

- src/core/modal.slice.ts
- src/core/mount.js
https://reload.atlassian.net/browse/DDFSOEG-453
When the user presses the escape key the `closeLastModal` action is dispatched, and it closes the last opened modal.
By implementing this feature, we ensure that the application is more user-friendly, and users can easily close modals without having to use tap key to search for a close button. Furthermore, this addition helps maintain consistency in user interactions across different applications, as the escape key is widely used for closing modals.
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/388
> Add Global Escape Key Handler for Closing Modals

- src/components/reservation/ReservationError.tsx
- src/components/reservation/ReservationSucces.tsx
https://reload.atlassian.net/browse/DDFSOEG-447
FocusTrap helps to trap the focus within the modal when it is open, preventing users from accidentally interacting with elements outside of the modal.
> Add 'FocusTrap'  in `ReservationSucces`

- src/apps/material/material.tsx
- src/components/description-list/description-list.tsx
- src/components/material/MaterialDetailsList.tsx
- src/components/material/MaterialMainfestationItem.tsx
https://reload.atlassian.net/browse/DDFSOEG-426
The aria-expanded attribute has been added to the MaterialDetailsList component to improve accessibility for users with disabilities. This attribute indicates the current state of the element, whether it is expanded or collapsed, and provides information to assistive technologies like screen readers.
> Add 'aria-expanded' to `MaterialDetailsList`

- src/components/Disclosures/DisclosureControllable.tsx
[DDFSOEG-472](https://reload.atlassian.net/browse/DDFSOEG-472)
The changes address focus issues in `DisclosureControllable` and provide a better user experience.
The changes include:
- Separating the `onClick` and `onKeyDown` event handlers into two separate functions, `handleClick` and `handleKeyDown`. This improves readability and maintains the separation of concerns between different types of events.
- Updating the `toggleOpen` useCallback to use a functional state update for `setIsOpen` instead of relying on the `isOpen` value from the closure. This avoids potential issues with stale state values and makes the callback more efficient.
https://user-images.githubusercontent.com/49920322/232033931-4956ae6b-5457-462b-a18f-8a8f75d8e78a.mov …
> Refactor `DisclosureControllable` toggle & key handling

- src/apps/material/helper.ts
- src/apps/material/material.dev.tsx
- src/components/autosuggest-material/autosuggest-material.tsx
- src/components/autosuggest-text/autosuggest-text-item.tsx
- src/components/autosuggest/autosuggest.graphql
- src/components/find-on-shelf/mocked-data.ts
- src/components/material/MaterialHeader.tsx
- src/components/material/MaterialHeaderText.tsx
- src/components/material/MaterialMainfestationItem.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.schema.json
- src/core/dbc-gateway/generated/graphql.tsx
https://reload.atlassian.net/browse/DDFSOEG-436
A new function called `getManifestationLanguageIsoCode` has been implemented to accomplish this.
The `getManifestationLanguageIsoCode` function takes an array of LanguagesFragment objects and returns the ISO code of the main language. If multiple unique main languages are present, it defaults to the language defined in the document's HTML tag.
In addition, 'LanguagesFragment' fragments have been added to enhance code generation (Types)
> Add 'lang' attribute to titles if they are not Danish

- package.json
- src/components/Buttons/LinkButton.tsx
- src/components/atoms/links/Link.tsx
- src/components/atoms/links/LinkNoStyle.tsx
- src/components/cover/cover-image.tsx
- src/components/cover/cover.tsx
- src/components/material/MaterialHeader.tsx
- src/components/material/MaterialHeaderText.tsx
- src/components/material/MaterialMainfestationItem.tsx
- src/components/material/material-buttons/MaterialButtons.tsx
- src/components/material/material-buttons/online/MaterialButtonOnlineExternal.tsx
- src/components/material/material-buttons/online/MaterialButtonsOnline.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item-cover.tsx
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/mount.js
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-421
https://reload.atlassian.net/browse/DDFSOEG-427
When the 'coverSrc' property in the `Cover` component is invalid, the image won't be displayed, leading to an empty link. To address this, we use the 'aria-labelledby' attribute to associate the empty link with the title of the search result item. 
We generate a unique identifier for the title using the useId() hook, which is assigned to the id attribute of the title and used as the aria-labelledby value for the Link
Additionally, the description prop in the Cover component is renamed to altText.
This improves the overall experience for users who rely on screen readers.
> Add 'aria-labelledby' to `Link` + Change name 'description' to 'altText'

- src/apps/search-result/search-result.tsx
- src/components/search-result-list/SearchResultList.tsx
https://reload.atlassian.net/browse/DDFSOEG-420
These changes ensure that the focus moves as expected when navigating through the list using the keyboard to move to the next pages.
The following changes have been made:
- Add 'page' and 'pageSize' props to the `SearchResultListProps` interface.
- Add a useEffect hook to focus on the first item of the new page when the page number changes.
- add a ref attribute to the first li element in the SearchResultList component.
https://user-images.githubusercontent.com/49920322/231752771-0cf16655-666a-460a-a45d-8535d91fd2d1.mov
> Improve keyboard navigation in `SearchResultList`

- src/components/find-on-shelf/FindOnShelfModal.tsx
- src/components/material/MaterialHeader.tsx
- src/components/material/MaterialMainfestationItem.tsx
- src/components/reservation/helper.ts
- src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
- src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFSOEG-503
This Pull Request refactors the way we retrieve authors/creators from works and manifestations.
Previously, we looked at whether the type of Creators was a `person` or `Corporation`, but we also want to display the author if the material is, for example, a CD, such as `work-of:870970-basis:23157381`.
Therefore, I have removed the usage of filterCreators and deleted the function.
> Remove unnecessary use of `filterCreators`

- src/components/reservation/ReservationError.tsx
- src/components/reservation/ReservationSucces.tsx
https://reload.atlassian.net/browse/DDFSOEG-506
The default behavior is to not allow clicking outside the `FocusTrap`. However, we still want to be able to close the modal with the mouse, so we set allowOutsideClick to `true`.
> Add `allowOutsideClick` to `FocusTrap` in ReservationSucces/ Error modal

- src/components/material/ReviewExternal.tsx
- src/components/material/ReviewInfomedia.tsx
- src/components/material/ReviewLibrarian.tsx
- src/components/material/ReviewMetadata.tsx
- src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFSOEG-500
- Implement a `getPublicationName` function that retrieves the 'hostPublication' and returns the host title.
- Add the 'publication' obtained from `getPublicationName` to `ReviewMetadata`.
- Update the existing `metaDataText` handling logic to include the 'publication', ensuring correct display and formatting of the author line in Reviews.
> Add 'hostPublication' to  `ReviewMetadata` + Refactor `metaDataText`

- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/components/material/MaterialDescription.tsx
https://reload.atlassian.net/browse/DDFSOEG-485
This PR introduces the `HorizontalTermLine` component for `dk5MainEntry` ("emnetal")  specifically for nonFiction Works
> Add `HorizontalTermLine` for `dk5MainEntry` ("emnetal") to nonFiction Works

- package.json
- src/components/button-expand/ButtonExpand.tsx
- src/components/horizontal-term-line/HorizontalTermLine.tsx
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-488
**This should reflect the changes in:**
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/213
Changes made:
- Extracted ButtonExpand into a separate component for improved reusability and maintenance
- Updated "dpl-design-system" to align with the latest design, ensuring baseline alignment for HorizontalTermLine
> Extract `ButtonExpand` component + Update "dpl-design-system"

- cypress/fixtures/material/user.json
- src/apps/material/material.tsx
- src/apps/menu/menu.tsx
- src/components/guarded-app.tsx
- src/components/material/material-buttons/physical/MaterialButtonsPhysical.tsx
- src/core/guardedRequests.slice.ts
- src/core/utils/helpers/user.ts
- src/core/utils/modal.tsx
- src/core/utils/types/entities.ts
https://reload.atlassian.net/browse/DDFSOEG-492
Previously, when a user who was not logged in clicked on the Reserve button, they were sent to the login platform and then redirected back to the page with a URL containing `&modal=reservation-modal-********`. This opened the modal, even if the user was blocked.
To resolve this issue, I have implemented the following changes:
- Added a check for `isUserAllowed` before rendering the `ReservationModal` and `FindOnShelfModal`.
- Introduced `userIsBlocked` and `userIsAllowed` variables to improve code readability and maintainability.
These changes ensure that the `ReservationModal` is not opened for blocked users.
**Blocked user:**
https://user-images.githubusercontent.com/49920322/233066134-ef5c558a-c76b-4f44-9f86-78c10b6730b6.mov
**user:** …
>   Don't open ReservationModal modal if the user is blocked.

- package.json
- src/components/autosuggest-material/autosuggest-material.tsx
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-520
This PR uses the newest dpl-design-system package to solve a bug described in [this PR](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/218), where autosuggest dividers were not spanning the full width of the element. 
n/a
> Use newest atosuggest-material classes for singular & two items

- src/apps/material/helper.ts
https://reload.atlassian.net/browse/DDFSOEG-496
This PR fixes the issue of missing the first edition year, which was caused by using 'workYear' on the selected / 'bestRepresentation' manifestation level where it was only provided on some of the manifestations. 
The following changes have been made to address this issue:
- Refactor `getManifestationFirstEditionYear` to `getWorkFirstEditionYear` as we should now use 'workYear' on the work level, rather than the manifestation level.
- Update the details list to display the first edition year using `getWorkFirstEditionYear`
> Use 'workYear' from 'work' instead of manifestation in `MaterialDetailsList`

- src/apps/search-header/search-header.tsx
- src/components/search-bar/search-bar.tsx
https://reload.atlassian.net/browse/DDFSOEG-483
This pull request aims to address the challenges with cursor placement in Downshift, using an approach inspired by a discussion on GitHub. The changes implemented in this PR help to improve the user experience by providing more accurate and intuitive cursor placement behavior during input interactions.
https://github.com/downshift-js/downshift/issues/1108#issuecomment-674180157
https://user-images.githubusercontent.com/49920322/236181667-b08b2689-e79c-41b2-9020-f7456c62396b.mov
> Fix jumping cursor problem in `SearchBar`

- package.json
- src/components/material/MaterialSkeleton.tsx
- yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-522
This PR is changing the `MaterialPageSkeleton` to reflect the new cover size on mobile.
https://user-images.githubusercontent.com/49920322/235878249-09dd7418-979b-416c-a279-5f10783e3d5f.mov
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/219
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/312
> Fix material skeleton

- src/apps/intermediate-list/fee-list/fee-list.tsx
- src/apps/intermediate-list/stackable-fees/total-payment-pay.tsx
https://platform.dandigbib.org/issues/5774
Remove checkbox that is not specced from the intermediate/fee-list
> remove not-specced checkbox in fee list

- src/apps/material/helper.ts
- src/apps/material/material.dev.tsx
- src/components/availability-label/availability-label.tsx
- src/components/availability-label/helper.ts
- src/components/find-on-shelf/FindOnShelfModal.tsx
- src/components/material/MaterialAvailabilityText/physical/MaterialAvailabilityTextPhysical.tsx
- src/components/material/periodical/MaterialPeriodical.tsx
- src/components/reservation/ReservationError.tsx
- src/components/reservation/ReservationModalBody.tsx
- src/components/reservation/useAlternativeAvailableManifestation.ts
- src/core/utils/UseReservableManifestations.tsx
- src/core/utils/useGetAvailability.ts
https://reload.atlassian.net/browse/DDFSOEG-499
This pull request aims to fix issues related to parallel reservations by addressing two specific problems with the `work-of:870970-basis:46143736`. Firstly, the branch `DK-775164` (Egå skolebibliotek) needs to be blacklisted, and secondly, we need to include the blacklist in the `UseReservableManifestations`.
To address these issues, this pull request introduces new hooks - `useGetAvailability`, `getAvailability`, and `useGetAvailability` - which serve as a wrapper around existing hooks. These new hooks handle cases where 'blacklistedConfig' needs to be considered while fetching data. By using the `getBlacklistedArgs` function, the wrapper ensures that blacklisted branches are appropriately excluded from the query results.
While working on …
> Fixing parallel reservation issues with blacklisting 

- src/components/Disclosures/DisclosureControllable.tsx
- src/components/Disclosures/DisclosureSummary.tsx
- src/components/Disclosures/disclosure.tsx
https://reload.atlassian.net/browse/DDFSOEG-521
This pull request improves the `Disclosure` component's className handling by replacing template strings with the `clsx` library. The previous approach resulted in undefined class names when no class was passed, leading to potential issues and inconsistencies.
> Switch to use `clsx` instead of template strings in `Disclosure`

- src/apps/search-header/search-header.dev.tsx
- src/apps/search-header/search-header.entry.tsx
- src/components/search-bar/search-bar.tsx
https://reload.atlassian.net/browse/DDFSOEG-461
This pull request implements a change that prevents users from executing an empty search when pressing the 'Enter' key in the search input field or the search icon is clicked. The update ensures that a search is only triggered when there is a meaningful input value, not just whitespace characters.
https://user-images.githubusercontent.com/49920322/234840414-3fb42b6a-e8be-4d26-8793-faa524f477cd.mov
> Prevent empty search on 'Enter' press in search input

- .eslintignore
- orval.config.ts
- src/apps/favorites-list/favorites-list.test.ts
- src/components/availability-label/AvailabilitySkeleton.tsx
- src/components/availability-label/availability-label-inside.tsx
- src/components/availability-label/availability-label-visual.tsx
- src/components/availability-label/availability-label.tsx
- src/components/availability-label/availability-labels.tsx
- src/components/availability-label/helper.ts
- src/components/availability-label/types.ts
- src/components/material/MaterialMainfestationItem.tsx
- src/core/publizon/publizon-adapter.yaml
- src/core/publizon/publizon.ts
https://reload.atlassian.net/browse/DDFSOEG-517
This PR fixes availability exposing for e-resources, and introduces loading state to availability labels. 
The e-resource availability is a bit tricky - they are per default always available, unless they can be accessed from Ereolen and they are not blue titles (unlimited loans) and there is a queue on them.
n/a
> Fix e-resource availability

- src/apps/material/login-redirect.test.ts
https://reload.atlassian.net/browse/DDFSOEG-526
This PR reimplements the `login-redirect.test` that was missing after changes in the Modal component.
The way we can test if an unauthorized user is redirected to the login platform is by checking if a current-path URL parameter has been added.
> Refactor `login-redirect.test`

- src/components/card-item-list/card-list-item/card-list-item.tsx
https://reload.atlassian.net/browse/DDFSOEG-484
This PR introduces a fix for the issue where the back button wasn't working correctly after clicking the title link in the `CardListItem` component.
Changes:
- Added `e.stopPropagation()` to the onClick handler of the title link in the `CardListItem` component.
This change ensures that only the specific onClick event for the title link is triggered, which effectively prevents unintended event propagation. As a result, the back button now functions correctly after using the title link.
> Fix back button issue by adding `e.stopPropagation()` to `CardListItem`

- src/apps/search-header/search-header.tsx
- src/apps/search-result/search-result.tsx
- src/apps/search-result/useFilterHandler.tsx
- src/components/autosuggest-category/autosuggest-category.tsx
- src/components/autosuggest/autosuggest.tsx
- src/core/utils/types/material-type.ts
https://reload.atlassian.net/browse/DDFSOEG-326
This pull request introduces the possibility to filter on `workTypes` in `AutosuggestCategory`, which was previously limited to only `materialTypes`. 
This change will provide users with a more flexible and powerful way to search and filter results.
It also resolves the absent mouse functionality in `handleHighlightedIndexChange`, enabling users to use their mouse for navigating to the search page with filters within the `AutosuggestCategory`.
> Add possibility to filter on `workTypes` in `AutosuggestCategory`

- src/apps/patron-page/sections/StatusSection.tsx
https://platform.dandigbib.org/issues/5690
- accessibility: labels instead of divs
Looks the same
n/a
> Itkdev: 5690: semantic labels for text

- src/apps/dashboard/modal/ReservationsGroupModal.tsx
- src/components/GroupModal/GroupModalLoansList.tsx
- src/components/GroupModal/GroupModalReservationsList.tsx
- src/components/GroupModal/LoansGroupModal.tsx
- src/components/result-pager/result-pager.tsx
- src/components/result-pager/use-pager.tsx
https://platform.dandigbib.org/issues/5389
In some situations the pager and the fixed button in the bottom of the modals had a bit of an unfortunate overlap
friends with: https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/239
n/a
> 5389: make room for fixed buttons/pager

- docs/code_guidelines.md
- tsconfig.json
- vitest.config.ts
While creating tests for some link component functionality I ran into an issue with testing/mocking a function that originally was an unexported function. There are other questionable hacks you can do
that is not a part of the Vitest recommended practices. However does Vitest have the [in source testing concept](https://vitest.dev/guide/in-source.html#setup) that solves the issue. I suggest we make use of that.
> Add Vitest in source testing

- src/apps/patron-page/PatronPage.tsx
[Please add a link to the issue being addressed by this change.](https://platform.dandigbib.org/issues/5835)
A boolean, set by the saving method, deciding if the submit button should be disabled.
N/A
> 5835: Adding button disable while data is being saved

- src/apps/loan-list/utils/helpers.ts
- src/apps/reservation-list/modal/reservation-details/digital-list-details.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
[Please add a link to the issue being addressed by this change.](https://platform.dandigbib.org/issues/5892)
Reservation expiration time until now only shown as date. This PR introduces the time as well.
> 5892: Added a formatdatetime for displaying the time aswell

- src/apps/dashboard/dashboard.dev.tsx
- src/apps/dashboard/dashboard.test.tsx
[Please add a link to the issue being addressed by this change.](https://platform.dandigbib.org/issues/5863)
The counterpart DPL-CMS pull#375 (https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/375) removes some link inputs from the admin panel, and this PR hardcodes them.
> 5863: Hardcoding some paths + removed unused

- .eslintrc
- src/core/utils/helpers/general.ts
Got tired of ts warnings and thought [getParams](https://github.com/danskernesdigitalebibliotek/dpl-react/pull/511/files#diff-a09d47a1eb335411b7f4c67799d5a4d59bac0b55e8dcf3d3142c99f86d309378L169-L177) could get more lean.
Also wrote a test for it.
> Cleaning up getParams

- src/apps/material/__snapshots__/helper.ts.snap
- src/apps/material/__vitest_data__/helper.ts
- src/apps/material/helper.ts
- src/core/utils/helpers/general.ts
We need to have ITK to confirm that we only look at the first material type on each manifestation in order to decide which type it is. We should not merge before it is confirmed.
https://reload.atlassian.net/browse/DSC-43
Fix weird availability-label click behaviour
Solved by ignoring all other specific material types
on manifestations except the first one.
This behaviour has to be double checked with DDF.
> DONT MERGE BEFORE CONFIRMATION: Availability labels bug fix

- src/components/material/material-buttons/online/MaterialButtonOnlineExternal.tsx
- src/components/material/material-buttons/online/MaterialButtonsOnline.tsx
https://reload.atlassian.net/browse/DDFSOEG-490
Since it is not working on DBC's side the decision has been made to remove the check for that property
> Remove loginRequired check in MaterialButtonOnlineExternal

- cypress/support/index.ts
- graphql.config.json
- src/apps/dashboard/dashboard.test.tsx
- src/apps/favorites-list/favorites-list.test.ts
- src/apps/fee-list/fee-list.test.ts
- src/apps/loan-list/list/loan-list.test.ts
- src/apps/loan-list/modal/modals.test.tsx
- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/apps/material/material.test.ts
- src/apps/reservation-list/list/reservation-list-pagination.test.ts
- src/apps/reservation-list/list/reservation-list.test.ts
- src/apps/reservation-list/modal/delete-reservation/delete-reservation.test.ts
- src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
- src/apps/search-header/search-header.test.ts
- src/apps/search-result/search-result.test.ts
- src/components/availability-label/availability-label.tsx
- src/core/storybook/serviceUrlArgs.ts
https://reload.atlassian.net/browse/DDFDPDEL-216
The definition of the availability texts where defined halfways. This PR names them with a "availability" prefix that makes it clear what the purpose of the strings are. The [PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/381) in the dpl-cms repository will make sure that these strings are added as well.
> Make availability label texts translatable

- .github/workflows/release.yml
Dependabot does not have permissions to create releases. This causes the workflow to fail when running ghr with the following error:
Failed to create GitHub release page: failed to create a release: POST https://api.github.com/repos/danskernesdigitalebibliotek/dpl-react/releases: 403 Resource not accessible by integration []
According to GitHub having Dependabot run with read-only scopes is intentional and the recommended approach is to skip running such  workflows based on branch naming:
https://docs.github.com/en/code-security/code-scanning/troubleshooting-code-scanning/resource-not-accessible-by-integration
Before:
> Skip release workflow for Dependabot

- src/components/Dropdown/Dropdown.tsx
- src/components/facet-browser/__snapshots__/helper.ts.snap
- src/components/facet-browser/helper.ts
- src/components/facet-line/FacetLineFilters.tsx
https://reload.atlassian.net/browse/DDFSOEG-525
We identified that the intelligentFacets query can sometimes return facets with a term intended for shortcut buttons. This same facet might also be present with other terms. To handle this efficiently and enhance our search capabilities, we've made the following updates:
- Added `createFacetsMap` Function:
This function is aimed to transform the facets array into an object. The main objective behind this transformation is to enhance search capabilities within the facets.
- Refactored `handleDropdownOnchange` Logic:
Incorporated the use of `createFacetsMap` within this function.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/49920322/8ad57abf-0e00-4323-8f62-fd23a8323235
> Refactor `handleDropdownOnchange` in `FacetLineFilters`

- src/components/Disclosures/DisclosureSummary.tsx
- src/components/availability-label/availability-label-visual.tsx
- src/components/find-on-shelf/FindOnShelfModalBody.tsx
- src/components/find-on-shelf/find-on-shelf.test.ts
- src/components/pagefold/Pagefold.tsx
https://reload.atlassian.net/browse/DDFSOEG-553
Availability texts has changed keys. This PR corrects some keys that escaped the first refactoring.
> Correct old availability text keys

- src/apps/dashboard/dashboard.test.tsx
- src/apps/loan-list/list/loan-list-items.tsx
- src/apps/loan-list/list/loan-list.test.ts
- src/apps/loan-list/modal/renew-button.tsx
- src/components/GroupModal/LoansGroupModal.tsx
- src/components/GroupModal/LoansGroupModalButton.tsx
- src/components/message/modal-message/ModalMessage.tsx
- src/components/store.jsx
https://reload.atlassian.net/browse/DDFLSBP-167
* The loan list and dashboard cypress tests have been expanded to incude the renewal flow introduced in part I
* The cache stale time has been bumped from 30 sec to 2 minutes in order to see the effect of the react query cache system
The first part of the work ([part 1)](https://github.com/danskernesdigitalebibliotek/dpl-react/pull/572) should be reviewd first before this is reviewed.
> Samlesag feedback på fornyelser part II

- .github/workflows/tests.yml
- src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
Please add a link to the issue being addressed by this change.
Align local tests with the timezone used in GitHub Actions to ensure consistency.
> Change timezone for Cypress in GitHub Action

- .github/workflows/release.yml
n/a
We experienced some issues where GHR sometimes marks a GH release as a draft, and sometimes as pre-release without a clear reasoning. We hope that this update will fix this inconsistancy.
n/a
n/a
> Update/ghr in release.yml GH action

- src/apps/patron-page/PatronPage.tsx
- src/components/atoms/input/TextInput.tsx
https://reload.atlassian.net/browse/DDFLSBP-85
We utilize the role="alert" attribute on the messages. This way, if the user is using a screen reader, they will be notified about the feedback messages as they appear.
n/a
n/a
> Fix screen reader feedback when changing user password

- .github/workflows/release.yml
This reverts commit 20416d2a8e7d3deb93ad35e3fdc1d8327fbe8ea4.
This is because I encountered issues while creating tags/releases.
> Revert "Update Install GHR command in release.yml so it uses the newest version

- src/apps/create-patron-user-info/UserInfo.tsx
- src/components/contact-info-section/ContactInfoSection.tsx
https://reload.atlassian.net/browse/DDFLSBP-208
https://reload.atlassian.net/browse/DDFLSBP-110
There has been some confusion about mail and phone no., wether they should be required or not.
Apparently the rule is:
None of them are required, except mail on the user registration form.
> Mail should not be required in user info

- src/apps/create-patron-user-info/CreatePatron.dev.tsx
- src/apps/create-patron-user-info/UserInfo.tsx
- src/apps/menu/menu-logged-in/MenuLoggedInContent.tsx
- src/apps/menu/menu.dev.tsx
- src/apps/menu/menu.entry.tsx
https://reload.atlassian.net/browse/DDFLSBP-202
When a user clicks "Cancel" on the user registration form the user is logged out and redirected to the frontpage of the mounting application.
- Refactor menuLogOutUrl to logoutUrl
- Make the cancel button go to the logout path
> DDFLSBP 202 brugeroprettelse fortryd knappen virker ikke

- .github/dependabot.yml
We use many packages from Storybook, GraphQL Codegen and Babel. These are often updated in parallel and may have dependencies between them. Thus is makes sense to group these updates of these packages in Dependabot to ensure that we get an update to e.g. Storybook 7, GraphQL Codegen 5, Babel 8 in the same pull request
> Group dependabot updates for certain vendors

- src/apps/patron-page/PatronPage.dev.tsx
- src/apps/patron-page/PatronPage.entry.tsx
- src/apps/patron-page/PatronPage.tsx
- src/components/contact-info-section/ContactInfoPhone.tsx
- src/components/notification/NotificationComponent.tsx
- src/components/promo-bar/PromoBarIcon.tsx
- src/core/utils/useNotificationMessage.ts
- src/core/utils/useNotificationMessage.tsx
- src/tests/unit/notification-message.test.tsx
https://reload.atlassian.net/browse/DDFLSBP-84
This Pull Request adds the `PromoBar` component and a new custom hook `useNotificationMessage` to the `PatronPage`. 
The `PromoBar` provides visual notifications to users, while the `useNotificationMessage` hook is designed to manage these notifications by handling auto-scrolling and setting removal timeouts.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/49920322/a7fe635e-51c6-480e-b680-a1bd2121b735
> adds the `PromoBar` component and a new custom hook `useNotificationMessage` to the `PatronPage`

- src/apps/dashboard/dashboard-fees/dashboard-fees.tsx
- src/apps/dashboard/dashboard.dev.tsx
- src/apps/dashboard/dashboard.entry.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details.tsx
- src/components/reservation/ReservationModalBody.tsx
- src/components/reservation/helper.ts
- src/core/storybook/reservationMaterialDetailsArgs.ts
- src/tests/unit/config.test.tsx
- src/tests/unit/text.test.tsx
https://reload.atlassian.net/browse/DDFLSBP-246
This PR is created as a port of the work being done on this [PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/436) in dpl-cms.
Initiatives in this project:
* Changed allowRemoveReadyReservations to be boolean property. I think we should handle booleans as a part of a json structure config. In that way it is "natively boolean" and we do not have to juggle around with tranforming "1" and "0" or "true" and "false".
* Instant loan config. The place it is used there was no checks if the various config properties were set. I tried to accomodate the situation by let the handling functions accept null parameters where they were used. Not optional though would like to handle it earlier.
* In the work with the …
> Defaults in dpl-react configuration

- src/apps/create-patron-user-info/UserInfo.tsx
https://reload.atlassian.net/browse/DDFLSBP-226
Activate email notifications for new accounts
For initial communication, new users are given a welcome email with guidelines and related information. Borrowers have the flexibility to transition to text notifications through their user settings, contingent upon the library's service offerings.
> Activate email notifications for new accounts

- src/components/reservation/ReservationModalBody.tsx
- src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFSOEG-528
The previous implementation set an empty string for the `pickUpBranch` field in `openOrder` if `selectedBranch` was not provided. However, an empty string is still considered a valid value when sent to the API, which triggered a `UNKNOWN_USER` error due to the user not being found.
Additionally, the `getPatronAddress` function has been removed as it's no longer necessary to send the address. There was a concern regarding potential mismatches in address formatting, which could result in errors since `openOrder` requires exact matches for input values.
> Set the patron `preferredPickupBranch` instead of the empty string in `openOrder`

- src/apps/dashboard/modal/ReservationsGroupModal.tsx
https://reload.atlassian.net/browse/DDFLSBP-171
A user should no be able to trigger the delete materials modal, if no materials have been selected. This adds a simple check for that.
> Add disabled state for delete materials button

- src/apps/reservation-list/modal/delete-reservation/delete-reservation-modal.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
- src/core/modal.slice.ts
- src/core/utils/modal.tsx
- src/tests/unit/modal.test.tsx
https://reload.atlassian.net/browse/DDFLSBP-102
Upon deleting a reserved material, the user can be stuck in an infinite loop, because the underlying reservations modal is not closed after deleting a reservation. This change always closes the reservationsQueued modal when deleting a reserved material.
> Close reservations modal when deleting reservation

- src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx
- src/apps/dashboard/dashboard.tsx
- src/apps/dashboard/modal/ReservationsGroupModal.tsx
- src/apps/loan-list/list/loan-list.tsx
- src/apps/menu/menu-logged-in/MenuLoggedInContent.tsx
- src/core/utils/helpers/general.ts
- src/core/utils/useLoans.tsx
- src/core/utils/useReservations.tsx
https://reload.atlassian.net/browse/DDFLSBP-197
https://reload.atlassian.net/browse/DDFLSBP-198
https://reload.atlassian.net/browse/DDFLSBP-233
https://reload.atlassian.net/browse/DDFLSBP-157
This Pull Request addresses issues pertaining to the display of reservations and loans from both FBS and Publizon systems. It introduces two new hooks: `useReservations` and `useLoans` and the implement of them
These new hooks simplify interactions with both FBS and Publizon systems by consolidating reservations and loans from each provider, respectively. Additionally, they return other specific lists of loans and reservations as required for the UI.
The changes have been integrated in sections relevant to loans and reservations.
All changes have been consolidated into a single commit to mitigate …
> Introduce and implement `useReservations` and `useLoans` hooks

- src/apps/advanced-search/AdvancedSearchHeader.tsx
- src/apps/advanced-search/AdvancedSearchResults.tsx
https://reload.atlassian.net/browse/DSC-76
This PR introduces a scoll into view feature for the advanced search results upon clicking the search button.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/28546954/2abf4fab-43d2-4741-9646-f27bd0f50d7c
n/a
> Scroll advanced search results into view on click of "search" button

- src/apps/loan-list/materials/utils/material-fetch-hoc.tsx
- src/apps/reservation-list/reservation-material/reservation-material.tsx
https://reload.atlassian.net/browse/DDFLSBP-284
To make it visible to the user that we are fetching materials, we are showing a skeleton loader on the materials we are waiting to finish fetching
> Show skeleton loader when fetching materials

- src/apps/dashboard/dashboard.dev.tsx
- src/apps/dashboard/dashboard.entry.tsx
- src/apps/fee-list/FeeList.dev.tsx
- src/apps/fee-list/FeeList.entry.tsx
- src/apps/loan-list/list/loan-list.dev.tsx
- src/apps/loan-list/list/loan-list.entry.tsx
- src/apps/loan-list/materials/utils/status-badge.tsx
- src/apps/loan-list/materials/utils/status-circle.tsx
- src/apps/menu/menu.dev.tsx
- src/apps/menu/menu.entry.tsx
- src/apps/reservation-list/list/reservation-list.dev.tsx
- src/apps/reservation-list/list/reservation-list.entry.tsx
- src/core/storybook/reservationListArgs.ts
- src/core/utils/config.tsx
- src/core/utils/types/threshold-type.ts
- src/core/utils/useLoanThresholds.tsx
- src/core/utils/useLoans.tsx
- src/tests/unit/status-badge.test.tsx
https://reload.atlassian.net/browse/DDFSOEG-583
Refactoring thresholdConfig => expirationWarningDaysBeforeConfig
Because it has been changed in the cms.
Also adding test and a hook for getting the loan thresholds.
> Refactoring thresholdConfig => expirationWarningDaysBeforeConfig

- src/apps/menu/menu-navigation-list/MenuNavigationItem.tsx
https://reload.atlassian.net/browse/DDFLSBP-180
We want screen readers to read the number of reserved items. Because the number is not a semantic part of the a tag, the screen reader will ignore it.
An aria-label can solve this, but a more correct solution would be to move the span inside the a tag - which would require changes in design system aswell.
> Add aria label to link

- src/apps/reservation-list/reservation-material/reservation-info.tsx
https://reload.atlassian.net/browse/DDFLSBP-213
This PR introduces a fix so that all digital reservations get the correct label, instead of the physical reservation address.
n/a
n/a
> Show "online access" label for all digital materials

- src/apps/patron-page/PatronPage.dev.tsx
- src/apps/patron-page/PatronPage.entry.tsx
- src/apps/reservation-list/modal/pause-reservation/pause-reservation.tsx
- src/core/storybook/reservationListArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-209
This adds the ability to cancel an ongoing pause period after it has been set. 
The issue suggests, that the user should be prompted with a success message, but when #680 is introduced, the banner will update according to the current pause settings.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/14014012/ca7908a8-b2c0-4368-bd5b-1527a9685bf7
> Added ability to cancel pause period

- src/apps/reservation-list/list/reservation-list.dev.tsx
- src/apps/reservation-list/list/reservation-list.entry.tsx
- src/apps/reservation-list/list/reservation-list.test.ts
- src/apps/reservation-list/list/reservation-pause-toggler.tsx
- src/apps/reservation-list/modal/delete-reservation/pause-reservations.test.ts
- src/core/storybook/reservationListArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-70
Previously it was not clear if a pause was active or not, and a toggle button was used to open a modal for changing settings.
This PR adds some descriptive text about the state of the current pause and a "Settings" button that behaves as expected.
> Refactor reservation pause banner

- src/core/modal.slice.ts
https://reload.atlassian.net/browse/DDFLSBP-283
This PR fixes an issue with scrolling behind modals. The user shouldn't be able to scroll in the content behind a modal until the very last modal is closed. Before, the scrolling was made possible after any modal was closed.
n/a
n/a
> Only enable body scrolling after closing the last modal, not after every

- src/apps/reservation-list/modal/delete-reservation/pause-reservations.test.ts
- src/apps/reservation-list/modal/pause-reservation/pause-reservation.tsx
https://reload.atlassian.net/browse/DDFLSBP-210
We no longer want to control the pause start date from CMS, but always fallback to the current date
> Set default start pause date as today

- package.json
- src/apps/loan-list/materials/selectable-material/selectable-material.tsx
- src/apps/reservation-list/list/list.tsx
- yarn.lock
https://reload.atlassian.net/browse/DDFLSBP-278
https://reload.atlassian.net/browse/DDFLSBP-279
They were just put in roughly everywhere needed so the different views in group-modal and reservation-list had to be adjusted.
Depending on [PR](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/341) in design system.
When the other PR has been merged the dependency to the design system in package.json should be merged.
> Improve rendering of reservation labels (don't merge b4 design)

- .github/dependabot.yml
All these modules work with generated code. Thus generated code should  be updated when updating these modules.
With that in mind it makes sense include all of them in the same group.
The list of added modules are taken from the commit which introduced GraphQL Codegen:
https://github.com/danskernesdigitalebibliotek/dpl-react/commit/22e016d72a30ef3685784668f51b8ce7b48c8d2d
Our currently separate PRs related to this: #659 #598.
> Add all packages related to GraphQL codegen to existing Dependabot group

- .github/workflows/tests.yml
- cypress.json
This should allow running tests in parallel to provide a faster testing process. Also it may provide a better test debugging experience.
All setup is based on the example from the documentation: https://github.com/cypress-io/github-action#split-install-and-tests.
My own observations:
- Parallelization  brings down integration test time from 10 mins in #683 , 9 mins in #681 and 25 mins(!) in #680 to ~5 mins (x3). Of this 5 minutes ~2 minutes are spent setting up containers, Node and running `yarn install`.
- I find the PR comment annoying. It is just noise.
- We currently run tests on both pushes and pull requests. Perhaps we could reduce this.
- If we want to go with this we need to update required GitHub Actions 
- For the moment I do not think Cypress Cloud provides something unique …
> Initial support for Cypress Cloud

- package.json
- yarn.lock
The package does not seem to be used.
According to the documentation the package is used by adding typescript-graphql-typed-files-modules as a plugin in the YAML file for graphql-codegen.  https://github.com/agendrix/typescript-graphql-typed-files-modules
We do not have it declared in dbc-gateway.codegen.yml. Consequenty it does not seem to be used.
It is a bit tricky to remove packages which are only used for codegen and are not tested during standard CI. I think we should be good though.
The reason I add it now is that we have a Dependabot update for the package #713.
With that in mind I only assigned you @spaceo since you are the one who set up the code generation initially.
> Remove typescript-graphql-typed-files-modules

- .eslintrc
- package.json
- src/apps/advanced-search/advanced-search.test.ts
- yarn.lock
While it may be best practice to use this when developing tests it is not a good idea to have it commit to VCS.
Doing so will prevent our CI (and future developers) from running other tests.
This is especially severe when running all tests locally as this means that only tests using only() will be used.
Using eslint-plugin-no-only-tests seems to be the suggested solution: https://github.com/cypress-io/eslint-plugin-cypress/issues/28
This will fail at the moment. It should be merged once we have removed all the onlys. This occurs as a part of #612.
> Do not allow only() in tests

- src/apps/loan-list/list/loan-list.dev.tsx
- src/apps/loan-list/list/loan-list.entry.tsx
- src/apps/loan-list/materials/stackable-material/material-overdue-link.tsx
- src/core/utils/types/global-url-props.ts
https://reload.atlassian.net/browse/DDFLSBP-313
In an attempt to streamline the fee url to a single field from Drupal, we wan to use the feesAndCompensationRatesUrl instead. materialOverdueUrl has been depricated and removed from Drupal.
> Set correct fees url

- docs/README.md
The software which builds documentation (MkDocs) is picky about validating URLs, and will break if they are not valid. This should fix that problem.
As far as I know, we cannot determine whether this change will fix the [broken documentation builds](https://github.com/danskernesdigitalebibliotek/dpl-docs/actions/runs/6970384342/job/18968175754) until we merge it to `develop` (or `main`?).
> Fix Markdown syntax for link.

- src/apps/favorites-list/FavoritesList.dev.tsx
- src/apps/favorites-list/FavoritesList.entry.tsx
- src/apps/loan-list/list/loan-list.entry.tsx
https://reload.atlassian.net/browse/DDFLSBP-245
This PR adds missing translations to .dev & .entry files: `groupModalGoToMaterialAriaLabelText` was missing in loan-list.entry, and `availabilityAvailableText` & `availabilityUnavailableText` in FavoritesList.dev and .entry
n/a
n/a
> Provide all translation texts to all react apps

- src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx
- src/apps/loan-list/modal/material-details.tsx
- src/core/storybook/materialDetailsModalArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-274
In an attempt to streamline the fee url to a single field from Drupal, we wan to use the feesAndCompensationRatesUrl instead. feespageURL is used for the user fee page /user/me/fees
> Align fees url

- .docker/wiremock/fbs/mappings/fbs-availability-31ef8b31-c7f7-4463-89e9-1b1f9875864b.json
- .docker/wiremock/fbs/mappings/fbs-holdings-a530c110-c4a9-42f4-a06f-9390744b8b00.json
- docs/request_mocking_wiremock.md
- src/apps/material/material.dev.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
- src/components/reservation/UserListItems.tsx
- src/components/reservation/forms/NoInterestAfterModal.tsx
- src/components/reservation/helper.ts
- src/components/reservation/types.ts
- src/core/storybook/reservationMaterialDetailsArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-150
This PR updates the usage of the "interest period" after which a loaner is no longer interested in a material when reserving it. There were [some updates in the backend](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/475) to the structure of the data we use, so here we update the frontend part.
We also add new wiremock stubs for the material page (so that it doesn't crash when running it locally).
n/a
n/a
> Update interest period treshold with drupal

- .github/dependabot.yml
There are often dependencies between core Redux and packages building on Redux like Redux Toolkit, React Redux, Redux Persist e.g. #760 and #765.
Group them to make them move in parallel.
> Add Dependabot group for Redux

- src/apps/fee-list/FeeList.tsx
- src/apps/fee-list/utils/helper.ts
- src/core/configuration/index.ts
- src/core/configuration/payment.json
https://reload.atlassian.net/browse/DDFLSBP-349
Fees after 27th of October were not showing (payment change happened on that date) on the fees page.
n/a
> Show fees after payment change date on the fees page

- src/apps/loan-list/materials/stackable-material/stackable-material.tsx
https://reload.atlassian.net/browse/DDFLSBP-338
Some of the business logic needed to be updated for loan list cards. When clicking on the title of a grouped loan, it is the group modal that should open, not a modal with details. 
n/a
n/a
> Fix single vs group loan click events

- src/apps/advanced-search/AdvancedSearchResults.tsx
- src/apps/advanced-search/advanced-search.test.ts
- src/apps/advanced-search/types.ts
https://reload.atlassian.net/browse/DSC-81
The FBI API came out with some changes to their specs, so we now need to update how we contact it. As a part of this, most keys of advancedSearchIndexTranslations also needed to be updated to match.
As a part of this PR, a minor bug was also fixed where the number 0 was showing on the page as a part of the loading results text headline
n/a
n/a
> Update advanced search filters

- src/apps/loan-list/list/ListHeader.tsx
- src/apps/reservation-list/list/list.tsx
- src/components/list-header/list-header.tsx
https://reload.atlassian.net/browse/DDFLSBP-177
A div is not semantically correct to use inside a h-tag. Instead we should use a span and tell the screen reader to percieve it as a text.
> Use correct semantics for header

- .github/workflows/tests.yml
- cypress.json
This should allow running tests in parallel to provide a faster testing process. Also it may provide a better test debugging experience.
All setup is based on the example from the documentation: https://github.com/cypress-io/github-action#split-install-and-tests.
My own observations:
- Parallelization  brings down integration test time from 10 mins in #683 , 9 mins in #681 and 25 mins(!) in #680 to ~5 mins (x3). Of this 5 minutes ~2 minutes are spent setting up containers, Node and running `yarn install`.
- I find the PR comment annoying. It is just noise.
- We currently run tests on both pushes and pull requests. Perhaps we could reduce this.
- If we want to go with this we need to update required GitHub Actions 
- For the moment I do not think Cypress Cloud provides something unique …
> Reintroduce initial support for Cypress Cloud

- cypress/fixtures/material/open-order/fbi-api.json
- src/apps/material/material.dev.tsx
- src/apps/material/material.entry.tsx
- src/components/material/material-buttons/MaterialButtons.tsx
- src/components/material/material-buttons/physical/MaterialButtonsPhysical.tsx
- src/components/reservation/ReservationModalBody.tsx
- src/core/utils/helpers/general.ts
- src/core/utils/useReservableFromAnotherLibrary.tsx
- src/tests/unit/useReservableFromAnotherLibrary.test.tsx
https://reload.atlassian.net/browse/DDFSOEG-528
This pull request refactors the order buttons by moving the logic for displaying the `MaterialButtonReservableFromAnotherLibrary` component and refactoring the `getReservablePidsFromAnotherLibrary` function into a `useReservableFromAnotherLibrary` hook. That also checks if the material is not reservable and should be ordered via openOrder.
> Refactor button reservable from another library

- .github/workflows/create-release-on-branch-changes.yml
It has been unstable to download the dpl-design-system during the Github workflow that creates releases on branch changes. This seems to be a fix...
Solution found at:
https://stackoverflow.com/questions/61817010/installing-private-github-package-using-yarn-on-github-actions-is-unauthorized-w
> Try to fix dependency problem in the branch release workflow

- src/apps/reservation-list/modal/reservation-details/reservation-details-redirect.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
https://reload.atlassian.net/browse/DDFLSBP-344
A link text "delete reservation" was changed to an ghost button in the reservation details modal.
-
> Make "delete reservation" into a ghost button instead a text link

- .docker/wiremock/fbs/mappings/external_agencyid_patron_patronid_fees_v2-bd783b91-b464-4137-9575-b093008866df.json
- .docker/wiremock/fbs/mappings/fees-v2-without-parameters-ed922f92-46bb-46c6-926f-73678410fcd0.json
Change wrong wiremock request.url property
The pattern matching should be more precise in order to match the exact
query parameters or no query parameters.
Wiremock is failing delivering fees which breaks stories that depends on those.
> Change wrong wiremock request.url property

- src/apps/loan-list/list/ToggleListViewButtons.tsx
https://reload.atlassian.net/browse/DDFLSBP-369
Disable "renew multiple loans" button on mobile if there aren't any
The mobile button for the test user mentioned in the ticket:
-
> Disable "renew multiple loans" button on mobile if there aren't any

- src/apps/loan-list/materials/selectable-material/selectable-material.tsx
- src/components/Buttons/ArrowButton.tsx
https://reload.atlassian.net/browse/DDFLSBP-276
The arrows in material details modal were being shown inconsistently to the rest of the site. This PR in combination with its [sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/436) fixes that.
-
-
> Make it possible to give arrow button component classes

- src/apps/dashboard/dashboard.dev.tsx
- src/apps/dashboard/dashboard.test.tsx
- src/apps/fee-list/FeeList.dev.tsx
- src/apps/fee-list/FeeList.tsx
- src/apps/fee-list/fee-list.test.ts
- src/apps/fee-list/stackable-fees/stackable-fees.tsx
https://reload.atlassian.net/browse/DDFLSBP-386
This PR makes sure that when rendering currency we use comma instead of a dot for decimals as per European standards.
-
> Decimals with comma

- src/apps/loan-list/materials/stackable-material/material-info.tsx
- src/apps/loan-list/materials/stackable-material/stackable-material.tsx
https://reload.atlassian.net/browse/DDFLSBP-367
Pager gives focus to the next stackable material too quickly while still
registering the key press. So when interacting with the pager on the
keyboard, material details of the following, newly shown item would open
unintentionally.
-
-
> Don't open material details modal after interacting with the pager

- src/apps/fee-list/FeeList.dev.tsx
- src/apps/fee-list/FeeList.entry.tsx
- src/apps/fee-list/FeeList.tsx
- src/apps/fee-list/list.tsx
https://reload.atlassian.net/browse/DDFLSBP-387
Fee list text needs to be under 2 lists and translated into 2 different things. So now we have 2 texts.
-
This PR has [a sibling in dpl-cms](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/689)
> Add fee list second text string

- src/apps/reservation-list/reservation-material/reservation-info.tsx
- src/apps/reservation-list/reservation-material/reservation-status.tsx
- src/components/GroupModal/GroupModalReservationsList.tsx
https://reload.atlassian.net/browse/DDFLSBP-374
* Fixed double arrows by providing parameter for the "default case". 
* Changed `IndexOf()` to `findIndex()` for object array matching. `IndexOf()` compares objects based on their reference in memory, not their content. If you have a separate object with the same properties as an object in the array, `IndexOf()` won't find it because it checks for reference equality.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/105956/f482f1c1-d6ee-491f-9803-3401246cf6ba
Updated screenshot with:
* Remove queue number label for physical materials
*
> Fix Group Modal for Reservations [DDFLSBP-374]

- .github/workflows/create-release-on-branch-changes.yml
We often end up having releases with "untagged" in the asset url wich srews up our build pipeline. This could be a fix.
> Do not use prerelease in branch releases

- src/apps/dashboard/dashboard.dev.tsx
- src/apps/dashboard/dashboard.entry.tsx
- src/apps/menu/menu.dev.tsx
- src/apps/menu/menu.entry.tsx
- src/apps/reservation-list/list/reservation-list.dev.tsx
- src/apps/reservation-list/list/reservation-list.entry.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details-buttons.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
- src/apps/reservation-list/modal/reservation-details/reservation-details.tsx
- src/core/storybook/reservationListArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-154
* Removes display of 'Others in queue' from the details of a physical reservation.
*
> Remove 'Others in queue' from a physical reservation view‚ [DDFLSBP-154]

- src/apps/loan-list/materials/selectable-material/selectable-material.tsx
- src/apps/reservation-list/list/reservation-list.dev.tsx
- src/apps/reservation-list/list/reservation-list.entry.tsx
- src/apps/reservation-list/reservation-material/reservation-info.tsx
- src/apps/reservation-list/reservation-material/reservation-status.tsx
- src/apps/reservation-list/utils/helpers.ts
- src/components/GroupModal/GroupModalReservationsList.tsx
- src/core/storybook/reservationListArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-408
- General cleanup of the group reservations modal.
- In cases where the expected redeem date is unknown, it will now display 'You are in the reservation queue.'
- The link 'See details for the material' has been removed.
- The design of the expected redeem date has been adjusted in accordance with Figma.
- Alignment has been verified.
*
> Fix Group Modal for Reservations - part II [DDFLSBP-408]

- src/components/GroupModal/GroupModalLoansList.tsx
- src/core/storybook/groupModalArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-337
* Changes the status badge text from "To be returned" to "Expires" in the Group modal if the material is digital.
* `dpl-cms` PR: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/728
*
> Changes the status badge text if the material is digital [DDFLSBP-337]

- src/apps/dashboard/dashboard-notification-list/NotificationColumn.tsx
- src/apps/dashboard/dashboard-notification-list/Notifications.tsx
- src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx
- src/apps/dashboard/dashboard-notification/dashboard-notification.tsx
https://reload.atlassian.net/browse/DDFLSBP-252
This PR removes status labels in the user menu due to limited space.
*
> Remove status labels in the user menu [DDFLSBP-252]

- src/apps/dashboard/dashboard.entry.tsx
https://reload.atlassian.net/browse/DDFLSBP-217
This PR adds the blockedModal on dashboard for blocked patrons, just as it is shown on other pages.
The blockedModal is not centered, but this is a general thing and is corrected in another PR.
> DDFLSBP-217 - Added blockedModal to dashboard

- src/apps/loan-list/materials/selectable-material/selectable-material.tsx
https://reload.atlassian.net/browse/DDFLSBP-413
This PR introduces a check on openDetailsModal that only cursor: pointer classes if openDetailsModel is set.
> DDFLSBP-413 - Removed click icon on mouseover on fees groupmodal

- src/apps/loan-list/list/ToggleListViewButtons.tsx
- src/apps/loan-list/list/loan-list.dev.tsx
- src/apps/loan-list/list/loan-list.entry.tsx
- src/core/storybook/renewalArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-371
* Renew button text changes conditionally based on disableRenewLoansButton
* Corresponding `dpl-cms` pull request: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/738
*
> Change RenewLoansButton text based on disableRenewLoansButton [DDFLSBP-371] 

- src/components/reservation/helper.ts
- src/tests/unit/__vitest_data__/instant-loan.ts
- src/tests/unit/instant-loan.test.ts
This PR modified the `getInstantLoanBranchHoldings` to use precise matching with `===` instead of using the `includes` method for material group description.
> Refactor `getInstantLoanBranchHoldings`

- src/apps/dashboard/dashboard.test.tsx
- src/apps/dashboard/modal/ReservationsGroupModal.tsx
- src/apps/reservation-list/modal/delete-reservation/delete-reservation-modal.tsx
- src/apps/reservation-list/modal/delete-reservation/delete-reservation.test.ts
- src/core/storybook/reservationGroupModalArgs.ts
- src/core/storybook/reservationListArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-172
In this PR we adjust two text string definitions for when the user is deleting their queued reservations from the dashboard. There was no distinction between singular and plural form depending on how many reservations were deleted before, which is now fixed. 
-
[Sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/767)
> Distinguish singular/plural on delete reservation

- src/apps/reservation-list/list/reservation-list.dev.tsx
- src/apps/reservation-list/list/reservation-list.entry.tsx
- src/core/storybook/globalTextArgs.ts
-
While testing for [this task](https://reload.atlassian.net/browse/DDFLSBP-170) I have discovered that the dashboard app is failing and ´reservationListDigitalPickupText´ needs to be in global text args definition.
-
-
> Move global text argument reservationListDigitalPickupText into global

- .github/workflows/create-release-on-branch-changes.yml
We have the suspicion that the design system npm packages takes time in being ready. Let's wait a bit more for them to be available...
> Insert retry delay in installs in branch release workflow

- .github/workflows/create-release-on-branch-changes.yml
- .github/workflows/create-release-on-tag.yml
- package.json
- src/apps/material-grid/MaterialGrid.tsx
- src/apps/material-grid/automatic/MaterialGridAutomatic.entry.tsx
- src/apps/material-grid/automatic/MaterialGridAutomatic.tsx
- src/apps/material-grid/manual/MaterialGridManual.dev.tsx
- src/apps/material-grid/manual/MaterialGridManual.entry.tsx
- src/apps/material-grid/manual/MaterialGridManual.tsx
- src/apps/material/helper.ts
- src/apps/recommendation/recommendation.dev.tsx
- src/apps/recommendation/recommendation.entry.tsx
- src/apps/recommendation/recommendation.tsx
- src/apps/recommended-material/RecommendedMaterial.dev.tsx
- src/apps/recommended-material/RecommendedMaterial.entry.tsx
- src/apps/recommended-material/RecommendedMaterial.tsx
- src/apps/recommended-material/recommendedMaterialDisplayTypeData.ts
- src/core/utils/types/material-type.ts
- yarn.lock
[DDFFORM-369](https://reload.atlassian.net/browse/DDFFORM-369)
This is connected to [CMS PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/867)
This PR adds an optional materialType field to all components currently using the recommendedMaterial for displaying materials. 
Remember to read the commit messages and consider any question specified there. 
_Current styling for the material Grids are only in develop, which is not merged onto form-sprint-8_
Consider the used type casting. I was not sure what alternative to this there was. 
Consider wether the combined type in materialGrid `MaterialGridItemProps`should be a general type and used for all components using recommendedMaterial, or if the current implmenetation is better. I am still unsure about this, but i decided to …
> DDFFORM 369

- src/apps/loan-list/list/loan-list.tsx
- src/core/storybook/groupModalArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-463
Removes subheadline from loan list modal about where the loan can be returned.
-
-
> Delete text on user me loans

- src/apps/create-patron-user-info/UserInfo.tsx
https://reload.atlassian.net/browse/DDFLSBP-474
This PR adds cypress-data props to the two buttons on the user registration page. It adds it on the confirm and cancel buttons.
This PR will have a sister PR on dpl-cms: https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1030#issue-2188414530
> DDFLSBP-474 - Added data-cy props on create and cancel buttons

- src/apps/patron-page/PatronPage.tsx
https://reload.atlassian.net/browse/DDFLSBP-439
Don't show digital material loan quota on the user profile page if the user is logged in in a different municipality then their home one.
-
-
> Don't show digital material quota if not logged in home municipality

- src/apps/dashboard/dashboard-fees/dashboard-fees.tsx
- src/apps/loan-list/materials/utils/warning-bar.tsx
https://reload.atlassian.net/browse/DDFLSBP-461
Consolidate totalOwedText with totalAmountFeeText in WarningBar
*
> Consolidate totalOwedText with totalAmountFeeText in WarningBar [DDFLSBP-461] 

- src/apps/loan-list/list/loan-list.dev.tsx
- src/apps/loan-list/materials/selectable-material/StatusMessage.tsx
- src/apps/loan-list/materials/stackable-material/material-status.tsx
- src/apps/loan-list/modal/material-details.tsx
- src/apps/loan-list/modal/renew-button.tsx
https://reload.atlassian.net/browse/DDFLSBP-476
This PR adds the reasoning for not allowing users to renew their loans to the loan list page list items and inside the material detail modals on the same page for singular items.
-
> Add reason for failed loan renewal

- src/components/reservation/ReservationModalBody.tsx
https://reload.atlassian.net/browse/DDFLSBP-491
In the reservation modal - when changing between pickup branches, we didn't ask for the correct configuration - forgetting blacklistedPickupBranchesConfig branches. Now we add those on top of already used instant loan blacklisted branches, and as a result when an administrator changes this config in the backend, the changes take effect in the reservation modal as well.
-
-
> Differenciate between blacklistBranchesInstantLoan & pickupBlacklist

- src/core/dbc-gateway/helper.ts
- src/core/dbc-gateway/queryMap.ts
- src/core/storybook/serviceUrlArgs.ts
- src/core/utils/reduxMiddleware/extractServiceBaseUrls.ts
- src/core/utils/types/global-url-props.ts
It makes more sense to call the scopes local/global instead of search/material because local/global illustrates if the material comes from the local library inventory or the cross library inventory.
NB!!: [This](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/919) should be merged first.
> Cleanup query map naming

- src/apps/fee-list/FeeList.tsx
- src/apps/fee-list/list.tsx
- src/apps/fee-list/stackable-fees/stackable-fees.tsx
- src/apps/fee-list/utils/helper.ts
https://reload.atlassian.net/browse/DDFLSBP-411
In this PR we start to distinguish between fees and compensations when creating fee modals.
Before, if there ever were materials that had both fees and compensations on them, clicking on either one of them would result in opening the same modal. The other item would then have incorrect items inside the modal. Creating separate modal IDs for each fee/compensation fixes this problem.
-
-
> Fix fees and compensations modals

- src/apps/fee-list/FeeList.tsx
- src/apps/fee-list/FeeListItemSkeleton.tsx
- src/apps/fee-list/FeeListSkeleton.tsx
- src/apps/fee-list/fee-list.test.ts
- src/apps/fee-list/stackable-fees/stackable-fees.tsx
https://reload.atlassian.net/browse/DDFLSBP-485
A skeleton list view has been added while awaiting a response from FBS, and individual list items are shown as skeletons while waiting for a response from FBI.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/105956/b91f3be1-12cf-40a0-b9da-d10ee209ba47
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/105956/e367ed13-6e37-44f7-9074-4edde1804753
Det bemærkes at der opleves et "hop" i indholdet, dette skyldes at skrifttypen loades ind "sent"
*
> Add a skeleton list and list item to the Fee List Page [DDFLSBP-485]

- src/apps/favorites-list/FavoritesList.tsx
- src/apps/favorites-list/favorites-list.test.ts
- src/components/card-item-list/card-list-item/card-list-item-adapter.tsx
https://reload.atlassian.net/browse/DDFLSBP-484
Implements a skeleton loading view for the Favorites Page. Additionally, made CardListItem display CardListItemSkeleton while it's loading.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/105956/e7d4778b-a99f-42e5-bd47-4f31bd9902c7
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/105956/eb5df99f-3390-46fe-bf57-63e2ebf733ac
*
> Favorite Page skeleton view [DDFLSBP-484]

- .github/workflows/create-release-on-branch-changes.yml
- .github/workflows/create-release-on-tag.yml
We have repeatedly encountered problems installing new releases of the design system packages. When running yarn install we would get errors like:
```
error Error: https://npm.pkg.github.com/download/@danskernesdigitalebibliotek/dpl-design-system/2024.14.0-c34d09ae7fd2867f880dfcfd979fa295b4f9cf68/94b880305fad19177788cf3c23ac81771ba01df3: Request failed "401 Unauthorized"
```
This only occurred in GitHub Actions and only during creation of new releases based on branch or tag changes.
The changes here are yet another attempt at fixing this. They basically revert/reset the steps used to install dependencies to the ones used on all other workflows.
The assumption that this will work is based on the following observations:
- The errors only occur for the two affected workflows. All other …
> Yet another attempt at resolving issues with package install failures

- src/components/GroupModal/GroupModalLoansList.tsx
https://reload.atlassian.net/browse/DDFLSBP-480
This PR groups loans in group loan modal by renewability and shows the renewable ones on top.
-
-
> Show renewable loans grouped first, then non-renewable

- src/apps/opening-hours-editor/DialogFormEdit.tsx
- src/apps/opening-hours-editor/EventForm.tsx
- src/apps/opening-hours-editor/OpeningHoursEditor.dev.tsx
- src/apps/opening-hours-editor/OpeningHoursEditorEventContent.tsx
https://reload.atlassian.net/browse/DDFFORM-559
This pull request includes the following updates:
- Renaming the `Opening Hours Editor` story to enhance clarity.
- Adding Cypress data attributes to facilitate testing
> Ddfform 559 tests pa abningstider testning af redigering af abningstider

- src/components/material/material-buttons/physical/MaterialButtonsPhysical.tsx
https://reload.atlassian.net/browse/DDFLSBP-519
Show a loading reserve button on material page until all data is loaded. We were waiting for patron data to load, but not for material availability data, which was being loaded inside a custom React hook. React query caching handling is used in our advantage here in order to extract whether the loading state inside the hook.
-
-
> Show a loading reserve button on material page until all data is loaded

- src/apps/recommended-material/RecommendedMaterial.tsx
jira : [DDFFORM-497](https://reload.atlassian.net/browse/DDFFORM-497)
Before it was not possible to click the description text / author text in a recommended-material component. This makes it possible to click in the same way as the cover. 
[Design system  PR](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/579)
[DDFFORM-497]: https://reload.atlassian.net/browse/DDFFORM-497?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DDFFORM 497

- src/core/modal.slice.ts
https://reload.atlassian.net/browse/DDFLSBP-516
Updates the removeModalIdFromUrl function to accurately manage the 'modal' parameter using the [URL API](https://developer.mozilla.org/en-US/docs/Web/API/URL). This refactoring corrects an issue where previously the entire query string was discarded when modifying the 'modal' parameter.
This demonstrates that on the search page, one can open a modal, close it again, and subsequently press F5, with the search term remaining preserved in the URL.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/105956/d33a1179-cce9-448b-97d5-5ae49ed20287
> Use the URL API for more accurate parameter handling [DDFLSBP-516]

- src/components/autosuggest-category/autosuggest-category.tsx
https://reload.atlassian.net/browse/DDFLSBP-489
This PR fixes an issue where autosuggest category items from previous searches would pop up on top of the autosuggest item list. This was happening because the used React keys weren't unique, and so React was confused which items to rerender and which not to.
-
-
> Provide a unique key to each autosuggest category item so it rerenders

- src/apps/menu/menu.dev.tsx
- src/apps/menu/menu.entry.tsx
- src/apps/menu/menu.tsx
- src/components/search-bar/story-header.dev.inc.tsx
https://reload.atlassian.net/browse/DDFLSBP-551
This PR adds "Login" text under the user icon when user isn't logged in, and "Liked" under the heart icon in the nav menu, introducing two new text strings in the process.
-
[Sibling PR in the design system](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/603)
[Sibling PR in the cms](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1028)
> Add text under login and favorites

- src/apps/search-result/helper.ts
- src/apps/search-result/search-result-not-valid-search.tsx
- src/apps/search-result/search-result.dev.tsx
- src/apps/search-result/search-result.entry.tsx
- src/apps/search-result/search-result.tsx
- src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFLSBP-529
This PR introduces handling of search results with the query not defined, or under 3 characters in length.
-
[Sibling PR in the CMS](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1017)
> Searching for space

- src/apps/fee-list/FeeList.dev.tsx
- src/apps/fee-list/FeeList.entry.tsx
- src/apps/fee-list/FeeList.tsx
- src/apps/fee-list/fee-list.test.ts
- src/apps/fee-list/test-mappings.tsx
- src/apps/loan-list/materials/utils/warning-bar.tsx
https://reload.atlassian.net/browse/DDFLSBP-553
This PR adds a warning bar on top of the fees page is user has any overdue loans.
\+ tests
-
[Sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1032)
> Inform about fees when loan is overdue

- src/apps/material/material.dev.tsx
- src/components/material/material-buttons/helper.ts
- src/core/utils/types/material-type.ts
https://reload.atlassian.net/browse/DDFLSBP-622
There are many types of articles, and ALL of them need to always show the "see online" button on the material page and treat them as online materials. This PR adjusts the isArticle() helper function so that it searches for any material types containing the word "article" (in danish).
-
> Remove reserve and find on shelf from articles

- src/core/modal.slice.ts
Refactored removeModalIdFromUrl  to use common URL functions for consistency. Also, see the Zulip thread [here](https://reload.zulipchat.com/#narrow/stream/413259-DDF---brahma/topic/Brug.20af.20f.C3.A6lles.20url.20funktioner/near/434798325).
> Refactored removeModalIdFromUrl to use common URL functions

- src/apps/material/material.dev.tsx
- src/components/availability-label/availability-label.tsx
- src/components/availability-label/availability-labels.tsx
- src/components/material/MaterialMainfestationItem.tsx
https://reload.atlassian.net/browse/DDFLSBP-581
Make it possible for availability labels to be non-interactive elements, and use them like this on search result page for search result items that only have one material type + on material page in the top for materials that only have one material type + on material page in the "editions" disclosure for each item, as these availability labels don't serve an interactive function, but merely are visual labels.
-
-
> Make it possible for availability labels to be non-interactive elements

- src/components/reservation/ReservationModalBody.tsx
https://reload.atlassian.net/browse/DDFLSBP-632
Refactored to use defaultInterestPeriod from interestPeriodsConfig when no selectedInterest is provided.
> Fixed interestPeriod when default value is selected [DDFLSBP-632]

- src/apps/material-grid/MaterialGrid.tsx
https://reload.atlassian.net/browse/DDFFORM-751
This pull request ensures that the next item in the `MaterialGrid` receives focus after the "show more" button is clicked.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/49920322/eaaf153c-a6f9-4303-a2d6-4647b0bcc7a4
> Enhance `MaterialGrid` functionality to focus on next item after "show more" click

- orval.config.ts
- src/apps/opening-hours-editor/OpeningHoursEditor.tsx
- src/apps/opening-hours-editor/useOpeningHoursEditor.tsx
- src/core/dpl-cms/dpl-cms.ts
- src/core/dpl-cms/model/eventsGET200ItemImage.ts
https://reload.atlassian.net/browse/DDFFORM-787
This pull request enhances the fetching mechanism for opening hours in the admin area, ensuring that we only retrieve the necessary data for the current view.
The `datesSet` method from FullCalendar, which provides the currently displayed dates and updates with navigation button clicks, is now utilized. This ensures we fetch only the relevant opening hours for the current view.
<s>Initially, I attempted to use the `enabled` property in the options object of `useDplOpeningHoursListGET` but encountered the following error: "Object literal may only specify known properties, and 'enabled' does not exist in type '{ query?: UseQueryOptions<DplOpeningHoursListGET200Item[] | null, void, DplOpeningHoursListGET200Item[] | null, QueryKey> | undefined; …
> Integrate `handleDateSet` into `useOpeningHoursEditor` hook

- src/components/search-bar/search-bar.tsx
https://reload.atlassian.net/browse/DDFLSBP-636
Animate advanced search header dropdown icon on click to indicate state and make it crisp.
-
[Sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/643)
> Show currect status of advanced search dropdown

- src/apps/dashboard/dashboard-notification-list/NotificationColumn.tsx
- src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx
- src/apps/dashboard/dashboard.dev.tsx
- src/apps/dashboard/dashboard.entry.tsx
https://reload.atlassian.net/browse/DDFLSBP-546
This PR adds a text link at the bottom of each notification column on the dashboard. This fixes broken user journey paths - now there is a link to loan and reservation page.
[Sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1185)
> Add links from dashboard

- src/apps/menu/menu.tsx
https://reload.atlassian.net/browse/DDFLSBP-580
Swap user login icon aria labels - logged in /vs/ logged out - it was the other way around.
-
-
> Swap user login icon aria labels - logged in /vs/ logged out

- .github/workflows/create-cms-pr.yml
- .github/workflows/create-release-on-branch-changes.yml
https://reload.atlassian.net/browse/DDFLSBP-643
This PR adds a Github Workflow `create-cms-pr` that requests [dpl-cms to create a PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1158).
For separation of concerns the workflow is triggered by the `create-release-on-branch-changes` workflow. In that way we try to avoid leaving all steps in the `create-release-on-branch-changes` and isolate the remote pr action steps in a separate yml file.
The changes here are similar to the changes in the [dpl-design-ssystem repo](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/632).
We need to set secrret and variables similiar to what has been set in:
https://github.com/reload/poc-dpl-react-pr-trigger
> Add workflow that creates a pr externally in the dpl-cms repo

- src/apps/dashboard/dashboard-fees/dashboard-fees.tsx
https://reload.atlassian.net/browse/DDFLSBP-666
Don't show fee warning bar if user doesn't have any fees on dashboard.
-
-
> Don't show fee warning bar if user doesn't have any fees on dashboard

- src/components/material/StockAndReservationInfo.tsx
- src/components/reservation/ReservationModalBody.tsx
- src/components/reservation/ReservationSucces.tsx
https://reload.atlassian.net/browse/DDFLSBP-678
Don't show reservation count in the "successful reservation" modal.
-
-
> Remove reservation text unnecessary info

- src/apps/opening-hours/OpeningHoursHelpers.ts
https://reload.atlassian.net/browse/DDFFORM-802
This pull request implements sorting for opening hours.
Ensure that opening hours are sorted in the correct chronological order based on `start_time` and `end_time` when `start_time` is identical:
Additionally, I identified a redundant date value from `groupOpeningHoursByWeekday` that was duplicated by the `dateTime` value.
http://varnish.pr-1211.dpl-cms.dplplat01.dpl.reload.dk/test-raekkefolge-af-abningstider
> Ddfform 802 sort openning hours

- src/apps/material-grid/MaterialGrid.tsx
- src/apps/material-grid/automatic/MaterialGridAutomatic.dev.tsx
- src/apps/material-grid/automatic/MaterialGridAutomatic.entry.tsx
- src/apps/material-grid/automatic/MaterialGridAutomatic.tsx
- src/apps/material-grid/manual/MaterialGridManual.dev.tsx
- src/apps/material-grid/manual/MaterialGridManual.entry.tsx
- src/apps/material-grid/manual/MaterialGridManual.tsx
Jira ticket: [DDFFORM-520](https://reload.atlassian.net/browse/DDFFORM-520)
Design system PR: https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/644
CMS pr: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1198
This PR updates the react components material grid manual and automatic to take a new `description` prop, and display it if it is received. 
[DDFFORM-520]: https://reload.atlassian.net/browse/DDFFORM-520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DDFFORM 520 material grid desc

- src/components/horizontal-term-line/HorizontalTermLine.tsx
https://reload.atlassian.net/browse/DDFLSBP-670
Add stopPropagation to HorizontalTermLine links to prevent confusion in the CardListItem context
> Add stopPropagation to HorizontalTermLine links [DDFLSBP-670]

- src/apps/advanced-search/AdvancedSearchRow.tsx
https://reload.atlassian.net/browse/DDFLSBP-669
Number advanced search text field labels from 1 upwards instead from 0.
-
-
> Number advanced search text field labels from 1 upwards

- src/components/find-on-shelf/FindOnShelfManifestationListItem.tsx
https://reload.atlassian.net/browse/DDFLSBP-712
Show "1 home" instead of "1" for how many specimens of a manifestation are home available - in find on shelf modal.
-
-
> Show "1 (item) home" in find-on-shelf modal on mobile instead of "1"

- src/components/material/material-buttons/online/MaterialButtonOnlineExternal.tsx
- src/components/material/material-buttons/online/MaterialButtonsOnline.tsx
https://reload.atlassian.net/browse/DDFLSBP-698
* We cannot always be certain that the `Ereol` object is located at index 0. To ensure we link to https://ereolen.dk whenever possible, we first attempt to find an `Ereol` object. If it's not found, we then default to using the object at index 0.
* Simplify the URL translation logic in MaterialButtonOnlineExternal to ensure rerendering on externalUrl changes by using a single state for translatedUrl and consolidating effects.
> Use Ereol url if available [DDFLSBP-698]

- src/components/atoms/links/Link.tsx
- src/components/atoms/links/LinkNoStyle.tsx
- src/components/cover/cover.tsx
https://reload.atlassian.net/browse/DDFFORM-719
This pull request introduces the `isHiddenFromScreenReaders` attribute to the `Link` component.
To enhance accessibility, the `isHiddenFromScreenReaders` attribute has been implemented to manage the focusability of links. Links without meaningful content (such as those without text or images without alt text) should not be focusable.
I have included a check to ensure that if a `Cover` component does not have alt text, the associated wrapper link is not focusable by screen readers.
http://varnish.pr-1338.dpl-cms.dplplat01.dpl.reload.dk/frontpage
> Improve `Cover` accessibility by adding `isHiddenFromScreenReaders` attribute to `Link` component - Ddfform 719 

- src/apps/material-grid/MaterialGrid.tsx
- src/apps/material-search/Errors/HiddenInputsNotFoundError.tsx
- src/apps/material-search/Errors/MaterialSearchBaseError.tsx
- src/apps/material-search/Errors/MaterialTypeNotFoundError.tsx
- src/apps/material-search/Errors/WorkNotFoundError.tsx
- src/apps/material-search/Errors/errorState.ts
- src/apps/material-search/MaterialSearch.dev.tsx
- src/apps/material-search/MaterialSearch.entry.tsx
- src/apps/material-search/MaterialSearch.tsx
- src/apps/material-search/MaterialSearchPreview.tsx
- src/apps/material-search/useGetHiddenInputs.tsx
- src/apps/material-search/useGetSelectedWork.ts
- src/apps/material/helper.ts
- src/apps/recommendation/recommendation.entry.tsx
- src/apps/recommendation/recommendation.tsx
- src/apps/recommended-material/RecommendedMaterial.entry.tsx
- src/apps/recommended-material/RecommendedMaterial.tsx
- src/core/utils/types/material-type.ts
- **Add error hiddenInputsNotFound.**
- **Rewrite retrieval and usage of selectedWorkId and materialType.**
- **Update / Refactor materialSearch story to reflect changes in the approach of retrieving the workId and type through the DOM.**
Jira Ticket: [DDFFORM-883](https://reload.atlassian.net/browse/DDFFORM-883)
Related tickets: 
This PR attempts to update the logic for retrieving dpl_fbi_work_id saved values, and use it in the materialSearch app. 
The PR builds ontop of [DDFFORM-900](https://reload.atlassian.net/browse/DDFFORM-900). 
The saved values in drupal are now retrieving using JS instead of being passed a prop. 
This is due to an issue, where formState is not correctly moving the app "value" associated with field, which means that if an entry is deleted from i.e. material-grid, …
> DDFFORM 883 deleting materialsearch

- src/apps/loan-list/list/loan-list.test.ts
- src/apps/loan-list/materials/selectable-material/selectable-material.tsx
- src/apps/loan-list/materials/stackable-material/material-info.tsx
- src/apps/loan-list/materials/utils/material-fetch-hoc.tsx
- src/apps/reservation-list/list/reservation-list.test.ts
- src/core/utils/helpers/list-mapper.ts
- src/core/utils/types/list-type.ts
https://reload.atlassian.net/browse/DDFLSBP-595
This PR extends list types used for reservations and loans with the possibility of attaching basic details. This is used when returning data from FBS.
These basic details can then be used as fallback information for physical materials in case these cannot be retrieved from FBI in the material fetch higher-order component.
Without this then the material will not be rendered at all.
One known situation where this occurs is interlibrary loans from the Royal Danish Library.
Add a test showing that this works.
> Use FBS record for interlibrary loans and reservations where material cannot be found in FBI

- src/apps/material-grid/MaterialGrid.tsx
https://reload.atlassian.net/browse/DDFFORM-835
Introduced a guard check to ensure the `MaterialGrid` component is not rendered if there are no materials + logging the information to the console for debugging purposes.
https://varnish.pr-1436.dpl-cms.dplplat01.dpl.reload.dk/test-material-grid-automatic-har-0-hits
> Handle zero hits in `MaterialGrid`

- src/components/search-bar/search-bar.tsx
- src/components/search-bar/story-header.dev.inc.tsx
https://reload.atlassian.net/browse/DDFLSBP-637
Changed the advanced-search input element into a button element containing an image element.
This PR has a sister PR here: https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/701
> DDFLSBP-637 - Change advanced search input element into and img element

- src/apps/patron-page/util/BranchesDropdown.tsx
- src/components/atoms/input/TextInput.tsx
https://reload.atlassian.net/browse/DDFLSBP-690
Updated the required check to display empty string instead of null.
Also added an extra space between the asterisk to comply with how required fields are indidcated in the rest of the project.
Similar changes has been done in dpl-cms and dpl-react
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/681
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1363
> Updated the required check to display empty string instead of null.

- src/components/material/material-buttons/online/MaterialButtonOnlineExternal.tsx
https://reload.atlassian.net/browse/DDFBRA-41
This PR fixes an issue where external URLs didn't get proxy translated through the CMS service endpoint.
-
-
> Fix URL proxies

- src/apps/create-patron-user-info/UserInfo.tsx
- src/apps/patron-page/PatronPage.tsx
- src/apps/patron-page/PatronPageSkeleton.tsx
- src/components/contact-info-section/ContactInfoSection.tsx
https://reload.atlassian.net/browse/DDFHER-67
This pull request enables users to subscribe to SMS notifications (`receiveSms`) if the library allows SMS notifications (`text-notifications-enabled-config`) during the user creation process. If the user opts in, their phone number will be displayed as "mobile (notif)" in Cicero; otherwise, it will continue to appear under "fastnet."
Create an adult user at Copenhagen Library via Frontpage | DPL CMS
During user creation, there is now a checkbox below the phone number.
If this is checked, the number in Cicero will be listed as “mobile (notif)”, otherwise it will be listed as “fastnet”.
https://varnish.pr-1570.dpl-cms.dplplat01.dpl.reload.dk/
> DDFHER-67 - Add checkbox for `receiveSms` when creating user

- src/components/reservation/helper.ts
https://reload.atlassian.net/browse/DDFBRA-34
This PR fixes an issue that arose when reserving certain periodical materials (magazines). We never included volume in the reservation request, which was needed for these materials.
-
-
> Fix reserving periodicals

- cypress/fixtures/material/instant-loan/holdings.json
- src/apps/material/material.stories.tsx
- src/components/reservation/helper.ts
- src/tests/unit/__vitest_data__/instant-loan.ts
- src/tests/unit/instant-loan.test.ts
https://reload.atlassian.net/browse/DDFHER-90
This pull request refactors the `getInstantLoanBranchHoldings` method to use `materialGroup.name` instead of `.description`. This change addresses the issue where `.description` is an optional field, potentially leading to inconsistencies or missing data during the execution of this method.
https://varnish.pr-1608.dpl-cms.dplplat01.dpl.reload.dk/
> DDFHER-90 - Refactor `getInstantLoanBranchHoldings` to use `materialGroup.name`

- src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFHER-77
The issue was that users whose age exactly matched the configured minimum age were being rejected during validation. The logic previously checked if the user's age was strictly greater than the minimum age, which caused this issue.
This pull request updates the age validation to ensure that the calculated age is greater than or equal to the configured minimum age. This resolves the problem by allowing users who are exactly the minimum age to pass validation.
https://varnish.pr-1639.dpl-cms.dplplat01.dpl.reload.dk/
> DDFHER-77 - Allow age to be equal to the configured minimum age in `patronAgeValid`

- src/components/reservation/ReservationModalBody.tsx
- src/components/reservation/UserListItems.tsx
- src/components/reservation/forms/ModalReservationFormSelect.tsx
- src/components/reservation/forms/NoInterestAfterModal.tsx
- src/components/reservation/forms/PickupModal.tsx
https://reload.atlassian.net/browse/DDFBRA-47
This PR disables the "approve reservation" button if the user already clicked it. This prevents multiple requests from being fired before resolving. 
I also took the liberty to (for consistency's sake) unite the way we work with request state in regards to reservation - between the reservation modal and edit reservation modal in the user profile (reservations list page).
-
-
> Ddfbra 47 flere samtidige reserveringer

- src/apps/search-header/search-header.tsx
- src/apps/search-result/helper.ts
- src/apps/search-result/search-result.tsx
- src/apps/search-result/useFilterHandler.tsx
- src/core/storybook/serviceUrlArgs.ts
https://reload.atlassian.net/browse/DDFBRA-100
This PR fixes an issue for PR #790 - where category search didn't work. This was happening due to the FBI API spec change, where all the facets are now gathered inside the `FacetFieldEnum` which is CAPITALIZED, but the simple search query filters cannot be. So we now have a way to map between them. 
In the last commit ( f540ae59 ) I also took the liberty to fix an issue where persisted filters keep stacking up between searches. If you search for Harry `in books` and then follow up with Adam `in e-books` you would end up with a search for Adam `in books and ebooks`. So now whenever the user searches we reset persisted filters before redirecting to the search page.
-
-
> Ddfbra 100 filtrering sker ikke

- src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx
- src/apps/loan-list/list/loan-list.tsx
- src/components/GroupModal/GroupModalLoansList.tsx
- src/core/utils/helpers/general.ts
- src/core/utils/useLoans.tsx
https://reload.atlassian.net/browse/DDFHER-89
<s>This pull request updates the `sortByDueDate` function to handle cases where the loan does not have a due date and now using `dayjs` for date manipulation instead of the native Date object. Previously, the code used the current date as a fallback, causing inconsistent sorting results. The new logic assigns 'Infinity' to loans without a due date, ensuring they always appear at the bottom of the list.</s>
The issue was that not all loans were being sorted correctly. As a solution, we decided to move the sorting logic out of `useLoans`, since different parts of the app have varying sorting requirements. 
Additionally, we identified an issue with JavaScript's `.sort()` mutating the original array. Therefore, we opted to use `groupBy` from …
> DDFHER-89 - Ensure consistent sorting for loans

- package.json
- yarn.lock
https://reload.atlassian.net/browse/DDFHER-106
Somehow Dependabot will not make this update. I have run `yarn add downshift@latest` and tested it locally environment without problems.
**See doc**
https://github.com/downshift-js/downshift/blob/master/src/hooks/MIGRATION_V9.md#onchange-typescript-improvements
https://varnish.pr-1680.dpl-cms.dplplat01.dpl.reload.dk/
> DDFHER-106 - Updated `downshift` to version 9

- cypress.config.js
- cypress/plugins/index.js
- package.json
- src/apps/material/material.test.ts
- src/components/campaign/campaign.test.ts
- yarn.lock
https://reload.atlassian.net/browse/DDFBRA-136
- Bump Cypress to v13.15.0
- Disable Test Isolation
- use 'first()' on 'within()'
- Import Cypress plugins
> Upgrade Cypress

- cypress/support/index.ts
- package.json
- src/apps/advanced-search/AdvancedSearchHeader.tsx
- src/apps/advanced-search/PreviewSection.tsx
- src/core/utils/config.tsx
- src/core/utils/helpers/currency.ts
- src/core/utils/text.tsx
- src/core/utils/url.tsx
- src/core/utils/withSuffix.tsx
- yarn.lock
https://reload.atlassian.net/browse/DDFBRA-181
- Upgrade Typescript to version 5.6.3
- Cleanup Cypress commands
- Fix type errors caused by Typescript upgrade
> Upgrade Typescript to newest version

- src/components/find-on-shelf/FindOnShelfManifestationListItem.tsx
https://reload.atlassian.net/browse/DDFNEXT-661
This pull request fixes a bug where the "Emnetal" label (A.K.A. “DK5”) was no longer displayed in the “Find on Shelf” modal.
It resolves a minor oversight in [DDFHER-83](https://reload.atlassian.net/browse/DDFHER-83), where I mistakenly forgot to include `locationArrayWithShelfmark`.
https://varnish.pr-1833.dpl-cms.dplplat01.dpl.reload.dk/work/work-of:870970-basis:46867394?type=bog&modal=find-on-shelf-modal-46867394 
[DDFHER-83]: https://reload.atlassian.net/browse/DDFHER-83?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DDFNEXT-661 Fix "shelfmark" in `FindOnShelfManifestationListItem`

- .github/dependabot.yml
We want to ensure that React and React DOM is updated in parallel.
This is especially relevant for React 19.
> Add a Dependabot group for React dependencies

- src/apps/loan-list/modal/material-details-modal.tsx
- src/apps/loan-list/modal/material-details.tsx
- src/core/storybook/materialDetailsModalArgs.ts
- src/core/utils/useGetWorkUrlFromIdentifier.ts
https://reload.atlassian.net/browse/DDFBRA-236
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1814/
This pull request replaces the link from the digital loan list to point to the material page instead of eReolen.
Unfortunately, I also found a bug in our code that causes an infinite re-render. This issue is also present on the develop branch, and I didn't find an easy solution to fix it. Therefore, this should be fixed in a separate ticket.
If you have an online loan, you can view it under the “Digital Loans” section. The button, which was previously labeled “Go to eReolen” and linked to eReolen, has been updated to now correctly link to the work with the appropriate type selected.
https://varnish.pr-1814.dpl-cms.dplplat01.dpl.reload.dk/user/me/loans …
> DDFBRA-236 - Logged in user can go from digital loans to material

- src/apps/favorites-list/favorites-list.test.ts
- src/apps/material/material.test.ts
https://reload.atlassian.net/browse/DDFBRA-229
While working with upgrades within the project, I discovered that we don't actually test the functionality of favorites.
This PR extends `favorites-list.test.ts` and `material.test.ts` to also test the functionality of favorites.
> DDFBRA-229 - Test favorites

- src/apps/loan-list/materials/utils/digital-material-fetch-hoc.tsx
- src/components/availability-label/availability-label.tsx
- src/components/availability-label/useOnlineAvailabilityData.ts
- src/components/material/MaterialAvailabilityText/online/MaterialAvailabilityTextOnline.tsx
https://reload.atlassian.net/browse/DDFBRA-283
We have identified a recurring issue in the code where attempts are made to access the first element of an empty array (`array[0]`), which results in `undefined`.
This issue occurs across all articles where the identifier is an empty array.
Additionally, our TypeScript implementation requires the `useGetV1ProductsIdentifier` hook to receive a string. To satisfy TypeScript, we currently use `|| ""`, even though the hook is only activated when a value is present. However, this approach has inadvertently allowed errors to occur, and we have been uncertain about how to address this properly.
This change ensures that the `|| ""` fallback in `useGetV1ProductsIdentifier` is never activated, effectively preventing the error from occurring. …
> DDFBRA-283 - Ensure `v1/products/` is never called without an identifier

- package.json
- src/apps/advanced-search/advanced-search.test.ts
- src/apps/loan-list/list/loan-list.test.ts
- src/apps/material/instant-loan.test.ts
- src/apps/material/login-redirect.test.ts
- src/apps/material/material.test.ts
- src/apps/material/order-digital-copy.test.ts
- src/apps/search-header/search-header.test.ts
- src/apps/search-result/facet-browser.test.ts
- src/components/multiselect/Multiselect.test.ts
- yarn.lock
https://reload.atlassian.net/browse/DDFNEXT-224
- Bump eslint-plugin-cypress to version 4.1.0
- Fixed issues in the where the linter was throwing "cypress/unsafe-to-chain-command" errors
> Bump eslint-plugin-cypress to version 4.1.0

- dbc-gateway.codegen.yml
https://reload.atlassian.net/browse/DDFBRA-211
Because we are using an older version react-query before it changed to TanStack, graphql-codegen references the new react-query package path, which does not exist in this project. By setting `legacyMode: true` we can instruct codegen to use the old react-query path as documented here:
https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-react-query#legacymode
I verified that `yarn codegen:dbc:gateway` worked as expected, but could not introduce schema changes in this PR, as breaking type changes has been made to the API which should be resolved in a different task.
> Use codegen in legacy mode

- src/apps/material-search/useInfiteScrollLoading.ts
- src/components/GroupModal/GroupModalContent.tsx
- src/core/utils/helpers/lazy-load.ts
https://reload.atlassian.net/browse/DDFBRA-407
Replace `@ts-ignore` with `@ts-expect-error`
This way TypeScript will let us know when a fix is made in the `react-use` package, and that we can safely remove the Directive Comments, which saves the need for a TODO in the code.
> Handle TS error differently

- eslint.config.mjs
- src/apps/loan-list/materials/utils/digital-material-fetch-hoc.tsx
- src/apps/loan-list/materials/utils/material-fetch-hoc.tsx
- src/core/utils/withIsPatronBlockedHoc.tsx
https://reload.atlassian.net/browse/DDFBRA-406
We have decided on the Brahma team to disable the eslint rule, as it is very much an edge case to have a display name for higher order components when using React Developer Tools.
It would not be worth it to rewrite existing higher order components or having it required for any future ones.
> Disable `react/display-name` eslint rule

- src/apps/material-grid/automatic/MaterialGridAutomatic.tsx
- src/apps/material-grid/link-automatic/MaterialGridLinkAutomatic.tsx
- src/apps/material-search/MaterialSearchList.tsx
- src/components/simple-material/SimpleMaterial.tsx
- src/components/simple-material/SimpleMaterialAdapter.tsx
- src/core/utils/helpers/general.ts
- src/core/utils/types/entities.ts
https://reload.atlassian.net/browse/DDFNEXT-752
Refactor `MaterialSearchList` to use work titles directly instead of a helper function.
The work data comes from `useComplexSearchWithPaginationQuery` and uses `WorkSmall`, which does not contain `mainLanguages` and `materialTypes`, both of which are required for `getWorkTitle`.
> DDFNEXT-752 - Fix `2025.10.0`

- cypress/fixtures/material-buttons/material-buttons-movie-fbi-api.json
- src/components/material/material-buttons/online/MaterialButtonsOnline.tsx
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.schema.json
- src/core/dbc-gateway/generated/graphql.ts
https://reload.atlassian.net/browse/DDFBRA-502
This PR refactors how we get the correct access element before rendering the external manifestation link button. By making sure that we find the access element, which has the status as "OK", an inactive link will not get rendered.
> Never render an inactive access url

- src/apps/menu/menu.stories.tsx
- src/apps/patron-page/PatronPage.entry.tsx
- src/apps/patron-page/PatronPage.stories.tsx
- src/apps/patron-page/PatronPage.test.tsx
- src/apps/patron-page/sections/StatusSection.tsx
- src/apps/reservation-list/list/reservation-list.entry.tsx
- src/apps/reservation-list/list/reservation-list.stories.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
- src/components/availability-label/useOnlineAvailabilityData.ts
- src/components/material/reserve-button.md
- src/core/storybook/publizonErrorArgs.ts
- src/core/storybook/reservationListArgs.ts
- src/core/storybook/reservationMaterialDetailsArgs.ts
- src/core/utils/types/global-url-props.ts
https://reload.atlassian.net/browse/DDFBRA-187
This PR removes obsolete references to `eReolen` in the application.
- Cleaned up unused text and outdated URLs that referenced `eReolen`.
- Removed `patronPageStatusSectionLinkText` and `alwaysAvailableEreolenUrl` as these concepts are no longer relevant since we can not filter exclusively for blue titles.
DPL-CMS PR:
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2144
https://varnish.pr-2144.dpl-cms.dplplat01.dpl.reload.dk/
> DDFBRA-187 - Remove `eReolen` references from the application

- src/apps/material/helper.ts
- src/components/availability-label/availability-labels.tsx
- src/components/material/MaterialAvailabilityText/MaterialAvailabilityText.tsx
- src/components/material/material-buttons/MaterialButtons.tsx
- src/components/material/material-buttons/online/MaterialButtonsOnlineInternal.tsx
- src/components/material/material-buttons/physical/MaterialButtonsPhysical.tsx
- src/components/reservation/OnlineInternalModalBody.tsx
- src/components/reservation/ReservationModalBody.tsx
- src/components/reservation/helper.ts
- src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFSAL-34
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2168
Updated reservation tracking to include material type. 
This change ensures that libraries have the necessary data for proper tracking, as workId alone was not sufficient.
I went down a bit of a rabbit hole by not using [0] on arrays, as Copilot first commented, since it may be undefined. This led to some changes that are not ticket-relevant but improve the current code. My Git commit should be descriptive of why I made the changes.
I have chosen to ignore the last Copilot suggestions, as I don’t think they are relevant.
https://varnish.pr-2168.dpl-cms.dplplat01.dpl.reload.dk/
> DDFSAL-34 - Add material type to reservation tracking

- .github/workflows/tests.yml
https://reload.atlassian.net/browse/DDFBRA-323
This PR upgrades the usage of codecov in our Github action to version 5.
While upgrading I discovered that it is now required to use an access token, which has been added to the repo.
I also discovered that the action was running inside a limited cypress container, which did not have the required packages available. As the cypress container was added to address a Chrome bug, that has since been fixed, it could be safely removed.
> Upgrade codecov action to version 5

- src/components/material/material-buttons/MaterialButtons.tsx
- src/components/material/material-buttons/physical/MaterialButtonReservableFromAnotherLibrary.tsx
- src/core/statistics/statistics.ts
https://reload.atlassian.net/browse/DDFSAL-37
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2193
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2193
This tracks when the modal is opened for reserving from another library, not the actual reservation itself, which is already tracked with `statistics.reservation`.
https://varnish.pr-2193.dpl-cms.dplplat01.dpl.reload.dk/
> DDFSAL-37 - Track click to open "reserve from another library" modal

- src/components/material/MaterialMainfestationItem.tsx
- src/components/material/material-buttons/MaterialButtons.tsx
- src/components/material/material-buttons/physical/MaterialButtonPhysical.tsx
- src/components/material/material-buttons/physical/MaterialButtonReservableFromAnotherLibrary.tsx
- src/components/material/material-buttons/physical/MaterialButtonsPhysical.tsx
- src/core/statistics/statistics.ts
https://reload.atlassian.net/browse/DDFSAL-36
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2186
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2186
This tracks when the modal is opened for a specific manifestation, not the actual reservation itself, which we already track with `statistics.reservation`.
https://varnish.pr-2186.dpl-cms.dplplat01.dpl.reload.dk/
> DDFSAL-36 - Track click to open reservation modal for specific manifestation

- src/apps/advanced-search/AdvancedSearchHeader.tsx
- src/core/statistics/statistics.ts
https://reload.atlassian.net/browse/DDFSAL-56
https://varnish.pr-2202.dpl-cms.dplplat01.dpl.reload.dk/advanced-search
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2202
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2202
Implement tracking of CQL queries on Advanced Search
The `handleSearchButtonClick` function tracks search term using two different CQL sources depending on the user's interaction mode
> DDFSAL-56 - Track CQL on search click in Advanced Search

- codecov.yml
Code coverage patch status has been missing for a while. Now that is it back we see it failing a lot.
Make it informational just as the project status is. This avoids the noice while stille keeping track of code coverage for future work.
See more documentation here: https://docs.codecov.com/docs/commit-status#patch-status
#1773 shows that this works while the original version of the change #1766 fails.
Before:
After:
This was made relevant again after #1759 was merged.
> Make codecov patch status informational

- src/components/facet-line/FacetLine.tsx
[Jira](https://reload.atlassian.net/jira/software/c/projects/DDFSAL/boards/539?selectedIssue=DDFSAL-12)
The intend of this change is to allow users to see more facets, which was limited to 5.
I've decided to start with changing this limit to 50 to begin with.
Option lists in a <select/> element, and are not easily styled. Because of this, i've also decided to see if the native renders of these will suffice before changing more markup.
> Increase the limit of Facets being displayed to users to 50.

- src/components/material/material-buttons/online/MaterialButtonsOnline.tsx
https://reload.atlassian.net/browse/DDFNEXT-777
https://reload.atlassian.net/browse/DDFNEXT-778
It seems DBC sometimes returns manifestations where all access URLs have `status: BROKEN`. As we throw an error when no accessElement is found, this breaks the whole material page.
> Don't render button if no active AccessUrl is found

- src/components/atoms/links/LinkNoStyle.tsx
- src/components/cover/cover.tsx
- src/components/recommended-material/recommended-material.tsx
- src/core/statistics/statistics.ts
- src/core/statistics/useStatistics.ts
https://reload.atlassian.net/browse/DDFSAL-45
https://varnish.pr-2389.dpl-cms.dplplat01.dpl.reload.dk/paragraph-side
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2389
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2389
Implements click tracking for recommended materials.  
Since only one tracking ID is available at the moment, it's applied to all three links: cover, title, and author.
> DDFSAL-45 - Track click on recommended material

- src/components/campaign/Campaign.tsx
- src/core/statistics/statistics.ts
- src/core/statistics/useStatistics.ts
https://reload.atlassian.net/browse/DDFSAL-62
https://varnish.pr-2395.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2395
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2395
This pull request refactors the campaign tracking logic by introducing a new URL tracking utility and updating the campaign statistics configuration to align with the settings in Mapp.
- Introduced a new `useUrlStatistics` hook in `useStatistics.ts` to manage redirections to campaign URLs with tracking parameters. This includes URL validation and appending the `u_navigatedby` parameter before redirection.
- Replaced `useEventStatistics` with `useUrlStatistics` in `Campaign.tsx`, removing the obsolete `trackClick` function and using the new …
> DDFSAL-62 - Campaign tracking

- src/apps/material/__snapshots__/helper.ts.snap
- src/apps/material/__vitest_data__/helper.ts
- src/apps/material/helper.ts
- src/apps/material/material.tsx
- src/components/find-on-shelf/mocked-data.ts
- src/core/dbc-gateway/fragments.graphql
- src/core/dbc-gateway/generated/graphql.schema.json
- src/core/dbc-gateway/generated/graphql.ts
https://reload.atlassian.net/browse/DDFSAL-49
https://varnish.pr-2399.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2399
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2399
This pull request updates the data sent for Mapp `materialAudience` tracking.
Previously, the necessary data was not available in the dbc Fbi dataset. I’ve added the required field to the GraphQL schema, generated new types and updated the relevant mocks accordingly.
> DDFSAL-49 - Correct data for `materialAudience` mapp traking

- src/apps/material/material.entry.tsx
- src/apps/material/material.stories.tsx
- src/components/reservation/ReservationModalBody.tsx
https://reload.atlassian.net/browse/DDFSAL-91
https://reload.atlassian.net/browse/DDFSAL-128
https://varnish.pr-2405.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2405
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2405
This pull request introduces a new feature to handle cases where a user without an email address attempts to reserve materials from another library.
> DDFSAL-91 - Implement email validation for OpenOrder reservations

- src/apps/material/material.tsx
- src/components/material/material-buttons/online/MaterialButtonsOnlineInternal.tsx
https://reload.atlassian.net/browse/DDFSAL-109
https://varnish.pr-2483.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2483
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2483
There were two main issues:
1. The `<OnlineInternalModal />` was only rendered when the selected manifestation was an e-book or e-audiobook. This prevented the modal from opening via the buttons in the editions list when a physical book was selected.
2. We were only rendering a modal for the selected manifestation’s Faust ID. As a result, if a user selected an e-book or audiobook, only that specific modal was available — others were not.
This update ensures that:
- A modal is rendered for each Faust ID, regardless of the selected manifestation.
- …
> DDFSAL-109 - Fix e-materials modal not opening under all conditions

- src/components/reservation/helper.ts
https://reload.atlassian.net/browse/DDFBRA-674
While working on DDFBRA-674, I discovered a bug related to instantloan that was not mentioned in the ticket.
At Frederiksberg Library, the value of `instantLoanString` was `"31filial/1xforny/ures"`, whereas `materialGroup.name` was `"31filial/1xforny/ures "` — note the trailing whitespace in the latter. This mismatch led to comparison issues.
To address this, I applied trim() to both values to ensure consistent comparison and prevent errors caused by unexpected whitespace.
> DDFBRA-674 - Trim `instantLoanString` and `materialGroup.name` to prevent mismatches

- package.json
- src/apps/search-header/search-header.tsx
- src/components/autosuggest/autosuggest.tsx
- yarn.lock
Reverts danskernesdigitalebibliotek/dpl-react#1875
During testing we have seen that this causes problems. Roll the changes back so we can investigate.
> Revert "Add autosuggest backdrop to search header"

- src/apps/loan-list/list/loan-list.test.ts
- src/apps/loan-list/materials/stackable-material/material-status.tsx
- src/apps/reservation-list/list/reservation-list.test.ts
- src/apps/reservation-list/modal/reservation-details/digital-list-details.tsx
- src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
- src/core/utils/helpers/date.ts
https://reload.atlassian.net/browse/DDFSAL-85
https://varnish.pr-2532.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2532
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2532
Publizon, which sends the relevant emails, does not support local timezone formatting. This update applies UTC formatting to ensure consistency across all eMaterials.
> DDFSAL-85 - Use UTC date formatting for eMaterials

- src/apps/patron-page/PatronPage.entry.tsx
- src/apps/patron-page/PatronPage.stories.tsx
- src/apps/patron-page/PatronPage.tsx
- src/apps/patron-page/sections/BasicDetailsSection.tsx
https://reload.atlassian.net/browse/DDFSAL-188
https://varnish.pr-2587.dpl-cms.dplplat01.dpl.reload.dk/user/me
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2587
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2587
This PR adds support for displaying the friendly card number on the `PatronPage`, improving the user experience for patrons encountering issues with Publizon.
Publizon's API returns a `FriendlyCardResult` object rather than an array. To handle this correctly, the response is cast to `FriendlyCardResult`, ensuring proper access to the required data.
> DDFSAL-188 - Add friendly card number to PatronPage

- src/apps/material/material.entry.tsx
- src/apps/material/material.stories.tsx
- src/components/find-on-shelf/FindOnShelfModalBody.tsx
https://reload.atlassian.net/browse/DDFSAL-251
https://varnish.pr-2613.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2613
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2613
This pull request enables the functionality for the new `find_on_shelf_disclosures_default_open` setting from drupal.
It allows smaller libraries to configure all Find on Shelf disclosures to be open by default.
This pull request introduces a new configuration option, `findOnShelfDisclosuresDefaultOpenConfig`, and integrates it across multiple files to control the default open state of disclosures in the "Find on Shelf" modal. The changes ensure the new configuration is properly added to the props, stories, and modal logic.
* Added …
> DDFSAL-251 - Option to have ‘Find on shelf’ always expanded by default.

- src/apps/material/material.entry.tsx
- src/apps/material/material.stories.tsx
- src/apps/material/material.test.ts
- src/components/material/MaterialReviews.tsx
- src/components/material/ReviewLibrarian.tsx
- src/components/material/ReviewMetadata.tsx
https://reload.atlassian.net/browse/DDFSAL-253
https://varnish.pr-2633.dpl-cms.dplplat01.dpl.reload.dk/work/work-of:870970-basis:06309801?type=lydbog+%28online%29 
https://varnish.pr-2633.dpl-cms.dplplat01.dpl.reload.dk/work/work-of:870970-basis:81188645?type=film+%28online%29
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2633
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2633
This pull request updates the `MaterialReviews` component to enhance the logic for determining review types. The most significant change is the addition of a check for `reviewByLibrarians` data, ensuring the "librarian" type is returned even when access is empty.
> DDFSAL-253 - Ensure that reviewByLibrarians is shown

- src/core/utils/modal.tsx
Refactor facet browser to use MODAL_Z_INDEX
Ensures proper stacking context following recent design system changes: https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/907
> Fix facet browser z-index

- src/components/date-inputs/DateRangeInput.tsx
https://reload.atlassian.net/browse/DDFSAL-187
https://varnish.pr-2664.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2664
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2664
<s>This pull request ensures that date ranges returned from the `/external/agencyid/patrons/patronid/v4` `onHold` field are correctly passed into the `DateRangeInput` component and parsed consistently across timezones by setting the time to noon using `.hour(12)`.
Previously, parsing a date like "2025-08-06" without a time component defaulted to midnight UTC, which could cause the date to shift to the previous day in local timezones. </s>
This pull request fixes issues with date range handling in the `DateRangeInput` component, particularly around …
> DDFSAL-187 - Fix reservation pause dates

- src/components/reservation/ReservationModalBody.tsx
- src/core/utils/useReservableFromAnotherLibrary.tsx
https://reload.atlassian.net/browse/DDFSAL-278
https://varnish.pr-2668.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2668
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2668
This pull request updates reservation logic and data fetching for the reservation modal. The main changes improve how reservations are processed depending on the material's availability and update the holdings data query to better reflect actual reservability.
**Reservation logic improvements:**
* In `ReservationModalBody.tsx`, the logic in `saveReservation` now prevents reserving materials from another library through the default reservation flow, ensuring such reservations are handled separately.
* The conditional for handling reservations from …
> DDFSAL-278

- cypress/fixtures/material/userinfo.json
- src/apps/material/material.entry.tsx
- src/apps/material/material.stories.tsx
- src/apps/material/material.test.ts
- src/apps/material/order-digital-copy.test.ts
- src/components/material/infomedia/InfomediaModal.tsx
- src/components/material/material-buttons/material-buttons.test.ts
- src/components/material/material-buttons/online/MaterialButtonOnlineDigitalArticle.tsx
- src/components/material/material-buttons/online/MaterialButtonOnlineInfomediaArticle.tsx
- src/core/utils/helpers/user.ts
- src/core/utils/helpers/userInfo.ts
https://reload.atlassian.net/browse/DDFSAL-270
https://varnish.pr-2646.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2646
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2646
This pull request ensures that users who are permitted by their municipality can read online and Infomedia articles.
Previously, we relied on patron.resident to determine access. However, some municipalities allow other users to access Infomedia articles as well. Therefore, we now check whether siteAgencyId matches municipalityAgencyId to determine eligibility.
> DDFSAL-270 - Infomedia should be consulted with municipality agency

- src/apps/create-patron-user-info/CreatePatron.tsx
- src/components/material/infomedia/InfomediaModal.tsx
- src/components/material/material-buttons/online/MaterialButtonOnlineDigitalArticle.tsx
- src/components/material/material-buttons/online/MaterialButtonOnlineInfomediaArticle.tsx
- src/core/adgangsplatformen/useUserInfo.ts
- src/core/utils/useSavePatron.tsx
https://reload.atlassian.net/browse/DDFSAL-419
- Disable user info fetching for anonymous users
- Remove error throwing to prevent the site from failing hard when anonymous users tries to get userData which is not possible as they are not logged in
> fix: disable user info fetching for anonymous users
