danskernesdigitalebibliotek/dpl-react

cypress.json, cypress/plugins/index.js, cypress/tsconfig.json, package.json, src/apps/hello-world/hello-world.test.ts, tsconfig.json, yarn.lock
Makes sure that we can run *.dev.ts cypress files
Install branch and run: `yarn test` and see the test pass.
You can also run `cypress:open` and see it in action.
Look at commits
https://reload.atlassian.net/browse/DDFSOEG-90
=> Cypress TS setup and hello-world app test

.github/workflows/release.yml
Doing as a part of this task:
https://reload.atlassian.net/browse/DDFSOEG-98
This will ensure that we get a build on HEAD of every branch which is handy for development
For more information see:
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/113
=> Build release on every push

.eslintrc, .github/workflows/release.yml, .storybook/webpack.config.js, architecture/adr-002-ui-text-handling.md, docs/ui_text_handling.md, package.json, src/apps/hello-world/hello-world.dev.tsx, src/apps/hello-world/hello-world.entry.tsx, src/apps/hello-world/hello-world.tsx, src/apps/search-header/search-header.dev.tsx, src/apps/search-header/search-header.entry.tsx, src/apps/search-header/search-header.mount.ts, src/apps/search-header/search-header.tsx, src/components/hello/hello.dev.tsx, src/components/hello/hello.tsx, src/components/search-bar/search-bar.dev.tsx, src/components/search-bar/search-bar.tsx, src/components/search-bar/story-header.dev.inc.tsx, src/core/store.ts, src/core/text.slice.ts, src/core/utils/text.tsx, webpack.config.js, yarn.lock
No ticket.
First release sprint merges.
=> Release PR

src/apps/adgangsplatformen/auth.dev.jsx, src/apps/adgangsplatformen/auth.jsx, src/apps/adgangsplatformen/auth.test.js, src/apps/adgangsplatformen/library-token.dev.tsx, src/apps/demo-search-header/demo-search-header.dev.tsx, src/apps/hello-world/hello-world.dev.tsx, src/apps/hello-world/hello-world.test.ts
Just a little cleanup of the storybook items to make it clear what is storybook tools and what is real apps.
=> Make separation between apps and sb utilities

.storybook/preview.js
No issue
Makes it possible to define library token in  local .env.
=> Makes it possible to define library token in  local .env

src/apps/material/material.dev.tsx, src/apps/material/material.entry.tsx, src/apps/material/material.mount.ts, src/apps/material/material.tsx, src/components/availability-label/availability-labels.tsx, src/core/utils/helpers.ts, src/core/utils/types/ids.ts
https://reload.atlassian.net/browse/DDFSOEG-175
This PR introduce material app.
Material app is container for material page and it receives 2 props(pid, workId) that it gets from url (can also be set via storybook)
**With url parameters**
**With storybook**
**UTILS FILES ARE CHECKOUT FOM** https://github.com/danskernesdigitalebibliotek/dpl-react/pull/36
=> Introduce material app

src/apps/material/material.dev.tsx, src/apps/material/material.entry.tsx, src/apps/search-result/helpers.ts, src/apps/search-result/search-result.entry.tsx, src/core/utils/helpers.ts
Either from props or from url parameters
We have several places where we need to check if data attributes are set -> if not check url params.
=> Add function that can extract params

src/components/atoms/link-no-style.tsx, src/components/atoms/link.tsx, src/components/availability-label/availability-label.tsx, src/components/cover/cover.tsx, src/components/search-result-list/search-result-list-item/search-result-list-item.tsx
This PR is refactor the Link component to be simpler and added a new LinkNoStyle component that adds .hide-linkstyle as the first css class
=> Link refactor 

src/components/material/disclosures/disclosure.tsx
To be used in the bottom of the material page
https://reload.atlassian.net/browse/DDFSOEG-168
It is a very simple component with the proper classes.
=> Add disclosure component

src/components/description-list/description-list.tsx
https://reload.atlassian.net/browse/DDFSOEG-169
A generic label/value list component that will be used for manifestations and material details on
the material page.
=> Add description list

package.json, src/apps/material/material.dev.tsx, src/apps/material/material.entry.tsx, src/apps/material/material.tsx, src/components/Buttons/ButtonLargeOutline.tsx, src/components/Buttons/ButtonSmallFilled.tsx, src/components/list-description/list-description.tsx, src/components/material/MaterialMainfestationItem.tsx, src/components/material/disclosures/disclosure.tsx, src/core/dbc-gateway/fragments.graphql, src/core/dbc-gateway/generated/graphql.tsx, yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-169
This PR introduces material editions.
Editions are shown in the Disclosure component on the Material page. its purpose is to show the remaining versions of the material.
=> Material editions

package.json, src/components/cover/cover.tsx, yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-177
This must be done at the same time as https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/120 !!!
Remember to change "@danskernesdigitalebibliotek/dpl-design-system": to the new version
Material has changed its name to Cover in the dpl-design-system so we have to change class names here too
=> See this ! https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/120

src/apps/loan-list/list/loan-list.tsx, src/apps/material/material.entry.tsx, src/apps/material/material.tsx, src/apps/search-result/search-result.dev.tsx, src/apps/search-result/search-result.entry.tsx, src/components/atoms/link-no-style.tsx, src/components/atoms/link.tsx, src/components/autosuggest-material/autosuggest-material.tsx, src/components/availability-label/availability-label.dev.tsx, src/components/availability-label/availability-label.tsx, src/components/availability-label/availability-labels.tsx, src/components/cover/cover.dev.tsx, src/components/cover/cover.test.ts, src/components/cover/cover.tsx, src/components/horizontal-term-line/HorizontalTermLine.tsx, src/components/material/MaterialDescription.tsx, src/components/material/MaterialHeader.tsx, src/components/material/MaterialMainfestationItem.tsx, src/components/material/ReviewInfomedia.tsx, src/components/material/ReviewMetadata.tsx, src/components/search-result-list/search-result-list-item/search-result-list-item.tsx, src/components/search-result-list/search-result.list.tsx, src/core/store.ts, src/core/url.slice.ts, src/core/utils/helpers/date.ts, src/core/utils/helpers/general.ts, src/core/utils/helpers/url.ts, src/core/utils/text.tsx, src/core/utils/url.tsx, src/core/utils/withSuffix.tsx
https://reload.atlassian.net/browse/DDFSOEG-186
Adds proper url handling at search result
- Adding useUrl concept that avoids prop drilling of urls
- Adding helper for constructing path with query parameters
- Organising global helpers in separate files since they are growing in numbers
=> Linkability fra search result til materialevisning og til search result

.storybook/main.js, package.json, yarn.lock
No issue
Thought we could take advantage of some of the useful stuff the addon-esentials comes with. Eg.: viewport and color. Plus that controls, docs also are included.
=> Replace Storybook addons with addon-esentials

src/apps/loan-list/list/loan-list.dev.tsx, src/apps/loan-list/list/loan-list.entry.tsx, src/apps/loan-list/list/loan-list.tsx
https://platform.dandigbib.org/issues/5387
An empty list
=> 5387: dpl-list-empty added

src/components/autosuggest/autosuggest.tsx, src/components/material/ReviewInfomedia.tsx
Remove imports and props that are no longer used. This addresses issues that are currently popping up on other unrelated PR.
=> Fix checks

package.json
This PR added these 2 to our storybook test command to (start:storybook:test) for a cleaner output in GitHub actions
- --quiet 
- --ci
=> Clean output from cypress

src/apps/material/helper.ts, src/apps/material/material.tsx
In order to get a clearer overview of component
Just a small cleanup suggestion
=> Move work description list data creation to helper

codecov.yml
Add a codecov.yml file with configurations that will make Codecov
less noisy in pull requests.
Most importantly Codecov checks will no longer be marked as failed
when coverage decrease and annotations for missing coverage will no
longer be shown. These can cause doubts for developers who think they
might have missed something and hide issues that must be addressed.
The changes do not show up in this PR. I expect that this is because Codecov runs based on the configuration in the base branch. The changes should take effect once this is merged.
=> Make Codecov less noisy in pull requests

src/components/guarded-app.tsx, src/core/guardedRequests.slice.ts
When the testing phase is done we can remove it. 
It is a complex flow and will help the troubleshooting flow to have it.
=> Leave auth console.debug temporarily

.storybook/preview.js
Why not adding that feature to the Dev Experience™ ? [Loud echo]
=> Add possibility for using user token in env file

src/apps/loan-list/modal/modals.test.tsx
Currently modal tests in our test suite fails. These changes should fix that.
Please read individual commits for more commentary.
=> Fix modal tests

src/apps/demo-modal/demo-modal.tsx, src/apps/loan-list/list/loan-list.tsx, src/apps/loan-list/materials/stackable-material.tsx, src/core/utils/modal.tsx
Instead of repeating the dispatch cmd we can have a small utility hook that makes sure it happens.
=> Add useModalButtonHandler hook

src/apps/material/helper.ts, src/apps/material/material.tsx, src/apps/search-result/search-result.tsx, src/components/availability-label/availability-labels.tsx, src/components/material/MaterialAvailabilityText/MaterialAvailabilityText.tsx, src/components/material/MaterialAvailabilityText/physical/MaterialAvailabilityTextPhysical.tsx, src/components/material/MaterialHeader.tsx, src/components/material/MaterialMainfestationItem.tsx, src/components/material/ReviewExternal.tsx, src/components/material/material-buttons/MaterialButtons.tsx, src/components/material/material-buttons/physical/MaterialButtonsPhysical.tsx, src/components/reservation/reservation-modal.tsx, src/components/search-result-list/search-result-list-item/search-result-list-item-cover.tsx, src/components/search-result-list/search-result-list-item/search-result-list-item.tsx, src/components/search-result-list/search-result.list.tsx, src/core/utils/helpers/general.ts, src/core/utils/types/entities.ts
Cleaning up work and manifestation types and destructing more variables to cleanup code
=> Cleanup types and destruct props

src/components/reservation/reservation-modal.tsx, src/core/dbc-gateway/generated/graphql.schema.json, src/core/dbc-gateway/generated/graphql.tsx
This fixes the braking changes that have been in connection with updating the FBI api
=> Fbi api changes 21sep22

src/components/reservation/UserListItems.tsx, src/components/reservation/forms/ModalReservationFormText.tsx, src/components/reservation/forms/helper.ts, src/core/utils/helpers/general.ts
Improve error handling when saving text in ModalReservationFormText by making use of a promise to handle the various cases.
=> Improved text modal error handling

src/components/find-on-shelf/FindOnShelfModal.tsx
https://reload.atlassian.net/browse/DDFSOEG-224
In this PR we sort find on shelf branch disclosures - showing the main branch first if there is one. 
n/a
=> Feature/find on shelf/main branch first

src/apps/loan-list/modal/renew-loans-modal-content.tsx
https://platform.dandigbib.org/issues/5389
Loan modal pagination
=> 5389: paginate loan modal

README.md
This is quite complex and requires deep insight into GitHub Actions, GitHub NPM package registry and Yarn so lets try to document this better.
=> Document how to use unreleased version of the design system

src/apps/material/material.dev.tsx, src/apps/material/material.entry.tsx, src/core/dpl-cms/mutator/fetcher.ts, src/core/fbs/mutator/fetcher.ts, src/core/publizon/mutator/fetcher.ts, src/core/utils/helpers/fetcher.ts
It has been implemented the same way as it has been done with the FBS and the Publizon fetchers
=> Add support for dpl cms api base url in fetcher

src/apps/loan-list/materials/utils/digital-material-fetch-hoc.tsx, src/apps/loan-list/materials/utils/material-fetch-hoc.tsx, src/core/utils/helpers/list-mapper.ts
It seems the t as argument makes my components re-render and re-render and re-render and re-render and re-render and ...
=> remove use of t as argument in helper

src/apps/material/material.dev.tsx, src/apps/material/material.entry.tsx, src/apps/search-result/search-result.dev.tsx, src/apps/search-result/search-result.entry.tsx, src/components/availability-label/availability-label.dev.tsx, src/components/availability-label/availability-label.test.js, src/components/availability-label/availability-label.tsx, src/components/find-on-shelf/FindOnShelfModal.dev.tsx, src/components/find-on-shelf/FindOnShelfModal.tsx, src/components/material/periodical/MaterialPeriodical.tsx, src/components/reservation/ReservationModalBody.tsx, src/components/reservation/UserListItems.tsx, src/components/reservation/helper.ts, src/core/utils/config.tsx
Because blacklisted branches must not be included in the AvailabilityLabel or FindOnShelfModal accessibility check
=> Exclude blacklistBranches in AvailabilityLabel + FindOnShelfModal

package.json, src/components/material/infomedia/InfomediaModalBody.tsx, yarn.lock
=> Add logo to infomedia modal

src/apps/reservation-list/list/reservation-list.mount.ts, src/apps/reservation-list/list/reservation-list.test.ts
https://platform.dandigbib.org/issues/5403
added a reservation list mount
=> 5401: add reseration list mount

docs/ui_text_handling.md
Correcting documentation typos..
=> Correcting typos in the text documentation

.github/workflows/pages.yml
While we have projects in the development phase we would like to have it updated regularly
=> Build GH storybook from develop

src/components/Dropdown/Dropdown.tsx, src/components/facet-line/FacetLineFilters.tsx, src/components/find-on-shelf/FindOnShelfPeriodicalDropdowns.tsx, src/components/list-details-dropdown/list-details-dropdown.tsx, src/components/reservation/forms/ModalReservationFormSelect.tsx
The changes are made to ensure that the Dropdowns remain consistent and make the code more readable
=> Rewrite code to use the reusable dropdown component (NEW)

src/components/material/material-buttons/helper.ts, src/components/material/material-buttons/online/MaterialButtonsOnline.tsx
DDFSOEG-345
The "Order digital copy" CTA button should only be shown for works that are of the "tidsskriftsartikel" material type, as specified in the project specs.
n/a
n/a
=> Fix order digital copy button

cypress/fixtures/reservation-list/work.json, src/apps/loan-list/list/loan-list.test.tsx, src/apps/loan-list/materials/manifestation.graphql, src/apps/loan-list/modal/modals.test.tsx, src/apps/reservation-list/list/reservation-list-pagination.test.ts, src/apps/reservation-list/modal/delete-reservation/delete-reservation.test.ts, src/core/dbc-gateway/generated/graphql.tsx, src/core/utils/helpers/list-mapper.ts
https://platform.dandigbib.org/issues/5553
I used the wrong year for the materials
=> 5553: change to use the publicationyear

src/apps/loan-list/list/loan-list.entry.tsx, src/apps/loan-list/materials/utils/status-circle-icon.tsx, src/apps/loan-list/materials/utils/status-circle.tsx, src/apps/reservation-list/list/reservation-list.dev.tsx, src/apps/reservation-list/list/reservation-list.entry.tsx, src/apps/reservation-list/reservation-material/reservation-info.tsx, src/apps/reservation-list/reservation-material/reservation-status.tsx
https://platform.dandigbib.org/issues/5541
Remove aria labels
n/a
=> 5541: remove aria labels

src/apps/loan-list/materials/stackable-material/material-status.tsx, src/apps/loan-list/materials/utils/status-circle-icon.tsx
n/a
Removed unused id and aria-hidden forgotten in previous pr
.
=> remove unused id

src/apps/reservation-list/list/reservation-list.test.ts
remove "list-reservation-container" from find
=> use dpl-list-empty instead of list-reservation-container

src/apps/loan-list/list/loan-list.entry.tsx
=> add feesPageUrl to loan list entry

src/apps/patron-page/sections/ContactInfoSection.tsx, src/apps/patron-page/sections/PincodeSection.tsx, src/components/atoms/input/TextInput.tsx
https://platform.dandigbib.org/issues/5398
change classes to match dpl-design-system, and make classnames prop on textinput an or instead of and. 
n/a
=> 5398: change classes

src/core/mount.js
https://reload.atlassian.net/browse/DDFSOEG-391
This PR enables us to render initial app html serrver side and then re-render it when React mounts.
=> Allow hydration of app mounts

src/apps/material/login-redirect.test.ts, src/apps/material/periodical.test.ts, src/components/material/material-buttons/physical/MaterialButtonPhysical.tsx
[DSC-9](https://reload.atlassian.net/browse/DSC-9)
This PR adds our already developed prompt-for-login functionality to the reservation button for physical materials.
n/a
-
=> Promt for login when ordering physical materials

src/apps/loan-list/modal/renew-loans-modal-content.tsx
https://platform.dandigbib.org/issues/5569
Instead of using how many that are renewable, the button now reflects the materials selected for renewal
=> 5569: renewable value should change

src/apps/loan-list/list/loan-list-items.tsx, src/apps/loan-list/materials/stackable-material/stackable-material.tsx
https://platform.dandigbib.org/issues/5600
Simplify the additional materials on stackable material ("+3 materials "link)
=> 5600: change additional materials on stacked material

src/components/date-inputs/date-inputs.tsx, src/core/utils/helpers/date.ts
n/a
add date has passed so the user cannot pick a "to" date that has already occurred
=> add date has passed to reservations

src/apps/reservation-list/list/list.tsx, src/apps/reservation-list/list/reservation-list-pagination.test.ts
https://platform.dandigbib.org/issues/5627
Move pager so it is not inside the ul
=> 5627: move pager

package.json, src/components/material/infomedia/InfomediaModalBody.tsx, src/components/search-result-list/search-result-list-item/search-result-list-item.tsx, yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-408
https://reload.atlassian.net/browse/DDFSOEG-409
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/194
=> Remove default spacing in article + Add spacing in infomedia

src/components/facet-browser/helper.ts
The search result and  facetbrowsermodal component is rerendering infinetely. This fixes the bug.
=> Fix useGetFacets re-render bug

cypress/fixtures/search-header-data.json, src/apps/material/material.dev.tsx, src/apps/search-header/search-header.test.ts, src/components/autosuggest-material/autosuggest-material.tsx, src/components/autosuggest/autosuggest.graphql, src/components/cover/cover-image.tsx, src/components/cover/cover.tsx, src/components/facet-browser/helper.ts, src/components/material/MaterialHeader.tsx, src/core/dbc-gateway/generated/graphql.schema.json, src/core/dbc-gateway/generated/graphql.tsx
https://reload.atlassian.net/browse/DSC-20
Refactor the Cover component to handle different aspect ratios. This will improve the component's flexibility and ensure that it aligns with the latest design https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/186.
=> Scaling of covers

cypress.json, vitest.config.ts
This PR solves the missing Cypress coverage problem by being specific about which Cypress files to include.
By doing that  we also automatically exclude Vitest files.
Second commit is due to a ts warning about the construction of the vitest config.
=> Cypress coverage fix

src/components/availability-label/availability-label.tsx
https://reload.atlassian.net/browse/DDFSOEG-430
The npm package (dpl-design-system) that we use for styling our react apps was updated recently. These changes require us to adjust some of the class names for the availability label component. 
n/a
Connected PR with the package changes - https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/203
=> Fix availability label accessibility

package.json, src/apps/material/periodical.test.ts, yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-465
https://reload.atlassian.net/browse/DDFSOEG-462
https://reload.atlassian.net/browse/DDFSOEG-471
This PR updates dpl-design-system package which fixed following:
- Autosuggest wrapping on phones 
- A problem where on iPhones the users would have to click the search suggestion twice in order to select it
Problem:
Solution:
n/a
=> Update dpl-design-system package (autosuggest mobile wrapping)

src/components/blocked-patron/blocked-modal/BlockedModal.tsx
N/A
Update link import path in blockedmodal
N/A
=> update link import path in blockedmodal

src/components/cover/cover.tsx, src/components/reservation/forms/ModalReservationFormText.tsx, src/components/reservation/useAlternativeAvailableManifestation.ts, src/core/storybook/serviceUrlArgs.ts
This pull request includes the following changes:
- Made changes to `ModalReservationFormText`, `useAlternativeAvailableManifestation`, `ModalReservationFormText` and `handleSetImageLoaded` to improve performance.
=> Update Publizon URL + Refactor components to avoid re-renders

src/apps/material/material.test.ts, src/components/availability-label/availability-label.tsx
https://reload.atlassian.net/browse/DDFSOEG-437
https://reload.atlassian.net/browse/DDFSOEG-449
it replacing the container 'div with type="button"' with either an outside `LinkNoStyle` or `button`. This change ensures that the AvailabilityLabel component is semantically correct and prevents double tabbing when navigating with the keyboard on the search-result page.
=> Improve Accessibility in `AvailabilityLabel`

src/core/utils/withIsPatronBlockedHoc.tsx
n/a
to avoid the "bad setState()"-error in console
=> ITKDEV - Add null to blockedFromViewingContent

src/apps/loan-list/modal/due-date-loans-modal.tsx, src/apps/loan-list/modal/renew-loans-modal.tsx, src/apps/reservation-list/modal/delete-reservation/delete-reservation-content.tsx, src/apps/reservation-list/modal/delete-reservation/delete-reservation.test.ts, src/apps/reservation-list/modal/pause-reservation/pause-reservation.tsx, src/components/blocked-patron/blocked-modal/BlockedModal.tsx
https://platform.dandigbib.org/issues/5671
Change h1's to h2's in modal 
not necessary
=> ITKDev - 5671 - Change h1 to h2 in modals

src/apps/dashboard/modal/ready-for-loan-modal/ready-to-loan-item.tsx, src/apps/intermediate-list/stackable-fees/stackable-fees-list.tsx, src/apps/loan-list/materials/selectable-material/StatusMessage.tsx, src/apps/loan-list/materials/selectable-material/selectable-material.tsx
https://platform.dandigbib.org/issues/5593
Update group modal classes, as per https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/224
n/a
=> ITKdev - 5593 - Status message mobile/desktop

src/apps/patron-page/sections/BasicDetailsSection.tsx, src/apps/patron-page/sections/ContactInfoSection.tsx, src/apps/patron-page/sections/PincodeSection.tsx, src/apps/patron-page/sections/ReservationDetailsSection.tsx, src/apps/patron-page/sections/StatusSection.tsx
https://platform.dandigbib.org/issues/5759
https://platform.dandigbib.org/issues/5691
Change look of headers on patron page
Change header tags on patron page
And so fourth...
=> CMN-599: update headers on patron page

src/apps/menu/menu-logged-in/menu-logged-in.tsx, src/apps/menu/menu-not-logged-in/menu-not-logged-in.tsx, src/apps/menu/menu.dev.tsx, src/apps/menu/menu.entry.tsx, src/apps/menu/menu.tsx, src/core/configuration/modal-ids.json
https://platform.dandigbib.org/issues/5716
Made modal accessible by using the accessible modal component. Removed some todos that i reckon is done. added strings, added modalids. 
=> itkdev:  use modal for user menu

src/apps/search-result/search-result-skeleton.tsx, src/apps/search-result/search-result-zero-hits.tsx, src/components/find-on-shelf/FindOnShelfModal.tsx, src/components/find-on-shelf/FindOnShelfModalBody.tsx
https://reload.atlassian.net/browse/DDFSOEG-505
Prevent findOnShelfModal reuqests om material page
by only requesting when the modal is open
=> Prevent findOnShelfModal reuqests om material page

src/apps/search-result/search-result-skeleton.tsx, src/apps/search-result/search-result-zero-hits.tsx
Changing wrong search result classes in skeleton screens
=> Changing wrong search result classes

src/apps/material/material.dev.tsx, src/apps/material/material.entry.tsx, src/apps/reservation-list/list/reservation-list.dev.tsx, src/apps/reservation-list/list/reservation-list.entry.tsx, src/apps/reservation-list/modal/reservation-details/physical-list-details.tsx, src/components/reservation/UserListItems.tsx, src/components/reservation/forms/NoInterestAfterModal.tsx, src/components/reservation/helper.ts
n/a
Change interestperiods to look like thresholdperiod and branchesconfig, a similar pr will be created in dpl-cms
n/a
=> itkdev: interest period changed to config

src/apps/loan-list/materials/manifestation.graphql, src/apps/loan-list/materials/selectable-material/selectable-material.tsx, src/apps/loan-list/materials/stackable-material/material-info.tsx, src/core/dbc-gateway/generated/graphql.schema.json, src/core/dbc-gateway/generated/graphql.tsx, src/core/utils/helpers/list-mapper.ts, src/core/utils/types/basic-details-type.ts
https://platform.dandigbib.org/issues/5666
Please include a short description of the suggested change and the reasoning behind the approach you have chosen.
=> ITKDEV - 5666 - language codes

src/apps/favorites-list-material-component/FavoritesListMaterialComponent.dev.tsx, src/apps/material/material.dev.tsx, src/apps/material/material.test.ts, src/apps/recommender/Recommender.dev.tsx, src/apps/search-result/search-result.dev.tsx, src/apps/search-result/search-result.test.ts, src/apps/something-similar/SomethingSimilar.dev.tsx, src/components/button-favourite/button-favourite.dev.tsx, src/components/button-favourite/button-favourite.test.ts, src/components/button-favourite/button-favourite.tsx, src/components/card-item-list/card-list-item/card-list-item.tsx, src/components/material/MaterialHeader.tsx, src/components/simple-material/SimpleMaterial.tsx
https://platform.dandigbib.org/issues/5786
Make aria-label more specific
=> itkdev: 5786: make aria label more specific

src/apps/fee-list/stackable-fees/fee-status.tsx
https://platform.dandigbib.org/issues/5794
Remove duplicate (and unused) id.
=> Itkdev: 5794: remove id

src/core/dbc-gateway/generated/graphql.schema.json, src/core/dbc-gateway/generated/graphql.tsx
n/a
This PR updates the client for FBI API.
n/a
n/a
=> Update FBI API schema (dbc gateway)

package.json, src/components/availability-label/availability-label-inside.tsx, src/components/pagefold/Pagefold.tsx, yarn.lock
This PR reflects changes in https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/209
=> Reflect css changes from dpl-design-system/pull/209

src/apps/dashboard/dashboard-notification-list/NotificationColumn.tsx, src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx, src/apps/dashboard/dashboard.dev.tsx, src/apps/dashboard/dashboard.entry.tsx, src/apps/menu/menu.dev.tsx, src/apps/menu/menu.entry.tsx, src/apps/reservation-list/list/reservation-list.dev.tsx, src/apps/reservation-list/list/reservation-list.entry.tsx, src/apps/reservation-list/reservation-material/reservation-info.tsx, src/apps/reservation-list/reservation-material/reservation-status.tsx, src/apps/something-similar/SomethingSimilarList.tsx, src/components/contact-info-section/ContactInfoSection.tsx, src/core/storybook/reservationGroupModalArgs.ts, src/core/storybook/reservationMaterialDetailsArgs.ts
n/a
Correct error with switched logic 
added some missing props to menu
add styling classes to "something similar"
=> itkdev: switch logic on contact info section

src/apps/dashboard/modal/ReservationsGroupModal.tsx, src/components/GroupModal/GroupModalContent.tsx
n/a
move some divs around before test
n/a 
n/a
=> itkdev: move divs around

package.json, src/components/atoms/links/Link.tsx, src/components/atoms/links/getLinkHandler.ts, src/components/atoms/links/handleTracking.ts, src/components/atoms/links/helpers.ts, src/components/card-item-list/card-list-item/card-list-item.tsx, src/core/utils/helpers/url.ts, src/tests/unit/linkTracking.test.tsx, yarn.lock
https://reload.atlassian.net/browse/DDFSOEG-484
This PR Added `stopPropagation()` to the `Link` component to prevent onClick and onKeyUp events from bubbling up and triggering parent functions, thereby enhancing encapsulation and reducing unexpected behaviors.
=> Implement `stopPropagation()` in `Link` component

src/components/cover/cover.tsx
Correct unclear id type fallback in cover component.
=> Correct unclear id type fallback

src/apps/loan-list/list/loan-list-items.tsx, src/apps/loan-list/materials/stackable-material/stackable-material.tsx, src/components/GroupModal/GroupModalContent.tsx
n/a
Replace faust with loanId, so modal opens (I did this before, I suspect I made a mistake during a rebase)
And refactored group modal checkbox code, to remove duplicate checkbox
n/a 
N/a
=> itkdev: replace faust with loanId

src/core/utils/helpers/list-mapper.ts
n/a
Do not just show reserved reservations (as we were previously told), but all reservations.
n/a
n/a
=> itkdev: show all reservation types

src/apps/dashboard/modal/ReservationsGroupModal.tsx, src/components/GroupModal/GroupModalReservationsList.tsx
https://platform.dandigbib.org/issues/5752
https://platform.dandigbib.org/issues/5861
Make it possible to delete reservations 
n/a
n/a
=> 5752: make possible to delete reservations

src/core/utils/helpers/general.ts
Since prefix is required there is no need for checking it. Add test that proves it works.
=> Simplifying modal id creation

src/apps/reservation-list/modal/reservation-details/physical-list-details.tsx
https://platform.dandigbib.org/issues/5830
This should be from today not from prev interested after date 
n/a
n/a
=> 5830: interested after period from today

src/apps/loan-list/modal/material-details.tsx, src/apps/loan-list/modal/renew-button.tsx, src/core/storybook/materialDetailsModalArgs.ts
[Please add a link to the issue being addressed by this change.](https://platform.dandigbib.org/issues/5888)
Corrected how the renew button is shown, and correcting it's classes to properly address the design.
=> 5888: showing renew button on loan detail screen

src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx, src/apps/dashboard/modal/ReservationsGroupModal.tsx, src/apps/reservation-list/list/reservation-list.tsx, src/apps/reservation-list/modal/delete-reservation/delete-reservation-content.tsx, src/apps/reservation-list/modal/delete-reservation/delete-reservation-modal.tsx, src/apps/reservation-list/modal/delete-reservation/delete-reservation.test.ts, src/components/GroupModal/GroupModalReservationsList.tsx, src/core/configuration/modal-ids.json
https://platform.dandigbib.org/issues/5882
Consolidate some functionality
=> 5882: streamline remove reservations

src/apps/menu/menu.tsx
https://platform.dandigbib.org/issues/5813
cursor pointer on icon
=> 5813: added styling class

src/apps/reservation-list/modal/reservation-details/physical-list-details.tsx
https://platform.dandigbib.org/issues/5904
select default: "Pick"
n/a
=> 5904: select default is pick

src/apps/loan-list/list/loan-list.dev.tsx, src/apps/loan-list/list/loan-list.tsx, src/apps/loan-list/modal/modals.test.tsx, src/apps/reservation-list/list/reservation-list.dev.tsx, src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts, src/core/utils/helpers/modal-helpers.ts
https://platform.dandigbib.org/issues/5919
Remove code that double-opens modal
=> 5919: remove double opening of modal

.github/workflows/tests.yml, src/components/card-item-list/card-list-item/card-list-item.tsx, src/components/subject-number/SubjectNumber.tsx
https://reload.atlassian.net/browse/DDFSOEG-549
Adds a subject line to search results that are non fictional.
=> Subject line on search results

graphql.config.json, package.json, src/core/dbc-gateway/generated/graphql.schema.json, src/core/dbc-gateway/generated/graphql.tsx
Bringing FBI API integration more up to date by making sure that the next profile is used everywhere, and adding updated generated code from FBI API.
=> Update fbi profile plus generated code

docs/architecture/README.md, docs/architecture/adr-001-rehydration.md, docs/architecture/adr-002-ui-text-handling.md, docs/architecture/adr-003-downshift.md, docs/architecture/adr-004-relative-ci.md, docs/architecture/adr-005-react-use.md, docs/architecture/adr-006-unit-tests.md, docs/architecture/adr-007-configuration.md
https://reload.atlassian.net/browse/DDFSOEG-558
This documents our decisions regarding how to manage responsibilities for providing correct configuration between React and Drupal.
It also updates other ADRs to improve their presentation [on the documentation site](https://danskernesdigitalebibliotek.github.io/dpl-docs/dpl-react/). If you disagree about that part I can leave it out.
=> ADR: Config handling

.env.example, .eslintrc, package.json, src/core/storybook/serviceUrlArgs.ts, webpack.config.js, webpack.helpers.js, yarn.lock
We will get tired of remembering to add it to storybook args and be careful not commit the mocked services. In the future we can handle other environment variables for other purposes as well.
=> Add possibility to define service urls in .env

src/components/card-item-list/card-list-item/card-list-item.tsx
https://reload.atlassian.net/browse/DDFSOEG-549
The wrong object (work) was passed to materialIsFiction(). The bestRepresentation manifestation has the information.
=> Fix bug with subject number showing on all search results

.vscode.example/dpl-react.code-snippets
Makes it easier to get up running fast
=> Use component file name as name of component

package.json, src/apps/fee-list/fee-list.test.ts, src/apps/loan-list/list/ToggleListViewButtons.tsx, src/components/GroupModal/GroupModalContent.tsx, yarn.lock
https://reload.atlassian.net/browse/DDFLSBP-57
Adding new sticky mobile button on loan page
And refactoring classes that was changes in order to make them more generic.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/998889/e56115bf-b406-43d3-953f-9f01e81fa628
[This PR](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/332) needs to be merged first.
Then the npm reference to the design system has to be updated.
=> Adding new sticky mobile button on loan page

src/core/utils/helpers/vitest.ts, src/core/utils/modal.tsx
https://reload.atlassian.net/browse/DDFSOEG-585
Added checks to ensure safe access to `process.env`, addressing environments where it might be undefined.
=> Fix `ReferenceError: process is not defined`

src/apps/menu/menu-logged-in/MenuLoggedInContent.tsx, src/apps/menu/menu.dev.tsx, src/apps/menu/menu.entry.tsx
https://reload.atlassian.net/browse/DDFLSBP-237
Create clear difference between what is dashboard and what is user profile links.
=> Create clear difference between what is dashboard and what is user profile links

.storybook/webpack.config.js, webpack.config.js
For whatever reason this comes up as a problem when using dapple. It does not seem to make a difference in other situations so we might as well add it.
=> Move webpack loaders for CSS files

src/apps/reservation-list/modal/reservation-details/reservation-details.tsx
https://reload.atlassian.net/browse/DDFLSBP-323
This was a mishap that was born out of merge conflict resolution. 
n/a
=> Don't render CTA row for digital reservations twice

src/apps/reservation-list/modal/delete-reservation/delete-reservation-modal.tsx, src/apps/reservation-list/modal/delete-reservation/helper.ts, src/core/utils/useRequestsWithStatus.tsx
https://reload.atlassian.net/browse/DDFLSBP-99
Set more precise types on requestsAndReservations
`requests`was not inferred correctly.
=> More precise types on requests and reservations

src/apps/reservation-list/modal/delete-reservation/delete-reservation-modal.tsx
Make sure to invalidate BOTH digital and physical reservations when deleting them.
=> Invalidate BOTH digital and physical reservations upon deletion

src/apps/fee-list/FeeList.tsx
https://reload.atlassian.net/browse/DDFLSBP-310
At some point it was decided to hide the whole page when any modal was open.
This gives some weird behavior when opening non-full screen modals like the menu. We don't want to hide the page.
=> Don't hide fee list page

.github/workflows/create-release-on-branch-changes.yml, .github/workflows/create-release-on-tag.yml
Otherwise the zip step fails on branches/tags with "/" in it.
=> Sluggify branch/tag name

src/components/description-list/description-list.tsx
Reflecting Changes in: https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/365
This pull request is to align the markup in dpl-react with the changes in the design system
=> Update `DescriptionList` with BEM Classes

src/components/contact-info-section/ContactInfoPhone.tsx
https://reload.atlassian.net/browse/DDFLSBP-249
Removed input placeholder text
=> Removed placeholder for mobile input

cypress/support/index.ts, src/apps/dashboard/dashboard.test.tsx, src/apps/favorites-list/favorites-list.test.ts, src/apps/fee-list/fee-list.test.ts, src/apps/loan-list/list/loan-list.test.ts, src/apps/loan-list/modal/modals.test.tsx, src/apps/reservation-list/list/reservation-list-pagination.test.ts, src/apps/reservation-list/list/reservation-list.test.ts, src/apps/reservation-list/modal/delete-reservation/delete-reservation.test.ts, src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts, src/apps/search-header/search-header.test.ts, src/apps/search-result/search-result.test.ts, src/core/dbc-gateway/graphql-fetcher.ts, src/core/dbc-gateway/helper.ts, src/core/dbc-gateway/queryMap.ts, src/core/storybook/serviceUrlArgs.ts, src/core/utils/reduxMiddleware/extractServiceBaseUrls.ts, src/core/utils/types/global-url-props.ts
https://reload.atlassian.net/browse/DDFLSBP-318
In that way we can change FBI graphql url depending on which query that is being executed.
We need that because DDF wants to change profile name depending on which query that is being run.
Is connected to [this PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/581).
=> Expanding fetching system for FBI to handle multiple urls

src/apps/fee-list/FeeList.dev.tsx, src/apps/fee-list/FeeList.entry.tsx, src/apps/fee-list/FeeList.tsx, src/apps/fee-list/list.tsx, src/apps/fee-list/utils/helper.ts
https://reload.atlassian.net/browse/DDFLSBP-332
The fee list needs to be divided into two separate list each with their own headline, and total. As a part of this two texts were redefined, so I'm changing their definition in [this PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/632) in the CMS as well.
-
-
=> Divide fees into payable and nonpayable by the client

src/apps/menu/menu-navigation-list/MenuNavigationItem.tsx, src/apps/menu/menu.dev.tsx, src/apps/menu/menu.test.ts
https://reload.atlassian.net/browse/DDFLSBP-366
Adjust patron storybook menu to reflect harcoded conf in dpl-cms
=> Adjust patron storybook menu to reflect harcoded conf in dpl-cms

src/apps/reservation-list/modal/reservation-details/reservation-details-redirect.tsx, src/apps/reservation-list/modal/reservation-details/reservation-details.test.ts
Merging develop into the release branch after fast tracking [this task](https://reload.atlassian.net/browse/DDFLSBP-344).
=> Merge develop into release 2024 05 0

.storybook/dev-fonts.scss, .storybook/preview.js, package.json, src/apps/fee-list/FeeList.dev.tsx, src/apps/fee-list/FeeList.entry.tsx, src/apps/fee-list/FeeList.tsx, src/apps/fee-list/FeePaymentButton.tsx, src/apps/fee-list/fee-list.test.ts, src/apps/fee-list/list.tsx, src/apps/fee-list/modal/my-payment-overview-modal.tsx, src/components/list-header/list-header.tsx, yarn.lock
https://reload.atlassian.net/browse/DDFLSBP-368
These changes:
* Adds a fee payment button if url has been defined
* Removes a reference to a dev font sass file which I do not see the need for.
=> Button for paying fees in header on /user/me/fees page

.github/workflows/create-release-on-branch-changes.yml, .github/workflows/create-release-on-tag.yml
In order to try to avoid 403 on design system npm download.
https://reload.zulipchat.com/#narrow/stream/240325-DDF/topic/GH.20workflow.3A.20New.20release.20on.20branch.20changes.20-.20flaky
=> Add NODE_AUTH_TOKEN

src/components/reservation/forms/ModalReservationFormSelect.tsx
https://reload.atlassian.net/browse/DDFLSBP-240
Center reservation detail feedback content in the modal
-
=> Center reservation detail feedback content in the modal

package.json, yarn.lock
https://reload.atlassian.net/browse/DDFLSBP-388
Updates design system package to have [these changes](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/451).
https://github.com/danskernesdigitalebibliotek/dpl-design-system/assets/28546954/690a07a9-aa3a-41e7-81cc-1034ade7b979
-
=> Update dpl-design-system-package to have arrow hover unification changes

package.json, yarn.lock
Update dpl-design-system package for latest release
=> Use release 2024.5.0 of design system

cypress/fixtures/recommendation/fbi-api.json, src/apps/fee-list/stackable-fees/fee-info.tsx, src/apps/loan-list/materials/stackable-material/material-info.tsx, src/apps/recommendation/RecommendationSkeleton.tsx, src/apps/recommendation/recommendation.dev.tsx, src/apps/recommendation/recommendation.entry.tsx, src/apps/recommendation/recommendation.mount.ts, src/apps/recommendation/recommendation.test.tsx, src/apps/recommendation/recommendation.tsx, src/apps/recommended-material/RecommendedMaterial.dev.tsx, src/apps/recommended-material/RecommendedMaterial.entry.tsx, src/apps/recommended-material/RecommendedMaterial.mount.ts, src/apps/recommended-material/RecommendedMaterial.tsx, src/apps/recommended-material/RecommendedMaterialSkeleton.tsx, src/apps/recommended-material/recommended-material.test.tsx, src/components/autosuggest-material/autosuggest-material.tsx, src/components/card-item-list/card-list-item/card-list-item-cover.tsx, src/components/cover/cover-image.tsx, src/components/cover/cover.dev.tsx, src/components/cover/cover.test.ts, src/components/cover/cover.tsx, src/components/material/MaterialHeader.tsx, src/components/modal-details-header/modal-details-header.tsx, src/core/utils/types/ids.ts
[Jira link](https://reload.atlassian.net/jira/software/c/projects/DDFFORM/boards/485?selectedIssue=DDFFORM-128)
The PR refactors two things, in addition to the apps mentioned below: 
- Refactor "shadow" prop on <Cover/> component to match changes in the design system. 
- Rewrite prop "description" to "alt" to match changes in the design system. 
This PR adds two react apps. 
- RecommendedMaterial for showing a "spotlight" of a material with cover, favourite toggle, description and author. 
- Recommendation for showing spotlight of a material with title, and description (Abstract), and including the RecommendedMaterial spotlight. 
At the time of implementing these, the "Recommendation" component will not be used as it is in the CMS. Only the recommendedMaterial will be used since the first …
=> DDFFORM 128

.github/workflows/create-release-on-branch-changes.yml, .github/workflows/create-release-on-tag.yml
We have continuously experienced the install failing because of problems downloading design system. Hopefully it helps retrying...
=> Retry yarn install if it fails in release workflows

src/components/GroupModal/LoansGroupModal.tsx
https://reload.atlassian.net/browse/DDFLSBP-407
When renewing loans - use loanIds to send to the service. We were sending nothing before.
-
-
=> Fix loan renewal error

.storybook/preview.js, package.json, src/apps/loan-list/list/ListHeader.tsx, src/apps/loan-list/materials/utils/digital-material-fetch-hoc.tsx, src/apps/loan-list/materials/utils/material-fetch-hoc.tsx, src/apps/reservation-list/list/list.tsx, src/apps/reservation-list/list/reservation-list-skeleton.tsx, src/apps/reservation-list/list/reservation-list.test.ts, src/apps/reservation-list/list/reservation-list.tsx, src/apps/reservation-list/reservation-material/reservation-material-skeleton.tsx, src/apps/reservation-list/reservation-material/reservation-material.tsx, yarn.lock
https://reload.atlassian.net/browse/DDFLSBP-397
This PR adds skeleton screens to the reservation page when it's loading.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/28546954/5ec80676-ba3c-42d5-8155-2ccd3d83b8e1
This PR needs its dpl-design-system dependency updated when [THIS PR](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/468) is merged in
=> Add reservation page skeleton screens

src/apps/patron-page/PatronPage.tsx, src/apps/patron-page/sections/PincodeSection.tsx, src/apps/patron-page/sections/ReservationDetailsSection.tsx, src/apps/patron-page/sections/StatusSection.tsx, src/components/contact-info-section/ContactInfoSection.tsx
https://reload.atlassian.net/browse/DDFLSBP-424
This PR removes the "pause your reservations" section from the patron page. 
Changes to spacing between sections have also been made to reflect Figma design.
-
-
=> Remove pause reservations from user profile

src/components/GroupModal/LoansGroupModal.tsx
Add chery-picked commit that fixes loan renewals
=> When renewing loans - use loanIds to send to the service

package.json, src/apps/fee-list/stackable-fees/stackable-fees-list.tsx, src/apps/loan-list/materials/selectable-material/selectable-material.tsx, yarn.lock
https://reload.atlassian.net/browse/DDFLSBP-340
This PR adds drop shadow on hover for group modal items + removes them from the fee list as the items there are not interactive.
(hovering over the highlighted item)
[Sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/495)
=> Add shadow to group modal items

src/components/date-inputs/DateRangeInput.tsx
https://reload.atlassian.net/browse/DDFLSBP-445
Show date formats for pause period as day. MONTHNAME year
-
=> Show date range in danish format

package.json, src/apps/dashboard/dashboard-notification-list/NotificationColumn.tsx, src/apps/dashboard/dashboard-notification-list/Notifications.tsx, src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx, src/apps/dashboard/dashboard-notification/notification-skeleton.tsx, src/apps/loan-list/materials/selectable-material/selectable-material-skeleton.tsx, src/apps/loan-list/materials/selectable-material/selectable-material.tsx, src/apps/reservation-list/list/reservation-list.dev.tsx, src/apps/reservation-list/list/reservation-list.entry.tsx, src/core/storybook/globalTextArgs.ts, yarn.lock
https://reload.atlassian.net/browse/DDFLSBP-428
This PR implements reservation group modal + loan group modal loading skeletons & dashboard + user menu list item skeletons.
-
[Sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/489)
=> Group modal card skeletons

src/components/search-bar/story-header.dev.inc.tsx
- Update story-header.dev markup to match new header-sidebar-nav
[DDFFORM-222](https://reload.atlassian.net/browse/DDFFORM-222)
- Design system PR: https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/503
- CMS PR: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/769
This PR updates the markup relevant for the header-sidebar-nav  / new burgermenu. 
See design system PR for image.
=> DDFFORM 222

src/apps/loan-list/modal/renew-button.tsx, src/components/GroupModal/LoansGroupModal.tsx, src/components/button-favourite/button-favourite.tsx, src/core/statistics/statistics.ts
https://reload.atlassian.net/browse/DDFLSBP-54
This PR introduces Mapp tracking to the LSBP project. 
You can see an overview of all tracking wishes from DDF in [this document](https://docs.google.com/spreadsheets/d/1EGxTxnGP664U2MMi2zn1bgWjChM8r9J3/edit#gid=412821441). Only three of them are implementable in React - all these are present in this PR (IDs 55, 56, 61)
-
-
=> Setup statistics lsbp

src/apps/create-patron-user-info/CreatePatron.dev.tsx, src/apps/create-patron-user-info/CreatePatron.entry.tsx, src/apps/create-patron-user-info/CreatePatron.tsx, src/apps/create-patron-user-info/UserInfo.tsx, src/apps/dashboard/dashboard-fees/dashboard-fees.tsx, src/apps/material/material.tsx, src/apps/menu/menu-logged-in/MenuLoggedInContent.tsx, src/apps/menu/menu-user-unregistered/MenuUserUnregisteredContent.tsx, src/apps/menu/menu-user-unregistered/menu-user-unregistered.tsx, src/apps/menu/menu.tsx, src/apps/patron-page/PatronPage.tsx, src/apps/reservation-list/list/reservation-list.tsx, src/components/material/digital-modal/DigitalModal.tsx, src/components/material/infomedia/InfomediaModal.tsx, src/components/material/material-buttons/online/MaterialButtonOnlineDigitalArticle.tsx, src/components/material/material-buttons/online/MaterialButtonOnlineInfomediaArticle.tsx, src/components/material/material-buttons/physical/MaterialButtonsPhysical.tsx, src/components/reservation/ReservationModalBody.tsx, src/core/adgangsplatformen/fetcher.ts, src/core/adgangsplatformen/useUserInfo.ts, src/core/configuration/modal-ids.json, src/core/fbs/mutator/fetcher.ts, src/core/token.js, src/core/utils/helpers/usePatronData.ts, src/core/utils/helpers/user.ts, src/core/utils/useGetReservationGroups.ts, src/core/utils/useLoans.tsx, src/core/utils/withIsPatronBlockedHoc.tsx
https://reload.atlassian.net/browse/DDFLSBP-403
This PR introduces the concept of identifying if a user is unregistered. Which means that the user has not registered via the register formular.
The PR is dependant on the work that has been done in [this PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/760).
=> Handling of unregistered users

package.json, src/apps/favorites-list/FavoritesList.tsx, src/components/button-favourite/button-favourite.tsx, src/core/material-list-api/material-list.ts, src/core/storybook/globalTextArgs.ts, yarn.lock
https://reload.atlassian.net/browse/DDFLSBP-112
This PR fixes an issue where items wouldn't get removed from the "favorite list" upon clicking on the heart icon unless the user refreshed their browser.
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/28546954/a6abbc09-6737-4803-9185-d1b1a9a176c7
-
=> Fix favorites list not removing items

src/apps/advanced-search/AdvancedSearch.dev.tsx, src/apps/create-patron-user-info/CreatePatron.dev.tsx, src/apps/dashboard/dashboard.dev.tsx, src/apps/dashboard/dashboard.tsx, src/apps/favorites-list-material-component/FavoritesListMaterialComponent.dev.tsx, src/apps/favorites-list/FavoritesList.dev.tsx, src/apps/fee-list/FeeList.dev.tsx, src/apps/material/material.dev.tsx, src/apps/menu/menu.dev.tsx, src/apps/patron-page/PatronPage.dev.tsx, src/apps/recommender/Recommender.dev.tsx, src/apps/search-header/search-header.dev.tsx, src/apps/search-result/search-result.dev.tsx, src/apps/something-similar/SomethingSimilar.dev.tsx, src/components/availability-label/availability-label.dev.tsx, src/components/button-favourite/button-favourite.dev.tsx, src/components/cover/cover.dev.tsx, src/components/error-boundary-alert/ErrorBoundaryAlert.tsx, src/components/find-on-shelf/FindOnShelfModal.dev.tsx, src/components/hello/hello.dev.tsx, src/components/multiselect/Multiselect.dev.tsx, src/components/search-bar/search-bar.dev.tsx, src/core/storybook/globalConfigArgs.ts
https://reload.atlassian.net/browse/DDFLSBP-448
This PR changes the Error boundary alert to be shown in a portal container delivered by the hosting system (dpl-cms)
=> Show error boundary error in a portal

src/core/material-list-api/mutator/fetcher.ts
https://reload.atlassian.net/browse/DDFLSBP-416
Favorites functionality encountered issues on iOS due to an error being thrown of an unexpected type. We have now added a condition to parse the JSON payload exclusively for GET requests. Additionally, detailed error messages have been introduced to improve clarity around JSON parsing failures.
*
*
=> Fix favorites functionality on iOS [DDFLSBP-416]

package.json, yarn.lock
update design system package to v 2024.11.1
=> Update design system package to version 2024.11.1

src/core/utils/modal.tsx
https://reload.atlassian.net/browse/DDFLSBP-392
Remove query parameters from url if it doesn't match any modals and reenable scrolling on the site.
-
-
=> Fix dashboard disappearing modals

src/apps/recommended-material/RecommendedMaterial.tsx, src/components/card-item-list/card-list-item/card-list-item.tsx, src/components/material/MaterialHeader.tsx, src/components/simple-material/SimpleMaterial.tsx, src/core/guardedRequests.slice.ts, src/core/material-list-api/material-list.ts
https://reload.atlassian.net/browse/DDFLSBP-112
Ensure the Favorites list is updated when materials are added or removed.
*
*
=> Ensure the Favorites list is updated when materials are added or removed [DDFLSBP-112]

src/components/availability-label/availability-label.tsx
https://reload.atlassian.net/browse/DDFLSBP-494
Articles should always show as available.
-
-
=> Make articles always show as available in availability labels

src/apps/opening-hours/OpeningHourWeekList.tsx, src/apps/opening-hours/OpeningHours.tsx
Add Cypress attributes for testing purposes
=> Add Cypress attributes for testing purposes

src/components/facet-browser/__snapshots__/helper.ts.snap, src/components/facet-browser/helper.ts
https://reload.atlassian.net/browse/DDFLSBP-520
Reordering the sequence of filters in the 'More filters' section for advanced search.
*
=> Reordering the advanced search filters

.github/dependabot.yml
Packages within the Testing library and Fullcalendar projects may be updated about the
same time.
Group them to make them move in parallel.
=> More dependabot groups

src/apps/fee-list/stackable-fees/fee-info.tsx, src/apps/loan-list/materials/stackable-material/material-info.tsx, src/apps/material/helper.ts, src/apps/material/material.tsx, src/apps/recommended-material/RecommendedMaterial.tsx, src/components/autosuggest-material/autosuggest-material.tsx, src/components/autosuggest/autosuggest.graphql, src/components/card-item-list/card-list-item/card-list-item-cover.tsx, src/components/card-item-list/card-list-item/card-list-item.tsx, src/components/cover/cover.tsx, src/components/cover/helper.ts, src/components/instant-loan/InstantLoanSummary.tsx, src/components/material/MaterialHeader.tsx, src/components/material/MaterialMainfestationItem.tsx, src/components/modal-details-header/modal-details-header.tsx, src/components/reservation/ReservationModalBody.tsx, src/components/simple-material/SimpleMaterial.tsx, src/core/cover-service-api/mutator/fetcher.ts, src/core/dbc-gateway/generated/graphql.schema.json, src/core/dbc-gateway/generated/graphql.tsx, src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFLSBP-536
This PR makes sure that we have a higher probability for getting a cover url in various places in our applications.
* Several pids are being sent at the same time to the cover service
* If we can find the best representation cover we'll use that otherwise we try to pick the first available cover
=> Improved cover url resolving

src/apps/material-grid/automatic/MaterialGridAutomatic.dev.tsx, src/apps/material-grid/manual/MaterialGridManual.dev.tsx, src/apps/recommended-material/RecommendedMaterial.tsx
- **Add story-book skeleton for materialgrid & use CLSX in recommended-material.**
[DDFFORM-490](https://reload.atlassian.net/browse/DDFFORM-490)
This PR does two things. 
- Add skeleton grid for both material-grids in storybook.
- Use CLSX for conditional rendering of css based on prop.
[DDFFORM-490]: https://reload.atlassian.net/browse/DDFFORM-490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DDFFORM 490 adjust css

src/apps/dashboard/dashboard-notification-list/Notifications.tsx, src/apps/dashboard/dashboard-notification/dashboard-notification.tsx, src/apps/dashboard/dashboard.test.tsx
https://reload.atlassian.net/browse/DDFLSBP-545
This PR removes the usage of red dots from notifications around the user menu & dashboard (+ adjusts tests).
-
-
=> Remove red dots

package.json, yarn.lock
Update dependencies to release 2024 18 1
=> Use release 2024.18.1

src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx
https://reload.atlassian.net/browse/DDFLSBP-584
Don't show digital loans in loan modals on dashboard:
- Returned too late modal
- To be returned soon modal
- Longer return time modal
-
-
=> Don't show digital loans on the dashboard

src/components/Buttons/ButtonTag.tsx, src/components/facet-line/FacetLineSelected.tsx
https://reload.atlassian.net/browse/DDFLSBP-590
Implemented focus management in ButtonTag and auto-focus on new facets in FacetLineSelected for enhanced accessibility
https://github.com/danskernesdigitalebibliotek/dpl-react/assets/105956/b15d836e-5cac-443e-b8ee-6387b8b1959f
=> Add focus to the last added facet in FacetLineSelected [DDFLSBP-590]

package.json, src/apps/create-patron-user-info/CreatePatron.dev.tsx, src/apps/create-patron-user-info/CreatePatron.tsx, src/apps/create-patron-user-info/RedirectToLoginMessage.tsx, src/apps/create-patron-user-info/UserInfo.tsx, src/apps/create-patron-user-info/helper.ts, yarn.lock
https://reload.atlassian.net/browse/DDFLSBP-615
Adds a story showing the redirect login message after submission of the patron registration form.
Belongs to a trinity together with:
+ https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/619
+ https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1091
=> Registration redirect login message

src/apps/dashboard/dashboard-fees/dashboard-fees.tsx, src/apps/dashboard/dashboard-notification-list/NotificationColumn.tsx, src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx, src/apps/dashboard/dashboard.tsx
https://reload.atlassian.net/browse/DDFLSBP-546
Supersize dashboard headlines according to https://www.figma.com/file/Zx9GrkFA3l4ISvyZD2q0Qi/Designsystem?type=design&node-id=15227%3A17027&mode=design&t=OR4lbQ8yQG2khFgn-1
-
=> Supersize dashboard headlines

src/apps/create-patron-user-info/UserInfo.tsx, src/apps/patron-page/PatronPage.tsx, src/apps/patron-page/sections/PincodeSection.tsx
https://reload.atlassian.net/browse/DDFLSBP-633
Don't let users submit user profile changes if password isn't valid.
-
-
=> Fix incorrect pincode message

src/apps/create-patron-user-info/CreatePatron.dev.tsx, src/apps/create-patron-user-info/CreatePatron.entry.tsx
https://reload.atlassian.net/browse/DDFLSBP-510
- createPatronChangePickupBodyText
- createPatronChangePickupHeaderText
-
[Sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1165)
=> Remove unused create patron texts

src/apps/patron-page/sections/StatusSection.tsx
https://reload.atlassian.net/browse/DDFLSBP-639
This is a fix for another existing bug discovered during testing of DDFLSBP-639
=> Handle libraryProfile zero values correctly [DDFLSBP-639]

src/apps/advanced-search/AdvancedSearchRow.tsx
https://reload.atlassian.net/browse/DDFLSBP-598
Focus on the new last advanced search row when deleting last row
-
-
=> Fix advanced search row focusing - the sequel

src/apps/search-header/search-header.tsx, src/components/header-dropdown/HeaderDropdown.tsx
https://reload.atlassian.net/browse/DDFLSBP-635
Add correct ARIA roles to ul and li elements in advanced search dropdown. Refactor advanced search button to an anchor element.
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/647
=> Fix ARIA roles and link element type [DDFLSBP-635]

src/apps/advanced-search/advanced-search.test.ts, src/components/multiselect/Multiselect.tsx
https://reload.atlassian.net/browse/DDFLSBP-601
Ensures that each Multiselect checkbox has a unique identifier.
=> Add unique ids for checkboxes [DDFLSBP-601]

src/components/facet-browser/FacetBrowserModalBody.tsx
https://reload.atlassian.net/browse/DDFLSBP-592
Turn filter browser modal filters into a list - because it is a list
-
-
=> Make filters into a list

src/components/find-on-shelf/FindOnShelfManifestationList.tsx, src/components/find-on-shelf/FindOnShelfManifestationListItem.tsx, src/components/find-on-shelf/FindOnShelfModalBody.tsx
https://reload.atlassian.net/browse/DDFLSBP-714
Add author at the end of the find-on-shelf modal location string
-
=> Add author name at the end of the find on shelf location string

src/apps/material-search/MaterialSearch.dev.tsx, src/apps/material-search/MaterialSearch.entry.tsx, src/apps/material-search/MaterialSearch.mount.ts, src/apps/material-search/MaterialSearch.tsx, src/apps/material-search/MaterialSearchInputs.tsx, src/apps/material-search/MaterialSearchList.tsx, src/apps/material-search/MaterialSearchLoading.tsx, src/apps/material-search/MaterialSearchPreview.tsx, src/apps/material-search/useGetMaterialListSearch.ts, src/apps/material-search/useGetSelectedWork.ts, src/apps/material-search/useInfiteScrollLoading.ts, src/apps/material-search/useUpdateFields.ts, src/components/cover/cover.tsx
Ticket: [DDFFORM-611](https://reload.atlassian.net/browse/DDFFORM-611)
This PR Depends on: 
CMS PR: https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1169
Design system PR: https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/636
This pr creates the react app MaterialSearch which will be used to search and select materials in the admin interface of drupal. 
There is a lot of functionality in the application. I've committed the changes in sizeable chunks that are relevant for each other, but it doesn't exclude that every commit depends on each other. 
I found this preferable over adding small connected parts and then expanding om them continuously. Use the main component `<MaterialSearch/>` for structural overview, otherwise see commit messages. 
- The console …
=> DDFFORM 611 backend anbefalings komp

src/components/find-on-shelf/FindOnShelfManifestationList.tsx
https://reload.atlassian.net/browse/DDFLSBP-717
Bringing design changes from the design system over.
-
[Sibling PR](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/668)
=> Use the new find-on-shelf__location-header class in find on shelf list

docs/architecture/adr-008-error-handling.md
https://reload.atlassian.net/browse/DDFLSBP-728
To spread the knwoledge about the current error handling in the react apps.
=> Add Architectural Decision Record about error handling

src/apps/reservation-list/modal/pause-reservation/pause-reservation.tsx
https://reload.atlassian.net/browse/DDFLSBP-749
Don't delete users' data when setting their reservations on hold
-
-
=> Don't delete users' data when setting their reservations on hold

src/apps/dashboard/dashboard-notification-list/dashboard-notification-list.tsx
https://reload.atlassian.net/browse/DDFLSBP-689
https://reload.atlassian.net/browse/DDFLSBP-692
Show digital loans on the dashboard page.
-
-
=> Fix dashboard loans not showing

src/core/mount.js, src/core/utils/extractErrorDetails.js, src/core/utils/forwardError.js
https://reload.atlassian.net/browse/DDFLSBP-569
Enhance ErrorBoundary to forward exceptions to window.onerror for logging in jsnlog.
(Exception fremprovokeret for test)
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/1077
=> Forward exceptions to window.onerror  [DDFLSBP-569]

src/apps/advanced-search/AdvancedSearch.dev.tsx, src/apps/advanced-search/AdvancedSearch.entry.tsx, src/apps/advanced-search/AdvancedSearch.tsx, src/apps/advanced-search/AdvancedSearchHeader.tsx, src/apps/advanced-search/AdvancedSearchResults.tsx, src/apps/advanced-search/CqlSearchHeader.tsx, src/apps/advanced-search/LocationFilter.ts
This is a copy of #1220 to automatically create a new demo environment.
=> Ddflsbp 654 demo

src/apps/material/material.tsx
DDFFORM-903
Jira [DDFFORM-903](https://reload.atlassian.net/browse/DDFFORM-903)
If the specified type in the URL does not exist in the data, we will fallback to the type in bestRepresentation.
This change is implemented because currently, if an incorrect type is specified, the page will load indefinitely.
Run it locally or on the Pr. 
Go the the page of a material. 
Change the type in the URL to something that doesn't exist. 
Verify that the fallback to bestRepresentation works. 
If you want to verify bestRep, look at the graphql data. 
[DDFFORM-903]: https://reload.atlassian.net/browse/DDFFORM-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implement fallback for material page.

src/components/search-bar/search-bar.tsx, src/components/search-bar/story-header.dev.inc.tsx
Reverts danskernesdigitalebibliotek/dpl-react#1359 as it was merged too soon.
=> Revert "DDFLSBP-637 - Change advanced search input element into and img element"

src/apps/menu/menu.test.ts, src/apps/menu/menu.tsx, src/components/search-bar/story-header.dev.inc.tsx
https://reload.atlassian.net/browse/DDFFORM-852
Update markup and CSS classes to align with changes in dpl-design-system
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/694
https://varnish.pr-1442.dpl-cms.dplplat01.dpl.reload.dk/frontpage
=> Show watch on small screens / Update markup and CSS classes to align with changes in dpl-design-system

src/apps/advanced-search/AdvancedSearchResults.tsx, src/apps/favorites-list/FavoritesList.tsx, src/apps/favorites-list/favorites-list.test.ts, src/apps/search-result/search-result-not-valid-search.tsx, src/apps/search-result/search-result-skeleton.tsx, src/apps/search-result/search-result-zero-hits.tsx, src/apps/search-result/search-result.test.ts, src/apps/search-result/search-result.tsx, src/components/card-item-list/MaterialListItem.tsx, src/components/card-item-list/SearchResultList.tsx, src/components/search-bar/search-result-header/SearchResultHeader.tsx
https://reload.atlassian.net/browse/DDFFORM-953
This pull request refactors the markup to align with the updates introduced in [dpl-design-system #708](https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/708). The main objective is to ensure consistent CSS styling for lists across both Drupal and React applications.
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1367
~~https://varnish.pr-1484.dpl-cms.dplplat01.dpl.reload.dk/search?q=dans~~
https://varnish.pr-1497.dpl-cms.dplplat01.dpl.reload.dk/search?q=dans
=> Unify lists between cms and react

src/components/find-on-shelf/FindOnShelfModalBody.tsx, src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFBRA-44
This PR introduces a new helper function that adds a comma between the first and second word in a string. 
-
-
=> Add comma between surname and name in find on shelf

src/components/facet-browser/__snapshots__/helper.ts.snap, src/components/facet-browser/helper.ts
https://reload.atlassian.net/browse/DDFBRA-48
This PR corrects a mistake where we were using incorrect filters in the facet browser.
-
-
=> Use MaterialTypesGeneral instead of WorkTypes in filters

src/components/availability-label/helper.ts, src/components/availability-label/usePhysicalAvailabilityData.ts, src/components/material/MaterialHeader.tsx, src/components/material/helper.ts
https://reload.atlassian.net/browse/DDFBRA-49
This PR fixes the viewing conditions for the text underneath action buttons on the material page. The logic was flawed, as the business logic is pretty complex. Now that's fixed + we have some comments in the code explaining the conditions that need to be met here.
-
-
=> We have XX specimens - fix business logic

src/apps/favorites-list/FavoritesList.tsx, src/components/card-item-list/card-list-item/card-list-item-adapter.tsx, src/components/card-item-list/card-list-item/card-list-item.tsx, src/components/search-bar/search-bar.tsx
https://reload.atlassian.net/browse/DDFBRA-30
This PR fixes an issue where some items on a user's favorites list had unfilled heart icons (meaning the item didn't belong to the list). This was happening because we weren't using the corresponding ID that matched the id that was saved in the "favorites material" API.
-
-
=> Fix favorites list - white hearts

src/apps/material/material.stories.tsx, src/core/utils/helpers/general.ts
https://reload.atlassian.net/browse/DDFBRA-101
This PR adds a new variant of a faust ID - including a dot "." 
Plus a story for it.
-
-
=> Ddfbra 101 fejl fbs vaerker fra naxos

package.json, yarn.lock
https://reload.atlassian.net/browse/DDFNEXT-207
Upgrade eslint-plugin-jsx-a11y to version 6.10.0
=> Upgrade eslint-plugin-jsx-a11y

package.json, src/components/alert/alert.jsx, yarn.lock
https://reload.atlassian.net/browse/DDFNEXT-204
Upgraded @reach/alert to version 0.18
=> Upgrade @reach/alert

package.json, yarn.lock
https://reload.atlassian.net/browse/DDFBRA-149
Upgraded react-error-boundary to version 4.1.2
=> Upgraded react-error-boundary

src/components/facet-browser/helper.ts, src/core/dbc-gateway/generated/graphql.schema.json, src/core/dbc-gateway/generated/graphql.tsx
https://reload.atlassian.net/browse/DDFBRA-43
This PR updates autogenerated FBI API code to be aligned to the newest API specs. Among other things, gamePlatform is added as one of the facetFieldEnum values. 
-
-
=> Update FBI graphql with gamePlatform

.github/PULL_REQUEST_TEMPLATE.md, .markdownlint-cli2.yaml, package.json, yarn.lock
https://reload.atlassian.net/browse/DDFNEXT-202
Update markdownlint-cli2 to version 0.16.0 fix pull request template formatting
=> Update markdownlint-cli2 to version 0.16.0 fix pull request template formatting

package.json, postcss.config.js, src/apps/material/__snapshots__/helper.ts.snap, src/components/facet-browser/__snapshots__/helper.ts.snap, src/tests/unit/__snapshots__/contact-info.test.tsx.snap, src/tests/unit/__snapshots__/info-labels.test.tsx.snap, yarn.lock
https://reload.atlassian.net/browse/DDFBRA-298
This PR bumps vitest package to 2.1.8
-
-
=> Bump vitest

package.json, yarn.lock
https://reload.atlassian.net/browse/DDFBRA-299
Read title 🙏 
-
-
=> Bump stylelint-config-recommended-scss and to latest

package.json, yarn.lock
https://reload.atlassian.net/browse/DDFBRA-300
See the title 🙏 
-
-
=> Bump vitest to latest version

package.json, yarn.lock
https://reload.atlassian.net/browse/DDFBRA-311
Bump `types/lodash` from "^4.17.5" to "^4.17.13"
=> DDFBRA-311 - Bump `types/lodash` from "^4.17.5" to "^4.17.13"

src/apps/search-result/useFilterHandler.tsx, src/components/facet-browser/__snapshots__/helper.ts.snap, src/components/facet-browser/facet-search.graphql, src/components/facet-browser/helper.ts, src/components/facet-line/intelligent-facets-search.graphql, src/core/dbc-gateway/generated/graphql.schema.json, src/core/dbc-gateway/generated/graphql.tsx
The gateway schema has been updated by DBC, which require us to handle a new `traceId` field for facets. This PR updates our generated graphql schema and queries to use the new field.
=> Update graphql schema

docs/README.md, docs/architecture/adr-009-remove-airbnb-lint-rules.md
https://reload.atlassian.net/browse/DDFBRA-405
- Update README with ESLint rule changes 
- Add ADR describing removal of Airbnb lint rules
=> docs: update README with ESLint rule changes + add ADR describing removal of Airbnb lint rules

src/components/material/digital-modal/DigitalModal.tsx, src/core/statistics/statistics.ts
https://reload.atlassian.net/browse/DDFSAL-40
https://varnish.pr-2194.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2194
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2194
Update tracking for "order digital copy"
This should not be tracked under as a normal reservation
=> DDFSAL-40 - Update tracking for "order digital copy"

src/core/utils/useSavePatron.tsx
https://reload.atlassian.net/browse/DDFSAL-104
This applies the key change from #1831 to 2025.17.x
=> DDFSAL-104 for 2025.17.x

src/core/utils/useSavePatron.tsx
https://reload.atlassian.net/browse/DDFSAL-104
This applies the key change from #1831 to 2025.18.x
=> DDFSAL-104 for 2025.18.x

cypress/fixtures/material-buttons/material-buttons-article-fbi-api.json, src/components/material/material-buttons/material-buttons.test.ts, src/components/material/material-buttons/online/MaterialButtonsOnline.tsx
https://reload.atlassian.net/browse/DDFBRA-502
Return the first active DBC Webarkiv element, but fallback to any other active element, if one from DBC is not found.
=> Prefer active DBC Webarkiv link for online materials

src/apps/material/material.stories.tsx, src/apps/material/material.tsx, src/components/atoms/links/Link.tsx, src/components/material/material-buttons/generic/MaterialSecondaryLink.tsx, src/components/material/material-buttons/online/MaterialButtonsOnline.tsx, src/components/material/material-buttons/online/MaterialButtonsOnlineInternal.tsx, src/components/reservation/OnlineInternalModal.tsx, src/components/reservation/OnlineInternalModalBody.tsx, src/core/statistics/statistics.ts, src/core/utils/useOnlineInternalHandleLoanReservation.ts
https://reload.atlassian.net/browse/DDFSAL-41
https://reload.atlassian.net/browse/DDFSAL-42
https://reload.atlassian.net/browse/DDFSAL-43
https://reload.atlassian.net/browse/DDFSAL-44
https://varnish.pr-2390.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2390
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2390
This pull request implements tracking for e-materials, including:
- Loans of e-materials
- Reservations of e-materials 
- Try feature for e-materials (teasers)
- Read/Listen interactions with e-materials
=> DDFSAL-41 DDFSAL-42 DDFSAL-43 DDFSAL-44 - Track E-Materials (Publizon)

src/components/facet-browser/FacetBrowserModalBody.tsx, src/components/facet-line/FacetLineFilters.tsx
https://reload.atlassian.net/browse/DDFBRA-690
This PR sorts intelligent filter "year" by relevance
-
-
=> Sort intelligent filter "year" in descending order

src/components/reservation/ReservationModalBody.tsx
https://reload.atlassian.net/browse/DDFSAL-120
https://varnish.pr-2492.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2492
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2492
Enhance Visibility of `InstantLoan` in `ReservationModal`
Reordered the ReservationModal to display the InstantLoan option at the top, improving user awareness of instant loan availability. No functional changes to the underlying logic.
This pull request modifies the `ReservationModalBody` component in `src/components/reservation/ReservationModalBody.tsx` to adjust the placement of the `InstantLoan` component. The changes ensure that the `InstantLoan` component is rendered earlier in the DOM structure, improving its visibility and alignment within …
=> DDFSAL-120 - Enhance Visibility of `InstantLoan` in `ReservationModal`

src/apps/search-header/search-header.tsx, src/apps/search-result/search-result.tsx, src/components/search-bar/search-bar.tsx
https://reload.atlassian.net/browse/DDFBRA-713
This PR makes it possible to search for 1 & 2 characters.
Autosuggest still opens only after writing at least 3 characters.
-
-
=> Make it possible to search for 1 & 2 characters

src/components/autosuggest-text/autosuggest-text-item.tsx, src/components/autosuggest-text/autosuggest-text.tsx
https://reload.atlassian.net/browse/DDFBRA-24
fix: remove generateItemId function to ensure keys are not changing during re-render
=> fix: remove generateItemId function

src/core/fbs/mutator/fetcher.ts
https://reload.atlassian.net/browse/DDFSAL-178
https://varnish.pr-2529.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2529
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2529
<s>On iOS/Safari, a successful pincode change request returns a 204 No Content response with no body, and it often omits or misreports the Content-Type header. Attempting to call .json() or catching a SyntaxError from parsing an empty or non-JSON response leads our client to incorrectly treat the update as a failure.
Changes
1.	Immediately short-circuits on 204 responses by returning null, avoiding any attempt to read the response body.
2.	Reads the response body into a text variable and only invokes JSON.parse if the Content-Type is explicitly …
=> DDFSAL-178 - Fix error when chane pincode from mobile (iPhone safari)

docs/architecture/README.md
=> Fix link to ADR example

src/apps/advanced-search/AdvancedSearch.entry.tsx, src/apps/advanced-search/AdvancedSearch.stories.tsx, src/apps/advanced-search/CqlSearchHeader.tsx, src/components/Dropdown/Dropdown.tsx, src/components/checkbox/Checkbox.tsx, src/components/forms/input/TextInput.tsx, src/components/forms/textarea/Textarea.tsx
https://reload.atlassian.net/browse/DDFSAL-92
https://varnish.pr-2611.dpl-cms.dplplat01.dpl.reload.dk/
https://ui.lagoon.dplplat01.dpl.reload.dk/projects/dpl-cms/dpl-cms-pr-2611
https://github.com/danskernesdigitalebibliotek/dpl-cms/pull/2611
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/915
This pull request is a new version of:
https://github.com/danskernesdigitalebibliotek/dpl-react/pull/1892
=> DDFSAL-92 - Enhance styling in advance search + Add CQL help link

src/apps/material/material.entry.tsx, src/apps/material/material.graphql, src/apps/material/material.stories.tsx, src/components/material/infomedia/InfomediaModal.tsx, src/components/material/infomedia/InfomediaModalBody.tsx, src/core/dbc-gateway/generated/graphql.schema.json, src/core/dbc-gateway/generated/graphql.ts
https://reload.atlassian.net/browse/DDFSAL-256
https://github.com/danskernesdigitalebibliotek/dpl-design-system/pull/951
=> DDFSAL-256 - Refactor Infomedia styles for improved layout and readability

src/components/material/MaterialAvailabilityText/online/MaterialAvailabilityTextOnline.tsx, src/components/material/MaterialHeader.tsx, src/components/material/helper.ts
https://reload.atlassian.net/browse/DDFBRA-715
- Check if user is logged in or not to prevent errors
- Removed unnecessary Publizon calls if not logged in
- Ensure blue title "materialIsIncludedText" is shown
=> feat: add check if user is logged in or not to prevent errors

.github/dependabot.yml, .nvmrc
Update Dependabot configuration to bring it in line with https://github.com/danskernesdigitalebibliotek/dpl-docs/pull/96
Please see code comments for additional commentary.
=> Dependabot update

src/apps/search-result/search-result.entry.tsx, src/apps/search-result/search-result.stories.tsx, src/apps/search-result/search-result.test.ts, src/apps/search-result/search-result.tsx, src/components/card-item-list/CardListInfoBox.tsx, src/components/card-item-list/SearchResultList.tsx
https://reload.atlassian.net/browse/DDFSAL-352
This PR introduces a new component called CardListInfoBox.tsx. Which is shown in as the first element when users are loading additional search result. 
desktop:
mobile:
=> Ddfsal 352 info box
